<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkAccessFlagBits2" type="bitmask">.
 *
 * A bitfield. Every `VkAccessFlags2` parameter and member
 * stays `int` on both sides, because `VkAccessFlagBits2::A | VkAccessFlagBits2::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkAccessFlagBits2: int
{
    case ACCESS_2_NONE = 0;
    case ACCESS_2_INDIRECT_COMMAND_READ_BIT = 1;
    case ACCESS_2_INDEX_READ_BIT = 2;
    case ACCESS_2_VERTEX_ATTRIBUTE_READ_BIT = 4;
    case ACCESS_2_UNIFORM_READ_BIT = 8;
    case ACCESS_2_INPUT_ATTACHMENT_READ_BIT = 16;
    case ACCESS_2_SHADER_READ_BIT = 32;
    case ACCESS_2_SHADER_WRITE_BIT = 64;
    case ACCESS_2_COLOR_ATTACHMENT_READ_BIT = 128;
    case ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT = 256;
    case ACCESS_2_DEPTH_STENCIL_ATTACHMENT_READ_BIT = 512;
    case ACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT = 1024;
    case ACCESS_2_TRANSFER_READ_BIT = 2048;
    case ACCESS_2_TRANSFER_WRITE_BIT = 4096;
    case ACCESS_2_HOST_READ_BIT = 8192;
    case ACCESS_2_HOST_WRITE_BIT = 16384;
    case ACCESS_2_MEMORY_READ_BIT = 32768;
    case ACCESS_2_MEMORY_WRITE_BIT = 65536;
    case ACCESS_2_SHADER_SAMPLED_READ_BIT = 4294967296;
    case ACCESS_2_SHADER_STORAGE_READ_BIT = 8589934592;
    case ACCESS_2_SHADER_STORAGE_WRITE_BIT = 17179869184;
}
