<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkBlendOp" type="enum">.
 */
enum VkBlendOp: int
{
    case ADD = 0;
    case SUBTRACT = 1;
    case REVERSE_SUBTRACT = 2;
    case MIN = 3;
    case MAX = 4;
}
