<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkBlendFactor" type="enum">.
 */
enum VkBlendFactor: int
{
    case ZERO = 0;
    case ONE = 1;
    case SRC_COLOR = 2;
    case ONE_MINUS_SRC_COLOR = 3;
    case DST_COLOR = 4;
    case ONE_MINUS_DST_COLOR = 5;
    case SRC_ALPHA = 6;
    case ONE_MINUS_SRC_ALPHA = 7;
    case DST_ALPHA = 8;
    case ONE_MINUS_DST_ALPHA = 9;
    case CONSTANT_COLOR = 10;
    case ONE_MINUS_CONSTANT_COLOR = 11;
    case CONSTANT_ALPHA = 12;
    case ONE_MINUS_CONSTANT_ALPHA = 13;
    case SRC_ALPHA_SATURATE = 14;
    case SRC1_COLOR = 15;
    case ONE_MINUS_SRC1_COLOR = 16;
    case SRC1_ALPHA = 17;
    case ONE_MINUS_SRC1_ALPHA = 18;
}
