<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkBufferUsageFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkBufferUsageFlags` parameter and member
 * stays `int` on both sides, because `VkBufferUsageFlagBits::A | VkBufferUsageFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkBufferUsageFlagBits: int
{
    case TRANSFER_SRC_BIT = 1;
    case TRANSFER_DST_BIT = 2;
    case UNIFORM_TEXEL_BUFFER_BIT = 4;
    case STORAGE_TEXEL_BUFFER_BIT = 8;
    case UNIFORM_BUFFER_BIT = 16;
    case STORAGE_BUFFER_BIT = 32;
    case INDEX_BUFFER_BIT = 64;
    case VERTEX_BUFFER_BIT = 128;
    case INDIRECT_BUFFER_BIT = 256;
    case SHADER_DEVICE_ADDRESS_BIT = 131072;
}
