<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkBufferUsageFlagBits2" type="bitmask">.
 *
 * A bitfield. Every `VkBufferUsageFlags2` parameter and member
 * stays `int` on both sides, because `VkBufferUsageFlagBits2::A | VkBufferUsageFlagBits2::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkBufferUsageFlagBits2: int
{
    case BUFFER_USAGE_2_TRANSFER_SRC_BIT = 1;
    case BUFFER_USAGE_2_TRANSFER_DST_BIT = 2;
    case BUFFER_USAGE_2_UNIFORM_TEXEL_BUFFER_BIT = 4;
    case BUFFER_USAGE_2_STORAGE_TEXEL_BUFFER_BIT = 8;
    case BUFFER_USAGE_2_UNIFORM_BUFFER_BIT = 16;
    case BUFFER_USAGE_2_STORAGE_BUFFER_BIT = 32;
    case BUFFER_USAGE_2_INDEX_BUFFER_BIT = 64;
    case BUFFER_USAGE_2_VERTEX_BUFFER_BIT = 128;
    case BUFFER_USAGE_2_INDIRECT_BUFFER_BIT = 256;
    case BUFFER_USAGE_2_SHADER_DEVICE_ADDRESS_BIT = 131072;
}
