<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkCommandPoolResetFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkCommandPoolResetFlags` parameter and member
 * stays `int` on both sides, because `VkCommandPoolResetFlagBits::A | VkCommandPoolResetFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkCommandPoolResetFlagBits: int
{
    case RELEASE_RESOURCES_BIT = 1;
}
