<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkCompareOp" type="enum">.
 */
enum VkCompareOp: int
{
    case NEVER = 0;
    case LESS = 1;
    case EQUAL = 2;
    case LESS_OR_EQUAL = 3;
    case GREATER = 4;
    case NOT_EQUAL = 5;
    case GREATER_OR_EQUAL = 6;
    case ALWAYS = 7;
}
