<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkCommandBufferResetFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkCommandBufferResetFlags` parameter and member
 * stays `int` on both sides, because `VkCommandBufferResetFlagBits::A | VkCommandBufferResetFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkCommandBufferResetFlagBits: int
{
    case RELEASE_RESOURCES_BIT = 1;
}
