<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkCommandBufferLevel" type="enum">.
 */
enum VkCommandBufferLevel: int
{
    case PRIMARY = 0;
    case SECONDARY = 1;
}
