<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkColorSpaceKHR" type="enum">.
 */
enum VkColorSpaceKHR: int
{
    case SRGB_NONLINEAR_KHR = 0;
}
