<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkDescriptorSetLayoutCreateFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkDescriptorSetLayoutCreateFlags` parameter and member
 * stays `int` on both sides, because `VkDescriptorSetLayoutCreateFlagBits::A | VkDescriptorSetLayoutCreateFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkDescriptorSetLayoutCreateFlagBits: int
{
    case UPDATE_AFTER_BIND_POOL_BIT = 2;
    case PUSH_DESCRIPTOR_BIT = 1;
}
