<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkDebugUtilsMessageTypeFlagBitsEXT" type="bitmask">.
 *
 * A bitfield. Every `VkDebugUtilsMessageTypeFlagsEXT` parameter and member
 * stays `int` on both sides, because `VkDebugUtilsMessageTypeFlagBitsEXT::A | VkDebugUtilsMessageTypeFlagBitsEXT::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkDebugUtilsMessageTypeFlagBitsEXT: int
{
    case GENERAL_BIT_EXT = 1;
    case VALIDATION_BIT_EXT = 2;
    case PERFORMANCE_BIT_EXT = 4;
}
