<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkDebugUtilsMessageSeverityFlagBitsEXT" type="bitmask">.
 *
 * A bitfield. Every `VkDebugUtilsMessageSeverityFlagsEXT` parameter and member
 * stays `int` on both sides, because `VkDebugUtilsMessageSeverityFlagBitsEXT::A | VkDebugUtilsMessageSeverityFlagBitsEXT::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkDebugUtilsMessageSeverityFlagBitsEXT: int
{
    case VERBOSE_BIT_EXT = 1;
    case INFO_BIT_EXT = 16;
    case WARNING_BIT_EXT = 256;
    case ERROR_BIT_EXT = 4096;
}
