<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkDependencyFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkDependencyFlags` parameter and member
 * stays `int` on both sides, because `VkDependencyFlagBits::A | VkDependencyFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkDependencyFlagBits: int
{
    case BY_REGION_BIT = 1;
    case DEVICE_GROUP_BIT = 4;
    case VIEW_LOCAL_BIT = 2;
}
