<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkDescriptorType" type="enum">.
 */
enum VkDescriptorType: int
{
    case SAMPLER = 0;
    case COMBINED_IMAGE_SAMPLER = 1;
    case SAMPLED_IMAGE = 2;
    case STORAGE_IMAGE = 3;
    case UNIFORM_TEXEL_BUFFER = 4;
    case STORAGE_TEXEL_BUFFER = 5;
    case UNIFORM_BUFFER = 6;
    case STORAGE_BUFFER = 7;
    case UNIFORM_BUFFER_DYNAMIC = 8;
    case STORAGE_BUFFER_DYNAMIC = 9;
    case INPUT_ATTACHMENT = 10;
    case INLINE_UNIFORM_BLOCK = 1000138000;
}
