<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkDeviceGroupPresentModeFlagBitsKHR" type="bitmask">.
 *
 * A bitfield. Every `VkDeviceGroupPresentModeFlagsKHR` parameter and member
 * stays `int` on both sides, because `VkDeviceGroupPresentModeFlagBitsKHR::A | VkDeviceGroupPresentModeFlagBitsKHR::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkDeviceGroupPresentModeFlagBitsKHR: int
{
    case LOCAL_BIT_KHR = 1;
    case REMOTE_BIT_KHR = 2;
    case SUM_BIT_KHR = 4;
    case LOCAL_MULTI_DEVICE_BIT_KHR = 8;
}
