<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkEventCreateFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkEventCreateFlags` parameter and member
 * stays `int` on both sides, because `VkEventCreateFlagBits::A | VkEventCreateFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkEventCreateFlagBits: int
{
    case DEVICE_ONLY_BIT = 1;
}
