<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkExternalFenceHandleTypeFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkExternalFenceHandleTypeFlags` parameter and member
 * stays `int` on both sides, because `VkExternalFenceHandleTypeFlagBits::A | VkExternalFenceHandleTypeFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkExternalFenceHandleTypeFlagBits: int
{
    case OPAQUE_FD_BIT = 1;
    case OPAQUE_WIN32_BIT = 2;
    case OPAQUE_WIN32_KMT_BIT = 4;
    case SYNC_FD_BIT = 8;
}
