<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkFenceCreateFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkFenceCreateFlags` parameter and member
 * stays `int` on both sides, because `VkFenceCreateFlagBits::A | VkFenceCreateFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkFenceCreateFlagBits: int
{
    case SIGNALED_BIT = 1;
}
