<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkHostImageCopyFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkHostImageCopyFlags` parameter and member
 * stays `int` on both sides, because `VkHostImageCopyFlagBits::A | VkHostImageCopyFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkHostImageCopyFlagBits: int
{
    case MEMCPY_BIT = 1;
}
