<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkImageViewType" type="enum">.
 */
enum VkImageViewType: int
{
    case TYPE_1D = 0;
    case TYPE_2D = 1;
    case TYPE_3D = 2;
    case CUBE = 3;
    case TYPE_1D_ARRAY = 4;
    case TYPE_2D_ARRAY = 5;
    case CUBE_ARRAY = 6;
}
