<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkIndexType" type="enum">.
 */
enum VkIndexType: int
{
    case UINT16 = 0;
    case UINT32 = 1;
    case UINT8 = 1000265000;
}
