<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkMemoryHeapFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkMemoryHeapFlags` parameter and member
 * stays `int` on both sides, because `VkMemoryHeapFlagBits::A | VkMemoryHeapFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkMemoryHeapFlagBits: int
{
    case DEVICE_LOCAL_BIT = 1;
    case MULTI_INSTANCE_BIT = 2;
}
