<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkMemoryPropertyFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkMemoryPropertyFlags` parameter and member
 * stays `int` on both sides, because `VkMemoryPropertyFlagBits::A | VkMemoryPropertyFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkMemoryPropertyFlagBits: int
{
    case DEVICE_LOCAL_BIT = 1;
    case HOST_VISIBLE_BIT = 2;
    case HOST_COHERENT_BIT = 4;
    case HOST_CACHED_BIT = 8;
    case LAZILY_ALLOCATED_BIT = 16;
    case PROTECTED_BIT = 32;
}
