<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkPipelineStageFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkPipelineStageFlags` parameter and member
 * stays `int` on both sides, because `VkPipelineStageFlagBits::A | VkPipelineStageFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkPipelineStageFlagBits: int
{
    case TOP_OF_PIPE_BIT = 1;
    case DRAW_INDIRECT_BIT = 2;
    case VERTEX_INPUT_BIT = 4;
    case VERTEX_SHADER_BIT = 8;
    case TESSELLATION_CONTROL_SHADER_BIT = 16;
    case TESSELLATION_EVALUATION_SHADER_BIT = 32;
    case GEOMETRY_SHADER_BIT = 64;
    case FRAGMENT_SHADER_BIT = 128;
    case EARLY_FRAGMENT_TESTS_BIT = 256;
    case LATE_FRAGMENT_TESTS_BIT = 512;
    case COLOR_ATTACHMENT_OUTPUT_BIT = 1024;
    case COMPUTE_SHADER_BIT = 2048;
    case TRANSFER_BIT = 4096;
    case BOTTOM_OF_PIPE_BIT = 8192;
    case HOST_BIT = 16384;
    case ALL_GRAPHICS_BIT = 32768;
    case ALL_COMMANDS_BIT = 65536;
    case NONE = 0;
}
