<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkPipelineCreationFeedbackFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkPipelineCreationFeedbackFlags` parameter and member
 * stays `int` on both sides, because `VkPipelineCreationFeedbackFlagBits::A | VkPipelineCreationFeedbackFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkPipelineCreationFeedbackFlagBits: int
{
    case VALID_BIT = 1;
    case APPLICATION_PIPELINE_CACHE_HIT_BIT = 2;
    case BASE_PIPELINE_ACCELERATION_BIT = 4;
}
