<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkPipelineCreateFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkPipelineCreateFlags` parameter and member
 * stays `int` on both sides, because `VkPipelineCreateFlagBits::A | VkPipelineCreateFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkPipelineCreateFlagBits: int
{
    case DISABLE_OPTIMIZATION_BIT = 1;
    case ALLOW_DERIVATIVES_BIT = 2;
    case DERIVATIVE_BIT = 4;
    case DISPATCH_BASE_BIT = 16;
    case VIEW_INDEX_FROM_DEVICE_INDEX_BIT = 8;
    case FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT = 256;
    case EARLY_RETURN_ON_FAILURE_BIT = 512;
    case NO_PROTECTED_ACCESS_BIT = 134217728;
    case PROTECTED_ACCESS_ONLY_BIT = 1073741824;
}
