<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkPipelineCreateFlagBits2" type="bitmask">.
 *
 * A bitfield. Every `VkPipelineCreateFlags2` parameter and member
 * stays `int` on both sides, because `VkPipelineCreateFlagBits2::A | VkPipelineCreateFlagBits2::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkPipelineCreateFlagBits2: int
{
    case PIPELINE_CREATE_2_DISABLE_OPTIMIZATION_BIT = 1;
    case PIPELINE_CREATE_2_ALLOW_DERIVATIVES_BIT = 2;
    case PIPELINE_CREATE_2_DERIVATIVE_BIT = 4;
    case PIPELINE_CREATE_2_VIEW_INDEX_FROM_DEVICE_INDEX_BIT = 8;
    case PIPELINE_CREATE_2_DISPATCH_BASE_BIT = 16;
    case PIPELINE_CREATE_2_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT = 256;
    case PIPELINE_CREATE_2_EARLY_RETURN_ON_FAILURE_BIT = 512;
    case PIPELINE_CREATE_2_NO_PROTECTED_ACCESS_BIT = 134217728;
    case PIPELINE_CREATE_2_PROTECTED_ACCESS_ONLY_BIT = 1073741824;
}
