<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkPointClippingBehavior" type="enum">.
 */
enum VkPointClippingBehavior: int
{
    case ALL_CLIP_PLANES = 0;
    case USER_CLIP_PLANES_ONLY = 1;
}
