<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkPrimitiveTopology" type="enum">.
 */
enum VkPrimitiveTopology: int
{
    case POINT_LIST = 0;
    case LINE_LIST = 1;
    case LINE_STRIP = 2;
    case TRIANGLE_LIST = 3;
    case TRIANGLE_STRIP = 4;
    case TRIANGLE_FAN = 5;
    case LINE_LIST_WITH_ADJACENCY = 6;
    case LINE_STRIP_WITH_ADJACENCY = 7;
    case TRIANGLE_LIST_WITH_ADJACENCY = 8;
    case TRIANGLE_STRIP_WITH_ADJACENCY = 9;
    case PATCH_LIST = 10;
}
