<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkPresentModeKHR" type="enum">.
 */
enum VkPresentModeKHR: int
{
    case IMMEDIATE_KHR = 0;
    case MAILBOX_KHR = 1;
    case FIFO_KHR = 2;
    case FIFO_RELAXED_KHR = 3;
}
