<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkQueryResultFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkQueryResultFlags` parameter and member
 * stays `int` on both sides, because `VkQueryResultFlagBits::A | VkQueryResultFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkQueryResultFlagBits: int
{
    case RESULT_64_BIT = 1;
    case WAIT_BIT = 2;
    case WITH_AVAILABILITY_BIT = 4;
    case PARTIAL_BIT = 8;
}
