<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkQueryPipelineStatisticFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkQueryPipelineStatisticFlags` parameter and member
 * stays `int` on both sides, because `VkQueryPipelineStatisticFlagBits::A | VkQueryPipelineStatisticFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkQueryPipelineStatisticFlagBits: int
{
    case INPUT_ASSEMBLY_VERTICES_BIT = 1;
    case INPUT_ASSEMBLY_PRIMITIVES_BIT = 2;
    case VERTEX_SHADER_INVOCATIONS_BIT = 4;
    case GEOMETRY_SHADER_INVOCATIONS_BIT = 8;
    case GEOMETRY_SHADER_PRIMITIVES_BIT = 16;
    case CLIPPING_INVOCATIONS_BIT = 32;
    case CLIPPING_PRIMITIVES_BIT = 64;
    case FRAGMENT_SHADER_INVOCATIONS_BIT = 128;
    case TESSELLATION_CONTROL_SHADER_PATCHES_BIT = 256;
    case TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT = 512;
    case COMPUTE_SHADER_INVOCATIONS_BIT = 1024;
}
