<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkQueueGlobalPriority" type="enum">.
 */
enum VkQueueGlobalPriority: int
{
    case LOW = 128;
    case MEDIUM = 256;
    case HIGH = 512;
    case REALTIME = 1024;
}
