<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkSamplerYcbcrModelConversion" type="enum">.
 */
enum VkSamplerYcbcrModelConversion: int
{
    case RGB_IDENTITY = 0;
    case YCBCR_IDENTITY = 1;
    case YCBCR_709 = 2;
    case YCBCR_601 = 3;
    case YCBCR_2020 = 4;
}
