<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkShaderFloatControlsIndependence" type="enum">.
 */
enum VkShaderFloatControlsIndependence: int
{
    case INDEPENDENCE_32_BIT_ONLY = 0;
    case ALL = 1;
    case NONE = 2;
}
