<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkSparseImageFormatFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkSparseImageFormatFlags` parameter and member
 * stays `int` on both sides, because `VkSparseImageFormatFlagBits::A | VkSparseImageFormatFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkSparseImageFormatFlagBits: int
{
    case SINGLE_MIPTAIL_BIT = 1;
    case ALIGNED_MIP_SIZE_BIT = 2;
    case NONSTANDARD_BLOCK_SIZE_BIT = 4;
}
