<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkSubgroupFeatureFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkSubgroupFeatureFlags` parameter and member
 * stays `int` on both sides, because `VkSubgroupFeatureFlagBits::A | VkSubgroupFeatureFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkSubgroupFeatureFlagBits: int
{
    case BASIC_BIT = 1;
    case VOTE_BIT = 2;
    case ARITHMETIC_BIT = 4;
    case BALLOT_BIT = 8;
    case SHUFFLE_BIT = 16;
    case SHUFFLE_RELATIVE_BIT = 32;
    case CLUSTERED_BIT = 64;
    case QUAD_BIT = 128;
    case ROTATE_BIT = 512;
    case ROTATE_CLUSTERED_BIT = 1024;
}
