<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkSubpassContents" type="enum">.
 */
enum VkSubpassContents: int
{
    case INLINE = 0;
    case SECONDARY_COMMAND_BUFFERS = 1;
}
