<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkSurfaceTransformFlagBitsKHR" type="bitmask">.
 *
 * A bitfield. Every `VkSurfaceTransformFlagsKHR` parameter and member
 * stays `int` on both sides, because `VkSurfaceTransformFlagBitsKHR::A | VkSurfaceTransformFlagBitsKHR::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkSurfaceTransformFlagBitsKHR: int
{
    case IDENTITY_BIT_KHR = 1;
    case ROTATE_90_BIT_KHR = 2;
    case ROTATE_180_BIT_KHR = 4;
    case ROTATE_270_BIT_KHR = 8;
    case HORIZONTAL_MIRROR_BIT_KHR = 16;
    case HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR = 32;
    case HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR = 64;
    case HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR = 128;
    case INHERIT_BIT_KHR = 256;
}
