<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <enums name="VkSubmitFlagBits" type="bitmask">.
 *
 * A bitfield. Every `VkSubmitFlags` parameter and member
 * stays `int` on both sides, because `VkSubmitFlagBits::A | VkSubmitFlagBits::B`
 * is a TypeError in PHP — write `->value | ->value`.
 */
enum VkSubmitFlagBits: int
{
    case PROTECTED_BIT = 1;
}
