<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\VK;

use Jovian\Bindings\Vulkan\Enums\VkFilter;
use Jovian\Bindings\Vulkan\Enums\VkFormat;
use Jovian\Bindings\Vulkan\Enums\VkImageLayout;
use Jovian\Bindings\Vulkan\Enums\VkImageTiling;
use Jovian\Bindings\Vulkan\Enums\VkImageType;
use Jovian\Bindings\Vulkan\Enums\VkIndexType;
use Jovian\Bindings\Vulkan\Enums\VkPipelineBindPoint;
use Jovian\Bindings\Vulkan\Enums\VkPipelineStageFlagBits;
use Jovian\Bindings\Vulkan\Enums\VkResult;
use Jovian\Bindings\Vulkan\Enums\VkSampleCountFlagBits;
use Jovian\Bindings\Vulkan\Enums\VkSubpassContents;
use Vulkan\VK\VK10\VK10 as ExtVK10;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
final class VK10
{
    public static function vkCreateInstance(int $pCreateInfo, int $pAllocator, int $pInstance): VkResult|int
    {
        return ExtVK10::vkCreateInstance($pCreateInfo, $pAllocator, $pInstance);
    }

    public static function vkDestroyInstance(int $instance, int $pAllocator): void
    {
        ExtVK10::vkDestroyInstance($instance, $pAllocator);
    }

    public static function vkEnumeratePhysicalDevices(int $instance, int $pPhysicalDeviceCount, int $pPhysicalDevices): VkResult|int
    {
        return ExtVK10::vkEnumeratePhysicalDevices($instance, $pPhysicalDeviceCount, $pPhysicalDevices);
    }

    public static function vkGetPhysicalDeviceFeatures(int $physicalDevice, int $pFeatures): void
    {
        ExtVK10::vkGetPhysicalDeviceFeatures($physicalDevice, $pFeatures);
    }

    public static function vkGetPhysicalDeviceFormatProperties(int $physicalDevice, VkFormat|int $format, int $pFormatProperties): void
    {
        ExtVK10::vkGetPhysicalDeviceFormatProperties($physicalDevice, $format instanceof \BackedEnum ? $format->value : $format, $pFormatProperties);
    }

    public static function vkGetPhysicalDeviceImageFormatProperties(int $physicalDevice, VkFormat|int $format, VkImageType|int $type, VkImageTiling|int $tiling, int $usage, int $flags, int $pImageFormatProperties): VkResult|int
    {
        return ExtVK10::vkGetPhysicalDeviceImageFormatProperties($physicalDevice, $format instanceof \BackedEnum ? $format->value : $format, $type instanceof \BackedEnum ? $type->value : $type, $tiling instanceof \BackedEnum ? $tiling->value : $tiling, $usage, $flags, $pImageFormatProperties);
    }

    public static function vkGetPhysicalDeviceProperties(int $physicalDevice, int $pProperties): void
    {
        ExtVK10::vkGetPhysicalDeviceProperties($physicalDevice, $pProperties);
    }

    public static function vkGetPhysicalDeviceQueueFamilyProperties(int $physicalDevice, int $pQueueFamilyPropertyCount, int $pQueueFamilyProperties): void
    {
        ExtVK10::vkGetPhysicalDeviceQueueFamilyProperties($physicalDevice, $pQueueFamilyPropertyCount, $pQueueFamilyProperties);
    }

    public static function vkGetPhysicalDeviceMemoryProperties(int $physicalDevice, int $pMemoryProperties): void
    {
        ExtVK10::vkGetPhysicalDeviceMemoryProperties($physicalDevice, $pMemoryProperties);
    }

    public static function vkGetInstanceProcAddr(int $instance, string $pName): int
    {
        return ExtVK10::vkGetInstanceProcAddr($instance, $pName);
    }

    public static function vkGetDeviceProcAddr(int $device, string $pName): int
    {
        return ExtVK10::vkGetDeviceProcAddr($device, $pName);
    }

    public static function vkCreateDevice(int $physicalDevice, int $pCreateInfo, int $pAllocator, int $pDevice): VkResult|int
    {
        return ExtVK10::vkCreateDevice($physicalDevice, $pCreateInfo, $pAllocator, $pDevice);
    }

    public static function vkDestroyDevice(int $device, int $pAllocator): void
    {
        ExtVK10::vkDestroyDevice($device, $pAllocator);
    }

    public static function vkEnumerateInstanceExtensionProperties(string $pLayerName, int $pPropertyCount, int $pProperties): VkResult|int
    {
        return ExtVK10::vkEnumerateInstanceExtensionProperties($pLayerName, $pPropertyCount, $pProperties);
    }

    public static function vkEnumerateDeviceExtensionProperties(int $physicalDevice, string $pLayerName, int $pPropertyCount, int $pProperties): VkResult|int
    {
        return ExtVK10::vkEnumerateDeviceExtensionProperties($physicalDevice, $pLayerName, $pPropertyCount, $pProperties);
    }

    public static function vkEnumerateInstanceLayerProperties(int $pPropertyCount, int $pProperties): VkResult|int
    {
        return ExtVK10::vkEnumerateInstanceLayerProperties($pPropertyCount, $pProperties);
    }

    public static function vkEnumerateDeviceLayerProperties(int $physicalDevice, int $pPropertyCount, int $pProperties): VkResult|int
    {
        return ExtVK10::vkEnumerateDeviceLayerProperties($physicalDevice, $pPropertyCount, $pProperties);
    }

    public static function vkGetDeviceQueue(int $device, int $queueFamilyIndex, int $queueIndex, int $pQueue): void
    {
        ExtVK10::vkGetDeviceQueue($device, $queueFamilyIndex, $queueIndex, $pQueue);
    }

    public static function vkQueueSubmit(int $queue, int $submitCount, int $pSubmits, int $fence): VkResult|int
    {
        return ExtVK10::vkQueueSubmit($queue, $submitCount, $pSubmits, $fence);
    }

    public static function vkQueueWaitIdle(int $queue): VkResult|int
    {
        return ExtVK10::vkQueueWaitIdle($queue);
    }

    public static function vkDeviceWaitIdle(int $device): VkResult|int
    {
        return ExtVK10::vkDeviceWaitIdle($device);
    }

    public static function vkAllocateMemory(int $device, int $pAllocateInfo, int $pAllocator, int $pMemory): VkResult|int
    {
        return ExtVK10::vkAllocateMemory($device, $pAllocateInfo, $pAllocator, $pMemory);
    }

    public static function vkFreeMemory(int $device, int $memory, int $pAllocator): void
    {
        ExtVK10::vkFreeMemory($device, $memory, $pAllocator);
    }

    public static function vkMapMemory(int $device, int $memory, int $offset, int $size, int $flags, int $ppData): VkResult|int
    {
        return ExtVK10::vkMapMemory($device, $memory, $offset, $size, $flags, $ppData);
    }

    public static function vkUnmapMemory(int $device, int $memory): void
    {
        ExtVK10::vkUnmapMemory($device, $memory);
    }

    public static function vkFlushMappedMemoryRanges(int $device, int $memoryRangeCount, int $pMemoryRanges): VkResult|int
    {
        return ExtVK10::vkFlushMappedMemoryRanges($device, $memoryRangeCount, $pMemoryRanges);
    }

    public static function vkInvalidateMappedMemoryRanges(int $device, int $memoryRangeCount, int $pMemoryRanges): VkResult|int
    {
        return ExtVK10::vkInvalidateMappedMemoryRanges($device, $memoryRangeCount, $pMemoryRanges);
    }

    public static function vkGetDeviceMemoryCommitment(int $device, int $memory, int $pCommittedMemoryInBytes): void
    {
        ExtVK10::vkGetDeviceMemoryCommitment($device, $memory, $pCommittedMemoryInBytes);
    }

    public static function vkBindBufferMemory(int $device, int $buffer, int $memory, int $memoryOffset): VkResult|int
    {
        return ExtVK10::vkBindBufferMemory($device, $buffer, $memory, $memoryOffset);
    }

    public static function vkBindImageMemory(int $device, int $image, int $memory, int $memoryOffset): VkResult|int
    {
        return ExtVK10::vkBindImageMemory($device, $image, $memory, $memoryOffset);
    }

    public static function vkGetBufferMemoryRequirements(int $device, int $buffer, int $pMemoryRequirements): void
    {
        ExtVK10::vkGetBufferMemoryRequirements($device, $buffer, $pMemoryRequirements);
    }

    public static function vkGetImageMemoryRequirements(int $device, int $image, int $pMemoryRequirements): void
    {
        ExtVK10::vkGetImageMemoryRequirements($device, $image, $pMemoryRequirements);
    }

    public static function vkGetImageSparseMemoryRequirements(int $device, int $image, int $pSparseMemoryRequirementCount, int $pSparseMemoryRequirements): void
    {
        ExtVK10::vkGetImageSparseMemoryRequirements($device, $image, $pSparseMemoryRequirementCount, $pSparseMemoryRequirements);
    }

    public static function vkGetPhysicalDeviceSparseImageFormatProperties(int $physicalDevice, VkFormat|int $format, VkImageType|int $type, VkSampleCountFlagBits|int $samples, int $usage, VkImageTiling|int $tiling, int $pPropertyCount, int $pProperties): void
    {
        ExtVK10::vkGetPhysicalDeviceSparseImageFormatProperties($physicalDevice, $format instanceof \BackedEnum ? $format->value : $format, $type instanceof \BackedEnum ? $type->value : $type, $samples instanceof \BackedEnum ? $samples->value : $samples, $usage, $tiling instanceof \BackedEnum ? $tiling->value : $tiling, $pPropertyCount, $pProperties);
    }

    public static function vkQueueBindSparse(int $queue, int $bindInfoCount, int $pBindInfo, int $fence): VkResult|int
    {
        return ExtVK10::vkQueueBindSparse($queue, $bindInfoCount, $pBindInfo, $fence);
    }

    public static function vkCreateFence(int $device, int $pCreateInfo, int $pAllocator, int $pFence): VkResult|int
    {
        return ExtVK10::vkCreateFence($device, $pCreateInfo, $pAllocator, $pFence);
    }

    public static function vkDestroyFence(int $device, int $fence, int $pAllocator): void
    {
        ExtVK10::vkDestroyFence($device, $fence, $pAllocator);
    }

    public static function vkResetFences(int $device, int $fenceCount, int $pFences): VkResult|int
    {
        return ExtVK10::vkResetFences($device, $fenceCount, $pFences);
    }

    public static function vkGetFenceStatus(int $device, int $fence): VkResult|int
    {
        return ExtVK10::vkGetFenceStatus($device, $fence);
    }

    public static function vkWaitForFences(int $device, int $fenceCount, int $pFences, bool $waitAll, int $timeout): VkResult|int
    {
        return ExtVK10::vkWaitForFences($device, $fenceCount, $pFences, $waitAll, $timeout);
    }

    public static function vkCreateSemaphore(int $device, int $pCreateInfo, int $pAllocator, int $pSemaphore): VkResult|int
    {
        return ExtVK10::vkCreateSemaphore($device, $pCreateInfo, $pAllocator, $pSemaphore);
    }

    public static function vkDestroySemaphore(int $device, int $semaphore, int $pAllocator): void
    {
        ExtVK10::vkDestroySemaphore($device, $semaphore, $pAllocator);
    }

    public static function vkCreateQueryPool(int $device, int $pCreateInfo, int $pAllocator, int $pQueryPool): VkResult|int
    {
        return ExtVK10::vkCreateQueryPool($device, $pCreateInfo, $pAllocator, $pQueryPool);
    }

    public static function vkDestroyQueryPool(int $device, int $queryPool, int $pAllocator): void
    {
        ExtVK10::vkDestroyQueryPool($device, $queryPool, $pAllocator);
    }

    public static function vkGetQueryPoolResults(int $device, int $queryPool, int $firstQuery, int $queryCount, int $dataSize, int $pData, int $stride, int $flags): VkResult|int
    {
        return ExtVK10::vkGetQueryPoolResults($device, $queryPool, $firstQuery, $queryCount, $dataSize, $pData, $stride, $flags);
    }

    public static function vkCreateBuffer(int $device, int $pCreateInfo, int $pAllocator, int $pBuffer): VkResult|int
    {
        return ExtVK10::vkCreateBuffer($device, $pCreateInfo, $pAllocator, $pBuffer);
    }

    public static function vkDestroyBuffer(int $device, int $buffer, int $pAllocator): void
    {
        ExtVK10::vkDestroyBuffer($device, $buffer, $pAllocator);
    }

    public static function vkCreateImage(int $device, int $pCreateInfo, int $pAllocator, int $pImage): VkResult|int
    {
        return ExtVK10::vkCreateImage($device, $pCreateInfo, $pAllocator, $pImage);
    }

    public static function vkDestroyImage(int $device, int $image, int $pAllocator): void
    {
        ExtVK10::vkDestroyImage($device, $image, $pAllocator);
    }

    public static function vkGetImageSubresourceLayout(int $device, int $image, int $pSubresource, int $pLayout): void
    {
        ExtVK10::vkGetImageSubresourceLayout($device, $image, $pSubresource, $pLayout);
    }

    public static function vkCreateImageView(int $device, int $pCreateInfo, int $pAllocator, int $pView): VkResult|int
    {
        return ExtVK10::vkCreateImageView($device, $pCreateInfo, $pAllocator, $pView);
    }

    public static function vkDestroyImageView(int $device, int $imageView, int $pAllocator): void
    {
        ExtVK10::vkDestroyImageView($device, $imageView, $pAllocator);
    }

    public static function vkCreateCommandPool(int $device, int $pCreateInfo, int $pAllocator, int $pCommandPool): VkResult|int
    {
        return ExtVK10::vkCreateCommandPool($device, $pCreateInfo, $pAllocator, $pCommandPool);
    }

    public static function vkDestroyCommandPool(int $device, int $commandPool, int $pAllocator): void
    {
        ExtVK10::vkDestroyCommandPool($device, $commandPool, $pAllocator);
    }

    public static function vkResetCommandPool(int $device, int $commandPool, int $flags): VkResult|int
    {
        return ExtVK10::vkResetCommandPool($device, $commandPool, $flags);
    }

    public static function vkAllocateCommandBuffers(int $device, int $pAllocateInfo, int $pCommandBuffers): VkResult|int
    {
        return ExtVK10::vkAllocateCommandBuffers($device, $pAllocateInfo, $pCommandBuffers);
    }

    public static function vkFreeCommandBuffers(int $device, int $commandPool, int $commandBufferCount, int $pCommandBuffers): void
    {
        ExtVK10::vkFreeCommandBuffers($device, $commandPool, $commandBufferCount, $pCommandBuffers);
    }

    public static function vkBeginCommandBuffer(int $commandBuffer, int $pBeginInfo): VkResult|int
    {
        return ExtVK10::vkBeginCommandBuffer($commandBuffer, $pBeginInfo);
    }

    public static function vkEndCommandBuffer(int $commandBuffer): VkResult|int
    {
        return ExtVK10::vkEndCommandBuffer($commandBuffer);
    }

    public static function vkResetCommandBuffer(int $commandBuffer, int $flags): VkResult|int
    {
        return ExtVK10::vkResetCommandBuffer($commandBuffer, $flags);
    }

    public static function vkCmdCopyBuffer(int $commandBuffer, int $srcBuffer, int $dstBuffer, int $regionCount, int $pRegions): void
    {
        ExtVK10::vkCmdCopyBuffer($commandBuffer, $srcBuffer, $dstBuffer, $regionCount, $pRegions);
    }

    public static function vkCmdCopyImage(int $commandBuffer, int $srcImage, VkImageLayout|int $srcImageLayout, int $dstImage, VkImageLayout|int $dstImageLayout, int $regionCount, int $pRegions): void
    {
        ExtVK10::vkCmdCopyImage($commandBuffer, $srcImage, $srcImageLayout instanceof \BackedEnum ? $srcImageLayout->value : $srcImageLayout, $dstImage, $dstImageLayout instanceof \BackedEnum ? $dstImageLayout->value : $dstImageLayout, $regionCount, $pRegions);
    }

    public static function vkCmdCopyBufferToImage(int $commandBuffer, int $srcBuffer, int $dstImage, VkImageLayout|int $dstImageLayout, int $regionCount, int $pRegions): void
    {
        ExtVK10::vkCmdCopyBufferToImage($commandBuffer, $srcBuffer, $dstImage, $dstImageLayout instanceof \BackedEnum ? $dstImageLayout->value : $dstImageLayout, $regionCount, $pRegions);
    }

    public static function vkCmdCopyImageToBuffer(int $commandBuffer, int $srcImage, VkImageLayout|int $srcImageLayout, int $dstBuffer, int $regionCount, int $pRegions): void
    {
        ExtVK10::vkCmdCopyImageToBuffer($commandBuffer, $srcImage, $srcImageLayout instanceof \BackedEnum ? $srcImageLayout->value : $srcImageLayout, $dstBuffer, $regionCount, $pRegions);
    }

    public static function vkCmdUpdateBuffer(int $commandBuffer, int $dstBuffer, int $dstOffset, int $dataSize, int $pData): void
    {
        ExtVK10::vkCmdUpdateBuffer($commandBuffer, $dstBuffer, $dstOffset, $dataSize, $pData);
    }

    public static function vkCmdFillBuffer(int $commandBuffer, int $dstBuffer, int $dstOffset, int $size, int $data): void
    {
        ExtVK10::vkCmdFillBuffer($commandBuffer, $dstBuffer, $dstOffset, $size, $data);
    }

    public static function vkCmdPipelineBarrier(int $commandBuffer, int $srcStageMask, int $dstStageMask, int $dependencyFlags, int $memoryBarrierCount, int $pMemoryBarriers, int $bufferMemoryBarrierCount, int $pBufferMemoryBarriers, int $imageMemoryBarrierCount, int $pImageMemoryBarriers): void
    {
        ExtVK10::vkCmdPipelineBarrier($commandBuffer, $srcStageMask, $dstStageMask, $dependencyFlags, $memoryBarrierCount, $pMemoryBarriers, $bufferMemoryBarrierCount, $pBufferMemoryBarriers, $imageMemoryBarrierCount, $pImageMemoryBarriers);
    }

    public static function vkCmdBeginQuery(int $commandBuffer, int $queryPool, int $query, int $flags): void
    {
        ExtVK10::vkCmdBeginQuery($commandBuffer, $queryPool, $query, $flags);
    }

    public static function vkCmdEndQuery(int $commandBuffer, int $queryPool, int $query): void
    {
        ExtVK10::vkCmdEndQuery($commandBuffer, $queryPool, $query);
    }

    public static function vkCmdResetQueryPool(int $commandBuffer, int $queryPool, int $firstQuery, int $queryCount): void
    {
        ExtVK10::vkCmdResetQueryPool($commandBuffer, $queryPool, $firstQuery, $queryCount);
    }

    public static function vkCmdWriteTimestamp(int $commandBuffer, VkPipelineStageFlagBits|int $pipelineStage, int $queryPool, int $query): void
    {
        ExtVK10::vkCmdWriteTimestamp($commandBuffer, $pipelineStage instanceof \BackedEnum ? $pipelineStage->value : $pipelineStage, $queryPool, $query);
    }

    public static function vkCmdCopyQueryPoolResults(int $commandBuffer, int $queryPool, int $firstQuery, int $queryCount, int $dstBuffer, int $dstOffset, int $stride, int $flags): void
    {
        ExtVK10::vkCmdCopyQueryPoolResults($commandBuffer, $queryPool, $firstQuery, $queryCount, $dstBuffer, $dstOffset, $stride, $flags);
    }

    public static function vkCmdExecuteCommands(int $commandBuffer, int $commandBufferCount, int $pCommandBuffers): void
    {
        ExtVK10::vkCmdExecuteCommands($commandBuffer, $commandBufferCount, $pCommandBuffers);
    }

    public static function vkCreateEvent(int $device, int $pCreateInfo, int $pAllocator, int $pEvent): VkResult|int
    {
        return ExtVK10::vkCreateEvent($device, $pCreateInfo, $pAllocator, $pEvent);
    }

    public static function vkDestroyEvent(int $device, int $event, int $pAllocator): void
    {
        ExtVK10::vkDestroyEvent($device, $event, $pAllocator);
    }

    public static function vkGetEventStatus(int $device, int $event): VkResult|int
    {
        return ExtVK10::vkGetEventStatus($device, $event);
    }

    public static function vkSetEvent(int $device, int $event): VkResult|int
    {
        return ExtVK10::vkSetEvent($device, $event);
    }

    public static function vkResetEvent(int $device, int $event): VkResult|int
    {
        return ExtVK10::vkResetEvent($device, $event);
    }

    public static function vkCreateBufferView(int $device, int $pCreateInfo, int $pAllocator, int $pView): VkResult|int
    {
        return ExtVK10::vkCreateBufferView($device, $pCreateInfo, $pAllocator, $pView);
    }

    public static function vkDestroyBufferView(int $device, int $bufferView, int $pAllocator): void
    {
        ExtVK10::vkDestroyBufferView($device, $bufferView, $pAllocator);
    }

    public static function vkCreateShaderModule(int $device, int $pCreateInfo, int $pAllocator, int $pShaderModule): VkResult|int
    {
        return ExtVK10::vkCreateShaderModule($device, $pCreateInfo, $pAllocator, $pShaderModule);
    }

    public static function vkDestroyShaderModule(int $device, int $shaderModule, int $pAllocator): void
    {
        ExtVK10::vkDestroyShaderModule($device, $shaderModule, $pAllocator);
    }

    public static function vkCreatePipelineCache(int $device, int $pCreateInfo, int $pAllocator, int $pPipelineCache): VkResult|int
    {
        return ExtVK10::vkCreatePipelineCache($device, $pCreateInfo, $pAllocator, $pPipelineCache);
    }

    public static function vkDestroyPipelineCache(int $device, int $pipelineCache, int $pAllocator): void
    {
        ExtVK10::vkDestroyPipelineCache($device, $pipelineCache, $pAllocator);
    }

    public static function vkGetPipelineCacheData(int $device, int $pipelineCache, int $pDataSize, int $pData): VkResult|int
    {
        return ExtVK10::vkGetPipelineCacheData($device, $pipelineCache, $pDataSize, $pData);
    }

    public static function vkMergePipelineCaches(int $device, int $dstCache, int $srcCacheCount, int $pSrcCaches): VkResult|int
    {
        return ExtVK10::vkMergePipelineCaches($device, $dstCache, $srcCacheCount, $pSrcCaches);
    }

    public static function vkCreateComputePipelines(int $device, int $pipelineCache, int $createInfoCount, int $pCreateInfos, int $pAllocator, int $pPipelines): VkResult|int
    {
        return ExtVK10::vkCreateComputePipelines($device, $pipelineCache, $createInfoCount, $pCreateInfos, $pAllocator, $pPipelines);
    }

    public static function vkDestroyPipeline(int $device, int $pipeline, int $pAllocator): void
    {
        ExtVK10::vkDestroyPipeline($device, $pipeline, $pAllocator);
    }

    public static function vkCreatePipelineLayout(int $device, int $pCreateInfo, int $pAllocator, int $pPipelineLayout): VkResult|int
    {
        return ExtVK10::vkCreatePipelineLayout($device, $pCreateInfo, $pAllocator, $pPipelineLayout);
    }

    public static function vkDestroyPipelineLayout(int $device, int $pipelineLayout, int $pAllocator): void
    {
        ExtVK10::vkDestroyPipelineLayout($device, $pipelineLayout, $pAllocator);
    }

    public static function vkCreateSampler(int $device, int $pCreateInfo, int $pAllocator, int $pSampler): VkResult|int
    {
        return ExtVK10::vkCreateSampler($device, $pCreateInfo, $pAllocator, $pSampler);
    }

    public static function vkDestroySampler(int $device, int $sampler, int $pAllocator): void
    {
        ExtVK10::vkDestroySampler($device, $sampler, $pAllocator);
    }

    public static function vkCreateDescriptorSetLayout(int $device, int $pCreateInfo, int $pAllocator, int $pSetLayout): VkResult|int
    {
        return ExtVK10::vkCreateDescriptorSetLayout($device, $pCreateInfo, $pAllocator, $pSetLayout);
    }

    public static function vkDestroyDescriptorSetLayout(int $device, int $descriptorSetLayout, int $pAllocator): void
    {
        ExtVK10::vkDestroyDescriptorSetLayout($device, $descriptorSetLayout, $pAllocator);
    }

    public static function vkCreateDescriptorPool(int $device, int $pCreateInfo, int $pAllocator, int $pDescriptorPool): VkResult|int
    {
        return ExtVK10::vkCreateDescriptorPool($device, $pCreateInfo, $pAllocator, $pDescriptorPool);
    }

    public static function vkDestroyDescriptorPool(int $device, int $descriptorPool, int $pAllocator): void
    {
        ExtVK10::vkDestroyDescriptorPool($device, $descriptorPool, $pAllocator);
    }

    public static function vkResetDescriptorPool(int $device, int $descriptorPool, int $flags): VkResult|int
    {
        return ExtVK10::vkResetDescriptorPool($device, $descriptorPool, $flags);
    }

    public static function vkAllocateDescriptorSets(int $device, int $pAllocateInfo, int $pDescriptorSets): VkResult|int
    {
        return ExtVK10::vkAllocateDescriptorSets($device, $pAllocateInfo, $pDescriptorSets);
    }

    public static function vkFreeDescriptorSets(int $device, int $descriptorPool, int $descriptorSetCount, int $pDescriptorSets): VkResult|int
    {
        return ExtVK10::vkFreeDescriptorSets($device, $descriptorPool, $descriptorSetCount, $pDescriptorSets);
    }

    public static function vkUpdateDescriptorSets(int $device, int $descriptorWriteCount, int $pDescriptorWrites, int $descriptorCopyCount, int $pDescriptorCopies): void
    {
        ExtVK10::vkUpdateDescriptorSets($device, $descriptorWriteCount, $pDescriptorWrites, $descriptorCopyCount, $pDescriptorCopies);
    }

    public static function vkCmdBindPipeline(int $commandBuffer, VkPipelineBindPoint|int $pipelineBindPoint, int $pipeline): void
    {
        ExtVK10::vkCmdBindPipeline($commandBuffer, $pipelineBindPoint instanceof \BackedEnum ? $pipelineBindPoint->value : $pipelineBindPoint, $pipeline);
    }

    public static function vkCmdBindDescriptorSets(int $commandBuffer, VkPipelineBindPoint|int $pipelineBindPoint, int $layout, int $firstSet, int $descriptorSetCount, int $pDescriptorSets, int $dynamicOffsetCount, int $pDynamicOffsets): void
    {
        ExtVK10::vkCmdBindDescriptorSets($commandBuffer, $pipelineBindPoint instanceof \BackedEnum ? $pipelineBindPoint->value : $pipelineBindPoint, $layout, $firstSet, $descriptorSetCount, $pDescriptorSets, $dynamicOffsetCount, $pDynamicOffsets);
    }

    public static function vkCmdClearColorImage(int $commandBuffer, int $image, VkImageLayout|int $imageLayout, int $pColor, int $rangeCount, int $pRanges): void
    {
        ExtVK10::vkCmdClearColorImage($commandBuffer, $image, $imageLayout instanceof \BackedEnum ? $imageLayout->value : $imageLayout, $pColor, $rangeCount, $pRanges);
    }

    public static function vkCmdDispatch(int $commandBuffer, int $groupCountX, int $groupCountY, int $groupCountZ): void
    {
        ExtVK10::vkCmdDispatch($commandBuffer, $groupCountX, $groupCountY, $groupCountZ);
    }

    public static function vkCmdDispatchIndirect(int $commandBuffer, int $buffer, int $offset): void
    {
        ExtVK10::vkCmdDispatchIndirect($commandBuffer, $buffer, $offset);
    }

    public static function vkCmdSetEvent(int $commandBuffer, int $event, int $stageMask): void
    {
        ExtVK10::vkCmdSetEvent($commandBuffer, $event, $stageMask);
    }

    public static function vkCmdResetEvent(int $commandBuffer, int $event, int $stageMask): void
    {
        ExtVK10::vkCmdResetEvent($commandBuffer, $event, $stageMask);
    }

    public static function vkCmdWaitEvents(int $commandBuffer, int $eventCount, int $pEvents, int $srcStageMask, int $dstStageMask, int $memoryBarrierCount, int $pMemoryBarriers, int $bufferMemoryBarrierCount, int $pBufferMemoryBarriers, int $imageMemoryBarrierCount, int $pImageMemoryBarriers): void
    {
        ExtVK10::vkCmdWaitEvents($commandBuffer, $eventCount, $pEvents, $srcStageMask, $dstStageMask, $memoryBarrierCount, $pMemoryBarriers, $bufferMemoryBarrierCount, $pBufferMemoryBarriers, $imageMemoryBarrierCount, $pImageMemoryBarriers);
    }

    public static function vkCmdPushConstants(int $commandBuffer, int $layout, int $stageFlags, int $offset, int $size, int $pValues): void
    {
        ExtVK10::vkCmdPushConstants($commandBuffer, $layout, $stageFlags, $offset, $size, $pValues);
    }

    public static function vkCreateGraphicsPipelines(int $device, int $pipelineCache, int $createInfoCount, int $pCreateInfos, int $pAllocator, int $pPipelines): VkResult|int
    {
        return ExtVK10::vkCreateGraphicsPipelines($device, $pipelineCache, $createInfoCount, $pCreateInfos, $pAllocator, $pPipelines);
    }

    public static function vkCreateFramebuffer(int $device, int $pCreateInfo, int $pAllocator, int $pFramebuffer): VkResult|int
    {
        return ExtVK10::vkCreateFramebuffer($device, $pCreateInfo, $pAllocator, $pFramebuffer);
    }

    public static function vkDestroyFramebuffer(int $device, int $framebuffer, int $pAllocator): void
    {
        ExtVK10::vkDestroyFramebuffer($device, $framebuffer, $pAllocator);
    }

    public static function vkCreateRenderPass(int $device, int $pCreateInfo, int $pAllocator, int $pRenderPass): VkResult|int
    {
        return ExtVK10::vkCreateRenderPass($device, $pCreateInfo, $pAllocator, $pRenderPass);
    }

    public static function vkDestroyRenderPass(int $device, int $renderPass, int $pAllocator): void
    {
        ExtVK10::vkDestroyRenderPass($device, $renderPass, $pAllocator);
    }

    public static function vkGetRenderAreaGranularity(int $device, int $renderPass, int $pGranularity): void
    {
        ExtVK10::vkGetRenderAreaGranularity($device, $renderPass, $pGranularity);
    }

    public static function vkCmdSetViewport(int $commandBuffer, int $firstViewport, int $viewportCount, int $pViewports): void
    {
        ExtVK10::vkCmdSetViewport($commandBuffer, $firstViewport, $viewportCount, $pViewports);
    }

    public static function vkCmdSetScissor(int $commandBuffer, int $firstScissor, int $scissorCount, int $pScissors): void
    {
        ExtVK10::vkCmdSetScissor($commandBuffer, $firstScissor, $scissorCount, $pScissors);
    }

    public static function vkCmdSetLineWidth(int $commandBuffer, float $lineWidth): void
    {
        ExtVK10::vkCmdSetLineWidth($commandBuffer, $lineWidth);
    }

    public static function vkCmdSetDepthBias(int $commandBuffer, float $depthBiasConstantFactor, float $depthBiasClamp, float $depthBiasSlopeFactor): void
    {
        ExtVK10::vkCmdSetDepthBias($commandBuffer, $depthBiasConstantFactor, $depthBiasClamp, $depthBiasSlopeFactor);
    }

    public static function vkCmdSetBlendConstants(int $commandBuffer, int $blendConstants): void
    {
        ExtVK10::vkCmdSetBlendConstants($commandBuffer, $blendConstants);
    }

    public static function vkCmdSetDepthBounds(int $commandBuffer, float $minDepthBounds, float $maxDepthBounds): void
    {
        ExtVK10::vkCmdSetDepthBounds($commandBuffer, $minDepthBounds, $maxDepthBounds);
    }

    public static function vkCmdSetStencilCompareMask(int $commandBuffer, int $faceMask, int $compareMask): void
    {
        ExtVK10::vkCmdSetStencilCompareMask($commandBuffer, $faceMask, $compareMask);
    }

    public static function vkCmdSetStencilWriteMask(int $commandBuffer, int $faceMask, int $writeMask): void
    {
        ExtVK10::vkCmdSetStencilWriteMask($commandBuffer, $faceMask, $writeMask);
    }

    public static function vkCmdSetStencilReference(int $commandBuffer, int $faceMask, int $reference): void
    {
        ExtVK10::vkCmdSetStencilReference($commandBuffer, $faceMask, $reference);
    }

    public static function vkCmdBindIndexBuffer(int $commandBuffer, int $buffer, int $offset, VkIndexType|int $indexType): void
    {
        ExtVK10::vkCmdBindIndexBuffer($commandBuffer, $buffer, $offset, $indexType instanceof \BackedEnum ? $indexType->value : $indexType);
    }

    public static function vkCmdBindVertexBuffers(int $commandBuffer, int $firstBinding, int $bindingCount, int $pBuffers, int $pOffsets): void
    {
        ExtVK10::vkCmdBindVertexBuffers($commandBuffer, $firstBinding, $bindingCount, $pBuffers, $pOffsets);
    }

    public static function vkCmdDraw(int $commandBuffer, int $vertexCount, int $instanceCount, int $firstVertex, int $firstInstance): void
    {
        ExtVK10::vkCmdDraw($commandBuffer, $vertexCount, $instanceCount, $firstVertex, $firstInstance);
    }

    public static function vkCmdDrawIndexed(int $commandBuffer, int $indexCount, int $instanceCount, int $firstIndex, int $vertexOffset, int $firstInstance): void
    {
        ExtVK10::vkCmdDrawIndexed($commandBuffer, $indexCount, $instanceCount, $firstIndex, $vertexOffset, $firstInstance);
    }

    public static function vkCmdDrawIndirect(int $commandBuffer, int $buffer, int $offset, int $drawCount, int $stride): void
    {
        ExtVK10::vkCmdDrawIndirect($commandBuffer, $buffer, $offset, $drawCount, $stride);
    }

    public static function vkCmdDrawIndexedIndirect(int $commandBuffer, int $buffer, int $offset, int $drawCount, int $stride): void
    {
        ExtVK10::vkCmdDrawIndexedIndirect($commandBuffer, $buffer, $offset, $drawCount, $stride);
    }

    public static function vkCmdBlitImage(int $commandBuffer, int $srcImage, VkImageLayout|int $srcImageLayout, int $dstImage, VkImageLayout|int $dstImageLayout, int $regionCount, int $pRegions, VkFilter|int $filter): void
    {
        ExtVK10::vkCmdBlitImage($commandBuffer, $srcImage, $srcImageLayout instanceof \BackedEnum ? $srcImageLayout->value : $srcImageLayout, $dstImage, $dstImageLayout instanceof \BackedEnum ? $dstImageLayout->value : $dstImageLayout, $regionCount, $pRegions, $filter instanceof \BackedEnum ? $filter->value : $filter);
    }

    public static function vkCmdClearDepthStencilImage(int $commandBuffer, int $image, VkImageLayout|int $imageLayout, int $pDepthStencil, int $rangeCount, int $pRanges): void
    {
        ExtVK10::vkCmdClearDepthStencilImage($commandBuffer, $image, $imageLayout instanceof \BackedEnum ? $imageLayout->value : $imageLayout, $pDepthStencil, $rangeCount, $pRanges);
    }

    public static function vkCmdClearAttachments(int $commandBuffer, int $attachmentCount, int $pAttachments, int $rectCount, int $pRects): void
    {
        ExtVK10::vkCmdClearAttachments($commandBuffer, $attachmentCount, $pAttachments, $rectCount, $pRects);
    }

    public static function vkCmdResolveImage(int $commandBuffer, int $srcImage, VkImageLayout|int $srcImageLayout, int $dstImage, VkImageLayout|int $dstImageLayout, int $regionCount, int $pRegions): void
    {
        ExtVK10::vkCmdResolveImage($commandBuffer, $srcImage, $srcImageLayout instanceof \BackedEnum ? $srcImageLayout->value : $srcImageLayout, $dstImage, $dstImageLayout instanceof \BackedEnum ? $dstImageLayout->value : $dstImageLayout, $regionCount, $pRegions);
    }

    public static function vkCmdBeginRenderPass(int $commandBuffer, int $pRenderPassBegin, VkSubpassContents|int $contents): void
    {
        ExtVK10::vkCmdBeginRenderPass($commandBuffer, $pRenderPassBegin, $contents instanceof \BackedEnum ? $contents->value : $contents);
    }

    public static function vkCmdNextSubpass(int $commandBuffer, VkSubpassContents|int $contents): void
    {
        ExtVK10::vkCmdNextSubpass($commandBuffer, $contents instanceof \BackedEnum ? $contents->value : $contents);
    }

    public static function vkCmdEndRenderPass(int $commandBuffer): void
    {
        ExtVK10::vkCmdEndRenderPass($commandBuffer);
    }
}
