<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Ext;

use Jovian\Bindings\Vulkan\Enums\VkDebugUtilsMessageSeverityFlagBitsEXT;
use Jovian\Bindings\Vulkan\Enums\VkResult;
use Vulkan\Ext\EXTDebugUtils\EXTDebugUtils as ExtEXTDebugUtils;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
final class EXTDebugUtils
{
    public static function vkSetDebugUtilsObjectNameEXT(int $device, int $pNameInfo): VkResult|int
    {
        return ExtEXTDebugUtils::vkSetDebugUtilsObjectNameEXT($device, $pNameInfo);
    }

    public static function vkSetDebugUtilsObjectTagEXT(int $device, int $pTagInfo): VkResult|int
    {
        return ExtEXTDebugUtils::vkSetDebugUtilsObjectTagEXT($device, $pTagInfo);
    }

    public static function vkQueueBeginDebugUtilsLabelEXT(int $queue, int $pLabelInfo): void
    {
        ExtEXTDebugUtils::vkQueueBeginDebugUtilsLabelEXT($queue, $pLabelInfo);
    }

    public static function vkQueueEndDebugUtilsLabelEXT(int $queue): void
    {
        ExtEXTDebugUtils::vkQueueEndDebugUtilsLabelEXT($queue);
    }

    public static function vkQueueInsertDebugUtilsLabelEXT(int $queue, int $pLabelInfo): void
    {
        ExtEXTDebugUtils::vkQueueInsertDebugUtilsLabelEXT($queue, $pLabelInfo);
    }

    public static function vkCmdBeginDebugUtilsLabelEXT(int $commandBuffer, int $pLabelInfo): void
    {
        ExtEXTDebugUtils::vkCmdBeginDebugUtilsLabelEXT($commandBuffer, $pLabelInfo);
    }

    public static function vkCmdEndDebugUtilsLabelEXT(int $commandBuffer): void
    {
        ExtEXTDebugUtils::vkCmdEndDebugUtilsLabelEXT($commandBuffer);
    }

    public static function vkCmdInsertDebugUtilsLabelEXT(int $commandBuffer, int $pLabelInfo): void
    {
        ExtEXTDebugUtils::vkCmdInsertDebugUtilsLabelEXT($commandBuffer, $pLabelInfo);
    }

    public static function vkCreateDebugUtilsMessengerEXT(int $instance, int $pCreateInfo, int $pAllocator, int $pMessenger): VkResult|int
    {
        return ExtEXTDebugUtils::vkCreateDebugUtilsMessengerEXT($instance, $pCreateInfo, $pAllocator, $pMessenger);
    }

    public static function vkDestroyDebugUtilsMessengerEXT(int $instance, int $messenger, int $pAllocator): void
    {
        ExtEXTDebugUtils::vkDestroyDebugUtilsMessengerEXT($instance, $messenger, $pAllocator);
    }

    public static function vkSubmitDebugUtilsMessageEXT(int $instance, VkDebugUtilsMessageSeverityFlagBitsEXT|int $messageSeverity, int $messageTypes, int $pCallbackData): void
    {
        ExtEXTDebugUtils::vkSubmitDebugUtilsMessageEXT($instance, $messageSeverity instanceof \BackedEnum ? $messageSeverity->value : $messageSeverity, $messageTypes, $pCallbackData);
    }
}
