<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Ext;

use Jovian\Bindings\Vulkan\Enums\VkResult;
use Vulkan\Ext\EXTMetalSurface\EXTMetalSurface as ExtEXTMetalSurface;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
final class EXTMetalSurface
{
    public static function vkCreateMetalSurfaceEXT(int $instance, int $pCreateInfo, int $pAllocator, int $pSurface): VkResult|int
    {
        return ExtEXTMetalSurface::vkCreateMetalSurfaceEXT($instance, $pCreateInfo, $pAllocator, $pSurface);
    }
}
