<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Ext;

use Jovian\Bindings\Vulkan\Enums\VkResult;
use Vulkan\Ext\KHRSwapchain\KHRSwapchain as ExtKHRSwapchain;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
final class KHRSwapchain
{
    public static function vkCreateSwapchainKHR(int $device, int $pCreateInfo, int $pAllocator, int $pSwapchain): VkResult|int
    {
        return ExtKHRSwapchain::vkCreateSwapchainKHR($device, $pCreateInfo, $pAllocator, $pSwapchain);
    }

    public static function vkDestroySwapchainKHR(int $device, int $swapchain, int $pAllocator): void
    {
        ExtKHRSwapchain::vkDestroySwapchainKHR($device, $swapchain, $pAllocator);
    }

    public static function vkGetSwapchainImagesKHR(int $device, int $swapchain, int $pSwapchainImageCount, int $pSwapchainImages): VkResult|int
    {
        return ExtKHRSwapchain::vkGetSwapchainImagesKHR($device, $swapchain, $pSwapchainImageCount, $pSwapchainImages);
    }

    public static function vkAcquireNextImageKHR(int $device, int $swapchain, int $timeout, int $semaphore, int $fence, int $pImageIndex): VkResult|int
    {
        return ExtKHRSwapchain::vkAcquireNextImageKHR($device, $swapchain, $timeout, $semaphore, $fence, $pImageIndex);
    }

    public static function vkQueuePresentKHR(int $queue, int $pPresentInfo): VkResult|int
    {
        return ExtKHRSwapchain::vkQueuePresentKHR($queue, $pPresentInfo);
    }

    public static function vkGetDeviceGroupPresentCapabilitiesKHR(int $device, int $pDeviceGroupPresentCapabilities): VkResult|int
    {
        return ExtKHRSwapchain::vkGetDeviceGroupPresentCapabilitiesKHR($device, $pDeviceGroupPresentCapabilities);
    }

    public static function vkGetDeviceGroupSurfacePresentModesKHR(int $device, int $surface, int $pModes): VkResult|int
    {
        return ExtKHRSwapchain::vkGetDeviceGroupSurfacePresentModesKHR($device, $surface, $pModes);
    }

    public static function vkGetPhysicalDevicePresentRectanglesKHR(int $physicalDevice, int $surface, int $pRectCount, int $pRects): VkResult|int
    {
        return ExtKHRSwapchain::vkGetPhysicalDevicePresentRectanglesKHR($physicalDevice, $surface, $pRectCount, $pRects);
    }

    public static function vkAcquireNextImage2KHR(int $device, int $pAcquireInfo, int $pImageIndex): VkResult|int
    {
        return ExtKHRSwapchain::vkAcquireNextImage2KHR($device, $pAcquireInfo, $pImageIndex);
    }
}
