<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Ext;

use Jovian\Bindings\Vulkan\Enums\VkResult;
use Vulkan\Ext\KHRSurface\KHRSurface as ExtKHRSurface;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
final class KHRSurface
{
    public static function vkDestroySurfaceKHR(int $instance, int $surface, int $pAllocator): void
    {
        ExtKHRSurface::vkDestroySurfaceKHR($instance, $surface, $pAllocator);
    }

    public static function vkGetPhysicalDeviceSurfaceSupportKHR(int $physicalDevice, int $queueFamilyIndex, int $surface, int $pSupported): VkResult|int
    {
        return ExtKHRSurface::vkGetPhysicalDeviceSurfaceSupportKHR($physicalDevice, $queueFamilyIndex, $surface, $pSupported);
    }

    public static function vkGetPhysicalDeviceSurfaceCapabilitiesKHR(int $physicalDevice, int $surface, int $pSurfaceCapabilities): VkResult|int
    {
        return ExtKHRSurface::vkGetPhysicalDeviceSurfaceCapabilitiesKHR($physicalDevice, $surface, $pSurfaceCapabilities);
    }

    public static function vkGetPhysicalDeviceSurfaceFormatsKHR(int $physicalDevice, int $surface, int $pSurfaceFormatCount, int $pSurfaceFormats): VkResult|int
    {
        return ExtKHRSurface::vkGetPhysicalDeviceSurfaceFormatsKHR($physicalDevice, $surface, $pSurfaceFormatCount, $pSurfaceFormats);
    }

    public static function vkGetPhysicalDeviceSurfacePresentModesKHR(int $physicalDevice, int $surface, int $pPresentModeCount, int $pPresentModes): VkResult|int
    {
        return ExtKHRSurface::vkGetPhysicalDeviceSurfacePresentModesKHR($physicalDevice, $surface, $pPresentModeCount, $pPresentModes);
    }
}
