<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Ext;

use Jovian\Bindings\Vulkan\Enums\VkResult;
use Vulkan\Ext\KHRXcbSurface\KHRXcbSurface as ExtKHRXcbSurface;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 */
final class KHRXcbSurface
{
    public static function vkCreateXcbSurfaceKHR(int $instance, int $pCreateInfo, int $pAllocator, int $pSurface): VkResult|int
    {
        return ExtKHRXcbSurface::vkCreateXcbSurfaceKHR($instance, $pCreateInfo, $pAllocator, $pSurface);
    }

    public static function vkGetPhysicalDeviceXcbPresentationSupportKHR(int $physicalDevice, int $queueFamilyIndex, int $connection, int $visual_id): bool
    {
        return ExtKHRXcbSurface::vkGetPhysicalDeviceXcbPresentationSupportKHR($physicalDevice, $queueFamilyIndex, $connection, $visual_id);
    }
}
