<?php

declare(strict_types=1);

/*
| The projection rule, enforced on the emitted tree: one PHP method is exactly
| one extension call, same arguments, same order — and the two conversions this
| layer adds are exactly ZERO calls, because a constructor and its inverse
| fetch nothing. Both halves matter: a toArray() that reached for the extension
| would be composition wearing a value object's clothes.
*/

/** @return list<string> */
function vulkanProjectionFiles(): array
{
    $root = dirname(__DIR__, 2) . '/src';
    $files = [];
    foreach (['VK', 'Ext', 'Structs'] as $directory) {
        foreach (glob($root . '/' . $directory . '/*.php') ?: [] as $file) {
            $files[] = $file;
        }
    }
    sort($files);

    return $files;
}

/**
 * The alias the file imported the extension class under. Counting `Ext\w+::`
 * instead would count `VkExtent3D::fromArray()` as an extension call, because
 * "Extent" begins with "Ext".
 */
function vulkanExtAlias(string $source): ?string
{
    return preg_match('/^use\s+Vulkan\\\\[^\s;]+\s+as\s+(\w+);$/m', $source, $m) === 1 ? $m[1] : null;
}

it('makes exactly one extension call per bound method, and none per conversion', function (): void {
    $bound = 0;
    $conversions = 0;

    foreach (vulkanProjectionFiles() as $file) {
        $source = (string) file_get_contents($file);
        $alias = vulkanExtAlias($source);
        expect($alias)->not->toBeNull(basename($file) . ' imports no extension class');

        preg_match_all(
            '/public (?:static )?function (\w+)\s*\([^)]*\):[^\n{]+\n    \{\n(.*?)\n    \}/s',
            $source,
            $matches,
            PREG_SET_ORDER,
        );
        expect($matches)->not->toBeEmpty(basename($file) . ' has no methods');

        foreach ($matches as $match) {
            $calls = preg_match_all('/\b' . preg_quote((string) $alias, '/') . '::/', $match[2]);
            if (in_array($match[1], ['toArray', 'fromArray'], true)) {
                $conversions++;
                expect($calls)->toBe(0, basename($file) . '::' . $match[1] . ' makes ' . $calls . ' extension calls');
                continue;
            }
            $bound++;
            expect($calls)->toBe(1, basename($file) . '::' . $match[1] . ' makes ' . $calls . ' extension calls');
        }
    }

    // 267 commands + 368 structs x 4 methods.
    expect($bound)->toBe(1739);
    expect($conversions)->toBe(736);
});

it('runs the generator in --check mode and joins everything', function (): void {
    $root = dirname(__DIR__, 2);
    $command = escapeshellarg(PHP_BINARY) . ' ' . escapeshellarg($root . '/scripts/generate.php')
        . ' --check --ext ' . escapeshellarg(vulkanExtRoot()) . ' 2>&1';
    $output = (string) shell_exec($command);

    expect($output)->toContain('GEN_OK');
    expect($output)->not->toContain('unmatched annotation');
    expect($output)->toContain('commands=267');
    expect($output)->toContain('structs=368');
    expect($output)->toContain('members=2296');
    expect($output)->toContain('struct_methods=1472');
    expect($output)->toContain('bridge=12');
    expect($output)->toContain('reserved=0');
});

it('keeps every generated file under the GENERATED banner', function (): void {
    $root = dirname(__DIR__, 2) . '/src';
    $generated = 0;
    foreach (['VK', 'Ext', 'Structs', 'Enums'] as $directory) {
        foreach (glob($root . '/' . $directory . '/*.php') ?: [] as $file) {
            $generated++;
            expect(str_contains((string) file_get_contents($file), 'GENERATED by scripts/generate.php'))
                ->toBeTrue(basename($file) . ' carries no GENERATED banner');
        }
    }

    // 13 command classes + 368 structs + 114 enums.
    expect($generated)->toBe(495);

    // And the hand-written half is exactly two files, by rule.
    $handWritten = array_merge(
        glob($root . '/Runtime/*.php') ?: [],
        glob($root . '/Values/*.php') ?: [],
    );
    expect(array_map('basename', $handWritten))->toBe(['Bridge.php', 'ApiVersion.php']);
    foreach ($handWritten as $file) {
        expect((string) file_get_contents($file))->not->toContain('GENERATED by scripts/generate.php');
    }
});
