<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkAllocationCallbacks\VkAllocationCallbacks as ExtVkAllocationCallbacks;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkAllocationCallbacks">, 6 members.
 *
 * The typed shape of the array ExtVkAllocationCallbacks::pack() takes and
 * ExtVkAllocationCallbacks::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkAllocationCallbacks
{
    public function __construct(
        public int $pUserData = 0,
        public int $pfnAllocation = 0,
        public int $pfnReallocation = 0,
        public int $pfnFree = 0,
        public int $pfnInternalAllocation = 0,
        public int $pfnInternalFree = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['pUserData'] = $this->pUserData;
        $members['pfnAllocation'] = $this->pfnAllocation;
        $members['pfnReallocation'] = $this->pfnReallocation;
        $members['pfnFree'] = $this->pfnFree;
        $members['pfnInternalAllocation'] = $this->pfnInternalAllocation;
        $members['pfnInternalFree'] = $this->pfnInternalFree;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            pUserData: (int) ($members['pUserData'] ?? 0),
            pfnAllocation: (int) ($members['pfnAllocation'] ?? 0),
            pfnReallocation: (int) ($members['pfnReallocation'] ?? 0),
            pfnFree: (int) ($members['pfnFree'] ?? 0),
            pfnInternalAllocation: (int) ($members['pfnInternalAllocation'] ?? 0),
            pfnInternalFree: (int) ($members['pfnInternalFree'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkAllocationCallbacks::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkAllocationCallbacks::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkAllocationCallbacks::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkAllocationCallbacks::size();
    }
}
