<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkApplicationInfo\VkApplicationInfo as ExtVkApplicationInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkApplicationInfo">, 7 members.
 *
 * The typed shape of the array ExtVkApplicationInfo::pack() takes and
 * ExtVkApplicationInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkApplicationInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::APPLICATION_INFO,
        public int $pNext = 0,
        public int $pApplicationName = 0,
        public int $applicationVersion = 0,
        public int $pEngineName = 0,
        public int $engineVersion = 0,
        public int $apiVersion = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['pApplicationName'] = $this->pApplicationName;
        $members['applicationVersion'] = $this->applicationVersion;
        $members['pEngineName'] = $this->pEngineName;
        $members['engineVersion'] = $this->engineVersion;
        $members['apiVersion'] = $this->apiVersion;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            pApplicationName: (int) ($members['pApplicationName'] ?? 0),
            applicationVersion: (int) ($members['applicationVersion'] ?? 0),
            pEngineName: (int) ($members['pEngineName'] ?? 0),
            engineVersion: (int) ($members['engineVersion'] ?? 0),
            apiVersion: (int) ($members['apiVersion'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkApplicationInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkApplicationInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkApplicationInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkApplicationInfo::size();
    }
}
