<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkImageLayout;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkAttachmentReference2\VkAttachmentReference2 as ExtVkAttachmentReference2;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkAttachmentReference2">, 5 members.
 *
 * The typed shape of the array ExtVkAttachmentReference2::pack() takes and
 * ExtVkAttachmentReference2::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkAttachmentReference2
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::ATTACHMENT_REFERENCE_2,
        public int $pNext = 0,
        public int $attachment = 0,
        public VkImageLayout|int $layout = 0,
        public int $aspectMask = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['attachment'] = $this->attachment;
        $members['layout'] = $this->layout instanceof \BackedEnum ? $this->layout->value : $this->layout;
        $members['aspectMask'] = $this->aspectMask;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            attachment: (int) ($members['attachment'] ?? 0),
            layout: (int) ($members['layout'] ?? 0),
            aspectMask: (int) ($members['aspectMask'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkAttachmentReference2::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkAttachmentReference2::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkAttachmentReference2::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkAttachmentReference2::size();
    }
}
