<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkAttachmentLoadOp;
use Jovian\Bindings\Vulkan\Enums\VkAttachmentStoreOp;
use Jovian\Bindings\Vulkan\Enums\VkFormat;
use Jovian\Bindings\Vulkan\Enums\VkImageLayout;
use Jovian\Bindings\Vulkan\Enums\VkSampleCountFlagBits;
use Vulkan\Struct\VkAttachmentDescription\VkAttachmentDescription as ExtVkAttachmentDescription;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkAttachmentDescription">, 9 members.
 *
 * The typed shape of the array ExtVkAttachmentDescription::pack() takes and
 * ExtVkAttachmentDescription::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkAttachmentDescription
{
    public function __construct(
        public int $flags = 0,
        public VkFormat|int $format = 0,
        public VkSampleCountFlagBits|int $samples = 0,
        public VkAttachmentLoadOp|int $loadOp = 0,
        public VkAttachmentStoreOp|int $storeOp = 0,
        public VkAttachmentLoadOp|int $stencilLoadOp = 0,
        public VkAttachmentStoreOp|int $stencilStoreOp = 0,
        public VkImageLayout|int $initialLayout = 0,
        public VkImageLayout|int $finalLayout = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['flags'] = $this->flags;
        $members['format'] = $this->format instanceof \BackedEnum ? $this->format->value : $this->format;
        $members['samples'] = $this->samples instanceof \BackedEnum ? $this->samples->value : $this->samples;
        $members['loadOp'] = $this->loadOp instanceof \BackedEnum ? $this->loadOp->value : $this->loadOp;
        $members['storeOp'] = $this->storeOp instanceof \BackedEnum ? $this->storeOp->value : $this->storeOp;
        $members['stencilLoadOp'] = $this->stencilLoadOp instanceof \BackedEnum ? $this->stencilLoadOp->value : $this->stencilLoadOp;
        $members['stencilStoreOp'] = $this->stencilStoreOp instanceof \BackedEnum ? $this->stencilStoreOp->value : $this->stencilStoreOp;
        $members['initialLayout'] = $this->initialLayout instanceof \BackedEnum ? $this->initialLayout->value : $this->initialLayout;
        $members['finalLayout'] = $this->finalLayout instanceof \BackedEnum ? $this->finalLayout->value : $this->finalLayout;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            flags: (int) ($members['flags'] ?? 0),
            format: (int) ($members['format'] ?? 0),
            samples: (int) ($members['samples'] ?? 0),
            loadOp: (int) ($members['loadOp'] ?? 0),
            storeOp: (int) ($members['storeOp'] ?? 0),
            stencilLoadOp: (int) ($members['stencilLoadOp'] ?? 0),
            stencilStoreOp: (int) ($members['stencilStoreOp'] ?? 0),
            initialLayout: (int) ($members['initialLayout'] ?? 0),
            finalLayout: (int) ($members['finalLayout'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkAttachmentDescription::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkAttachmentDescription::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkAttachmentDescription::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkAttachmentDescription::size();
    }
}
