<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkBaseOutStructure\VkBaseOutStructure as ExtVkBaseOutStructure;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkBaseOutStructure">, 2 members.
 *
 * The typed shape of the array ExtVkBaseOutStructure::pack() takes and
 * ExtVkBaseOutStructure::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkBaseOutStructure
{
    public function __construct(
        public VkStructureType|int $sType = 0,
        public int $pNext = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkBaseOutStructure::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkBaseOutStructure::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkBaseOutStructure::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkBaseOutStructure::size();
    }
}
