<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkBindImageMemoryDeviceGroupInfo\VkBindImageMemoryDeviceGroupInfo as ExtVkBindImageMemoryDeviceGroupInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkBindImageMemoryDeviceGroupInfo">, 6 members.
 *
 * The typed shape of the array ExtVkBindImageMemoryDeviceGroupInfo::pack() takes and
 * ExtVkBindImageMemoryDeviceGroupInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkBindImageMemoryDeviceGroupInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO,
        public int $pNext = 0,
        public int $deviceIndexCount = 0,
        public int $pDeviceIndices = 0,
        public int $splitInstanceBindRegionCount = 0,
        public int $pSplitInstanceBindRegions = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['deviceIndexCount'] = $this->deviceIndexCount;
        $members['pDeviceIndices'] = $this->pDeviceIndices;
        $members['splitInstanceBindRegionCount'] = $this->splitInstanceBindRegionCount;
        $members['pSplitInstanceBindRegions'] = $this->pSplitInstanceBindRegions;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            deviceIndexCount: (int) ($members['deviceIndexCount'] ?? 0),
            pDeviceIndices: (int) ($members['pDeviceIndices'] ?? 0),
            splitInstanceBindRegionCount: (int) ($members['splitInstanceBindRegionCount'] ?? 0),
            pSplitInstanceBindRegions: (int) ($members['pSplitInstanceBindRegions'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkBindImageMemoryDeviceGroupInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkBindImageMemoryDeviceGroupInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkBindImageMemoryDeviceGroupInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkBindImageMemoryDeviceGroupInfo::size();
    }
}
