<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkBindImageMemoryInfo\VkBindImageMemoryInfo as ExtVkBindImageMemoryInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkBindImageMemoryInfo">, 5 members.
 *
 * The typed shape of the array ExtVkBindImageMemoryInfo::pack() takes and
 * ExtVkBindImageMemoryInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkBindImageMemoryInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::BIND_IMAGE_MEMORY_INFO,
        public int $pNext = 0,
        public int $image = 0,
        public int $memory = 0,
        public int $memoryOffset = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['image'] = $this->image;
        $members['memory'] = $this->memory;
        $members['memoryOffset'] = $this->memoryOffset;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            image: (int) ($members['image'] ?? 0),
            memory: (int) ($members['memory'] ?? 0),
            memoryOffset: (int) ($members['memoryOffset'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkBindImageMemoryInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkBindImageMemoryInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkBindImageMemoryInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkBindImageMemoryInfo::size();
    }
}
