<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkBindSparseInfo\VkBindSparseInfo as ExtVkBindSparseInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkBindSparseInfo">, 12 members.
 *
 * The typed shape of the array ExtVkBindSparseInfo::pack() takes and
 * ExtVkBindSparseInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkBindSparseInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::BIND_SPARSE_INFO,
        public int $pNext = 0,
        public int $waitSemaphoreCount = 0,
        public int $pWaitSemaphores = 0,
        public int $bufferBindCount = 0,
        public int $pBufferBinds = 0,
        public int $imageOpaqueBindCount = 0,
        public int $pImageOpaqueBinds = 0,
        public int $imageBindCount = 0,
        public int $pImageBinds = 0,
        public int $signalSemaphoreCount = 0,
        public int $pSignalSemaphores = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['waitSemaphoreCount'] = $this->waitSemaphoreCount;
        $members['pWaitSemaphores'] = $this->pWaitSemaphores;
        $members['bufferBindCount'] = $this->bufferBindCount;
        $members['pBufferBinds'] = $this->pBufferBinds;
        $members['imageOpaqueBindCount'] = $this->imageOpaqueBindCount;
        $members['pImageOpaqueBinds'] = $this->pImageOpaqueBinds;
        $members['imageBindCount'] = $this->imageBindCount;
        $members['pImageBinds'] = $this->pImageBinds;
        $members['signalSemaphoreCount'] = $this->signalSemaphoreCount;
        $members['pSignalSemaphores'] = $this->pSignalSemaphores;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            waitSemaphoreCount: (int) ($members['waitSemaphoreCount'] ?? 0),
            pWaitSemaphores: (int) ($members['pWaitSemaphores'] ?? 0),
            bufferBindCount: (int) ($members['bufferBindCount'] ?? 0),
            pBufferBinds: (int) ($members['pBufferBinds'] ?? 0),
            imageOpaqueBindCount: (int) ($members['imageOpaqueBindCount'] ?? 0),
            pImageOpaqueBinds: (int) ($members['pImageOpaqueBinds'] ?? 0),
            imageBindCount: (int) ($members['imageBindCount'] ?? 0),
            pImageBinds: (int) ($members['pImageBinds'] ?? 0),
            signalSemaphoreCount: (int) ($members['signalSemaphoreCount'] ?? 0),
            pSignalSemaphores: (int) ($members['pSignalSemaphores'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkBindSparseInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkBindSparseInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkBindSparseInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkBindSparseInfo::size();
    }
}
