<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkBindImageMemorySwapchainInfoKHR\VkBindImageMemorySwapchainInfoKHR as ExtVkBindImageMemorySwapchainInfoKHR;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkBindImageMemorySwapchainInfoKHR">, 4 members.
 *
 * The typed shape of the array ExtVkBindImageMemorySwapchainInfoKHR::pack() takes and
 * ExtVkBindImageMemorySwapchainInfoKHR::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkBindImageMemorySwapchainInfoKHR
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::BIND_IMAGE_MEMORY_SWAPCHAIN_INFO_KHR,
        public int $pNext = 0,
        public int $swapchain = 0,
        public int $imageIndex = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['swapchain'] = $this->swapchain;
        $members['imageIndex'] = $this->imageIndex;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            swapchain: (int) ($members['swapchain'] ?? 0),
            imageIndex: (int) ($members['imageIndex'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkBindImageMemorySwapchainInfoKHR::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkBindImageMemorySwapchainInfoKHR::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkBindImageMemorySwapchainInfoKHR::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkBindImageMemorySwapchainInfoKHR::size();
    }
}
