<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkBufferImageCopy2\VkBufferImageCopy2 as ExtVkBufferImageCopy2;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkBufferImageCopy2">, 8 members.
 *
 * The typed shape of the array ExtVkBufferImageCopy2::pack() takes and
 * ExtVkBufferImageCopy2::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkBufferImageCopy2
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::BUFFER_IMAGE_COPY_2,
        public int $pNext = 0,
        public int $bufferOffset = 0,
        public int $bufferRowLength = 0,
        public int $bufferImageHeight = 0,
        public ?VkImageSubresourceLayers $imageSubresource = null,
        public ?VkOffset3D $imageOffset = null,
        public ?VkExtent3D $imageExtent = null,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['bufferOffset'] = $this->bufferOffset;
        $members['bufferRowLength'] = $this->bufferRowLength;
        $members['bufferImageHeight'] = $this->bufferImageHeight;
        if (! is_null($this->imageSubresource)) {
            $members['imageSubresource'] = $this->imageSubresource->toArray();
        }
        if (! is_null($this->imageOffset)) {
            $members['imageOffset'] = $this->imageOffset->toArray();
        }
        if (! is_null($this->imageExtent)) {
            $members['imageExtent'] = $this->imageExtent->toArray();
        }

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            bufferOffset: (int) ($members['bufferOffset'] ?? 0),
            bufferRowLength: (int) ($members['bufferRowLength'] ?? 0),
            bufferImageHeight: (int) ($members['bufferImageHeight'] ?? 0),
            imageSubresource: is_array($members['imageSubresource'] ?? null) ? VkImageSubresourceLayers::fromArray($members['imageSubresource']) : null,
            imageOffset: is_array($members['imageOffset'] ?? null) ? VkOffset3D::fromArray($members['imageOffset']) : null,
            imageExtent: is_array($members['imageExtent'] ?? null) ? VkExtent3D::fromArray($members['imageExtent']) : null,
        );
    }

    public function pack(): int
    {
        return ExtVkBufferImageCopy2::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkBufferImageCopy2::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkBufferImageCopy2::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkBufferImageCopy2::size();
    }
}
