<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkSharingMode;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkBufferCreateInfo\VkBufferCreateInfo as ExtVkBufferCreateInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkBufferCreateInfo">, 8 members.
 *
 * The typed shape of the array ExtVkBufferCreateInfo::pack() takes and
 * ExtVkBufferCreateInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkBufferCreateInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::BUFFER_CREATE_INFO,
        public int $pNext = 0,
        public int $flags = 0,
        public int $size = 0,
        public int $usage = 0,
        public VkSharingMode|int $sharingMode = 0,
        public int $queueFamilyIndexCount = 0,
        public int $pQueueFamilyIndices = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        $members['size'] = $this->size;
        $members['usage'] = $this->usage;
        $members['sharingMode'] = $this->sharingMode instanceof \BackedEnum ? $this->sharingMode->value : $this->sharingMode;
        $members['queueFamilyIndexCount'] = $this->queueFamilyIndexCount;
        $members['pQueueFamilyIndices'] = $this->pQueueFamilyIndices;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            size: (int) ($members['size'] ?? 0),
            usage: (int) ($members['usage'] ?? 0),
            sharingMode: (int) ($members['sharingMode'] ?? 0),
            queueFamilyIndexCount: (int) ($members['queueFamilyIndexCount'] ?? 0),
            pQueueFamilyIndices: (int) ($members['pQueueFamilyIndices'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkBufferCreateInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkBufferCreateInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkBufferCreateInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkBufferCreateInfo::size();
    }
}
