<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkBufferCopy2\VkBufferCopy2 as ExtVkBufferCopy2;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkBufferCopy2">, 5 members.
 *
 * The typed shape of the array ExtVkBufferCopy2::pack() takes and
 * ExtVkBufferCopy2::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkBufferCopy2
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::BUFFER_COPY_2,
        public int $pNext = 0,
        public int $srcOffset = 0,
        public int $dstOffset = 0,
        public int $size = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['srcOffset'] = $this->srcOffset;
        $members['dstOffset'] = $this->dstOffset;
        $members['size'] = $this->size;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            srcOffset: (int) ($members['srcOffset'] ?? 0),
            dstOffset: (int) ($members['dstOffset'] ?? 0),
            size: (int) ($members['size'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkBufferCopy2::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkBufferCopy2::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkBufferCopy2::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkBufferCopy2::size();
    }
}
