<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkBufferMemoryBarrier2\VkBufferMemoryBarrier2 as ExtVkBufferMemoryBarrier2;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkBufferMemoryBarrier2">, 11 members.
 *
 * The typed shape of the array ExtVkBufferMemoryBarrier2::pack() takes and
 * ExtVkBufferMemoryBarrier2::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkBufferMemoryBarrier2
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::BUFFER_MEMORY_BARRIER_2,
        public int $pNext = 0,
        public int $srcStageMask = 0,
        public int $srcAccessMask = 0,
        public int $dstStageMask = 0,
        public int $dstAccessMask = 0,
        public int $srcQueueFamilyIndex = 0,
        public int $dstQueueFamilyIndex = 0,
        public int $buffer = 0,
        public int $offset = 0,
        public int $size = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['srcStageMask'] = $this->srcStageMask;
        $members['srcAccessMask'] = $this->srcAccessMask;
        $members['dstStageMask'] = $this->dstStageMask;
        $members['dstAccessMask'] = $this->dstAccessMask;
        $members['srcQueueFamilyIndex'] = $this->srcQueueFamilyIndex;
        $members['dstQueueFamilyIndex'] = $this->dstQueueFamilyIndex;
        $members['buffer'] = $this->buffer;
        $members['offset'] = $this->offset;
        $members['size'] = $this->size;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            srcStageMask: (int) ($members['srcStageMask'] ?? 0),
            srcAccessMask: (int) ($members['srcAccessMask'] ?? 0),
            dstStageMask: (int) ($members['dstStageMask'] ?? 0),
            dstAccessMask: (int) ($members['dstAccessMask'] ?? 0),
            srcQueueFamilyIndex: (int) ($members['srcQueueFamilyIndex'] ?? 0),
            dstQueueFamilyIndex: (int) ($members['dstQueueFamilyIndex'] ?? 0),
            buffer: (int) ($members['buffer'] ?? 0),
            offset: (int) ($members['offset'] ?? 0),
            size: (int) ($members['size'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkBufferMemoryBarrier2::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkBufferMemoryBarrier2::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkBufferMemoryBarrier2::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkBufferMemoryBarrier2::size();
    }
}
