<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkClearValue\VkClearValue as ExtVkClearValue;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="union" name="VkClearValue">, 2 members.
 *
 * The typed shape of the array ExtVkClearValue::pack() takes and
 * ExtVkClearValue::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 *
 * A union. Every member is nullable and defaults to null, because only
 * the one you wrote has a meaning; toArray() emits the members that are
 * not null, in registry order, and the last one written wins. unpack()
 * hands back every member, because which one is live is not knowable
 * from the bytes.
 */
final readonly class VkClearValue
{
    public function __construct(
        public ?VkClearColorValue $color = null,
        public ?VkClearDepthStencilValue $depthStencil = null,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        if (! is_null($this->color)) {
            $members['color'] = $this->color->toArray();
        }
        if (! is_null($this->depthStencil)) {
            $members['depthStencil'] = $this->depthStencil->toArray();
        }

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            color: is_array($members['color'] ?? null) ? VkClearColorValue::fromArray($members['color']) : null,
            depthStencil: is_array($members['depthStencil'] ?? null) ? VkClearDepthStencilValue::fromArray($members['depthStencil']) : null,
        );
    }

    public function pack(): int
    {
        return ExtVkClearValue::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkClearValue::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkClearValue::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkClearValue::size();
    }
}
