<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkClearAttachment\VkClearAttachment as ExtVkClearAttachment;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkClearAttachment">, 3 members.
 *
 * The typed shape of the array ExtVkClearAttachment::pack() takes and
 * ExtVkClearAttachment::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkClearAttachment
{
    public function __construct(
        public int $aspectMask = 0,
        public int $colorAttachment = 0,
        public ?VkClearValue $clearValue = null,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['aspectMask'] = $this->aspectMask;
        $members['colorAttachment'] = $this->colorAttachment;
        if (! is_null($this->clearValue)) {
            $members['clearValue'] = $this->clearValue->toArray();
        }

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            aspectMask: (int) ($members['aspectMask'] ?? 0),
            colorAttachment: (int) ($members['colorAttachment'] ?? 0),
            clearValue: is_array($members['clearValue'] ?? null) ? VkClearValue::fromArray($members['clearValue']) : null,
        );
    }

    public function pack(): int
    {
        return ExtVkClearAttachment::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkClearAttachment::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkClearAttachment::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkClearAttachment::size();
    }
}
