<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkCommandBufferLevel;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkCommandBufferAllocateInfo\VkCommandBufferAllocateInfo as ExtVkCommandBufferAllocateInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkCommandBufferAllocateInfo">, 5 members.
 *
 * The typed shape of the array ExtVkCommandBufferAllocateInfo::pack() takes and
 * ExtVkCommandBufferAllocateInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkCommandBufferAllocateInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::COMMAND_BUFFER_ALLOCATE_INFO,
        public int $pNext = 0,
        public int $commandPool = 0,
        public VkCommandBufferLevel|int $level = 0,
        public int $commandBufferCount = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['commandPool'] = $this->commandPool;
        $members['level'] = $this->level instanceof \BackedEnum ? $this->level->value : $this->level;
        $members['commandBufferCount'] = $this->commandBufferCount;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            commandPool: (int) ($members['commandPool'] ?? 0),
            level: (int) ($members['level'] ?? 0),
            commandBufferCount: (int) ($members['commandBufferCount'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkCommandBufferAllocateInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkCommandBufferAllocateInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkCommandBufferAllocateInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkCommandBufferAllocateInfo::size();
    }
}
