<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkComputePipelineCreateInfo\VkComputePipelineCreateInfo as ExtVkComputePipelineCreateInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkComputePipelineCreateInfo">, 7 members.
 *
 * The typed shape of the array ExtVkComputePipelineCreateInfo::pack() takes and
 * ExtVkComputePipelineCreateInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkComputePipelineCreateInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::COMPUTE_PIPELINE_CREATE_INFO,
        public int $pNext = 0,
        public int $flags = 0,
        public ?VkPipelineShaderStageCreateInfo $stage = null,
        public int $layout = 0,
        public int $basePipelineHandle = 0,
        public int $basePipelineIndex = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        if (! is_null($this->stage)) {
            $members['stage'] = $this->stage->toArray();
        }
        $members['layout'] = $this->layout;
        $members['basePipelineHandle'] = $this->basePipelineHandle;
        $members['basePipelineIndex'] = $this->basePipelineIndex;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            stage: is_array($members['stage'] ?? null) ? VkPipelineShaderStageCreateInfo::fromArray($members['stage']) : null,
            layout: (int) ($members['layout'] ?? 0),
            basePipelineHandle: (int) ($members['basePipelineHandle'] ?? 0),
            basePipelineIndex: (int) ($members['basePipelineIndex'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkComputePipelineCreateInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkComputePipelineCreateInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkComputePipelineCreateInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkComputePipelineCreateInfo::size();
    }
}
