<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkCommandBufferBeginInfo\VkCommandBufferBeginInfo as ExtVkCommandBufferBeginInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkCommandBufferBeginInfo">, 4 members.
 *
 * The typed shape of the array ExtVkCommandBufferBeginInfo::pack() takes and
 * ExtVkCommandBufferBeginInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkCommandBufferBeginInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::COMMAND_BUFFER_BEGIN_INFO,
        public int $pNext = 0,
        public int $flags = 0,
        public int $pInheritanceInfo = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        $members['pInheritanceInfo'] = $this->pInheritanceInfo;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            pInheritanceInfo: (int) ($members['pInheritanceInfo'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkCommandBufferBeginInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkCommandBufferBeginInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkCommandBufferBeginInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkCommandBufferBeginInfo::size();
    }
}
