<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkImageLayout;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkCopyImageToMemoryInfo\VkCopyImageToMemoryInfo as ExtVkCopyImageToMemoryInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkCopyImageToMemoryInfo">, 7 members.
 *
 * The typed shape of the array ExtVkCopyImageToMemoryInfo::pack() takes and
 * ExtVkCopyImageToMemoryInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkCopyImageToMemoryInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::COPY_IMAGE_TO_MEMORY_INFO,
        public int $pNext = 0,
        public int $flags = 0,
        public int $srcImage = 0,
        public VkImageLayout|int $srcImageLayout = 0,
        public int $regionCount = 0,
        public int $pRegions = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        $members['srcImage'] = $this->srcImage;
        $members['srcImageLayout'] = $this->srcImageLayout instanceof \BackedEnum ? $this->srcImageLayout->value : $this->srcImageLayout;
        $members['regionCount'] = $this->regionCount;
        $members['pRegions'] = $this->pRegions;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            srcImage: (int) ($members['srcImage'] ?? 0),
            srcImageLayout: (int) ($members['srcImageLayout'] ?? 0),
            regionCount: (int) ($members['regionCount'] ?? 0),
            pRegions: (int) ($members['pRegions'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkCopyImageToMemoryInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkCopyImageToMemoryInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkCopyImageToMemoryInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkCopyImageToMemoryInfo::size();
    }
}
