<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkConformanceVersion\VkConformanceVersion as ExtVkConformanceVersion;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkConformanceVersion">, 4 members.
 *
 * The typed shape of the array ExtVkConformanceVersion::pack() takes and
 * ExtVkConformanceVersion::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkConformanceVersion
{
    public function __construct(
        public int $major = 0,
        public int $minor = 0,
        public int $subminor = 0,
        public int $patch = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['major'] = $this->major;
        $members['minor'] = $this->minor;
        $members['subminor'] = $this->subminor;
        $members['patch'] = $this->patch;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            major: (int) ($members['major'] ?? 0),
            minor: (int) ($members['minor'] ?? 0),
            subminor: (int) ($members['subminor'] ?? 0),
            patch: (int) ($members['patch'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkConformanceVersion::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkConformanceVersion::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkConformanceVersion::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkConformanceVersion::size();
    }
}
