<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkCopyBufferInfo2\VkCopyBufferInfo2 as ExtVkCopyBufferInfo2;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkCopyBufferInfo2">, 6 members.
 *
 * The typed shape of the array ExtVkCopyBufferInfo2::pack() takes and
 * ExtVkCopyBufferInfo2::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkCopyBufferInfo2
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::COPY_BUFFER_INFO_2,
        public int $pNext = 0,
        public int $srcBuffer = 0,
        public int $dstBuffer = 0,
        public int $regionCount = 0,
        public int $pRegions = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['srcBuffer'] = $this->srcBuffer;
        $members['dstBuffer'] = $this->dstBuffer;
        $members['regionCount'] = $this->regionCount;
        $members['pRegions'] = $this->pRegions;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            srcBuffer: (int) ($members['srcBuffer'] ?? 0),
            dstBuffer: (int) ($members['dstBuffer'] ?? 0),
            regionCount: (int) ($members['regionCount'] ?? 0),
            pRegions: (int) ($members['pRegions'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkCopyBufferInfo2::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkCopyBufferInfo2::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkCopyBufferInfo2::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkCopyBufferInfo2::size();
    }
}
