<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkCommandBufferSubmitInfo\VkCommandBufferSubmitInfo as ExtVkCommandBufferSubmitInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkCommandBufferSubmitInfo">, 4 members.
 *
 * The typed shape of the array ExtVkCommandBufferSubmitInfo::pack() takes and
 * ExtVkCommandBufferSubmitInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkCommandBufferSubmitInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::COMMAND_BUFFER_SUBMIT_INFO,
        public int $pNext = 0,
        public int $commandBuffer = 0,
        public int $deviceMask = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['commandBuffer'] = $this->commandBuffer;
        $members['deviceMask'] = $this->deviceMask;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            commandBuffer: (int) ($members['commandBuffer'] ?? 0),
            deviceMask: (int) ($members['deviceMask'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkCommandBufferSubmitInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkCommandBufferSubmitInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkCommandBufferSubmitInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkCommandBufferSubmitInfo::size();
    }
}
