<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkFormat;
use Jovian\Bindings\Vulkan\Enums\VkSampleCountFlagBits;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkCommandBufferInheritanceRenderingInfo\VkCommandBufferInheritanceRenderingInfo as ExtVkCommandBufferInheritanceRenderingInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkCommandBufferInheritanceRenderingInfo">, 9 members.
 *
 * The typed shape of the array ExtVkCommandBufferInheritanceRenderingInfo::pack() takes and
 * ExtVkCommandBufferInheritanceRenderingInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkCommandBufferInheritanceRenderingInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::COMMAND_BUFFER_INHERITANCE_RENDERING_INFO,
        public int $pNext = 0,
        public int $flags = 0,
        public int $viewMask = 0,
        public int $colorAttachmentCount = 0,
        public int $pColorAttachmentFormats = 0,
        public VkFormat|int $depthAttachmentFormat = 0,
        public VkFormat|int $stencilAttachmentFormat = 0,
        public VkSampleCountFlagBits|int $rasterizationSamples = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        $members['viewMask'] = $this->viewMask;
        $members['colorAttachmentCount'] = $this->colorAttachmentCount;
        $members['pColorAttachmentFormats'] = $this->pColorAttachmentFormats;
        $members['depthAttachmentFormat'] = $this->depthAttachmentFormat instanceof \BackedEnum ? $this->depthAttachmentFormat->value : $this->depthAttachmentFormat;
        $members['stencilAttachmentFormat'] = $this->stencilAttachmentFormat instanceof \BackedEnum ? $this->stencilAttachmentFormat->value : $this->stencilAttachmentFormat;
        $members['rasterizationSamples'] = $this->rasterizationSamples instanceof \BackedEnum ? $this->rasterizationSamples->value : $this->rasterizationSamples;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            viewMask: (int) ($members['viewMask'] ?? 0),
            colorAttachmentCount: (int) ($members['colorAttachmentCount'] ?? 0),
            pColorAttachmentFormats: (int) ($members['pColorAttachmentFormats'] ?? 0),
            depthAttachmentFormat: (int) ($members['depthAttachmentFormat'] ?? 0),
            stencilAttachmentFormat: (int) ($members['stencilAttachmentFormat'] ?? 0),
            rasterizationSamples: (int) ($members['rasterizationSamples'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkCommandBufferInheritanceRenderingInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkCommandBufferInheritanceRenderingInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkCommandBufferInheritanceRenderingInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkCommandBufferInheritanceRenderingInfo::size();
    }
}
