<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkDescriptorType;
use Vulkan\Struct\VkDescriptorSetLayoutBinding\VkDescriptorSetLayoutBinding as ExtVkDescriptorSetLayoutBinding;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkDescriptorSetLayoutBinding">, 5 members.
 *
 * The typed shape of the array ExtVkDescriptorSetLayoutBinding::pack() takes and
 * ExtVkDescriptorSetLayoutBinding::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkDescriptorSetLayoutBinding
{
    public function __construct(
        public int $binding = 0,
        public VkDescriptorType|int $descriptorType = 0,
        public int $descriptorCount = 0,
        public int $stageFlags = 0,
        public int $pImmutableSamplers = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['binding'] = $this->binding;
        $members['descriptorType'] = $this->descriptorType instanceof \BackedEnum ? $this->descriptorType->value : $this->descriptorType;
        $members['descriptorCount'] = $this->descriptorCount;
        $members['stageFlags'] = $this->stageFlags;
        $members['pImmutableSamplers'] = $this->pImmutableSamplers;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            binding: (int) ($members['binding'] ?? 0),
            descriptorType: (int) ($members['descriptorType'] ?? 0),
            descriptorCount: (int) ($members['descriptorCount'] ?? 0),
            stageFlags: (int) ($members['stageFlags'] ?? 0),
            pImmutableSamplers: (int) ($members['pImmutableSamplers'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkDescriptorSetLayoutBinding::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkDescriptorSetLayoutBinding::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkDescriptorSetLayoutBinding::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkDescriptorSetLayoutBinding::size();
    }
}
