<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkObjectType;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkDebugUtilsObjectNameInfoEXT\VkDebugUtilsObjectNameInfoEXT as ExtVkDebugUtilsObjectNameInfoEXT;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkDebugUtilsObjectNameInfoEXT">, 5 members.
 *
 * The typed shape of the array ExtVkDebugUtilsObjectNameInfoEXT::pack() takes and
 * ExtVkDebugUtilsObjectNameInfoEXT::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkDebugUtilsObjectNameInfoEXT
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::DEBUG_UTILS_OBJECT_NAME_INFO_EXT,
        public int $pNext = 0,
        public VkObjectType|int $objectType = 0,
        public int $objectHandle = 0,
        public int $pObjectName = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['objectType'] = $this->objectType instanceof \BackedEnum ? $this->objectType->value : $this->objectType;
        $members['objectHandle'] = $this->objectHandle;
        $members['pObjectName'] = $this->pObjectName;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            objectType: (int) ($members['objectType'] ?? 0),
            objectHandle: (int) ($members['objectHandle'] ?? 0),
            pObjectName: (int) ($members['pObjectName'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkDebugUtilsObjectNameInfoEXT::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkDebugUtilsObjectNameInfoEXT::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkDebugUtilsObjectNameInfoEXT::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkDebugUtilsObjectNameInfoEXT::size();
    }
}
