<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkDescriptorSetVariableDescriptorCountLayoutSupport\VkDescriptorSetVariableDescriptorCountLayoutSupport as ExtVkDescriptorSetVariableDescriptorCountLayoutSupport;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkDescriptorSetVariableDescriptorCountLayoutSupport">, 3 members.
 *
 * The typed shape of the array ExtVkDescriptorSetVariableDescriptorCountLayoutSupport::pack() takes and
 * ExtVkDescriptorSetVariableDescriptorCountLayoutSupport::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkDescriptorSetVariableDescriptorCountLayoutSupport
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT,
        public int $pNext = 0,
        public int $maxVariableDescriptorCount = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['maxVariableDescriptorCount'] = $this->maxVariableDescriptorCount;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            maxVariableDescriptorCount: (int) ($members['maxVariableDescriptorCount'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkDescriptorSetVariableDescriptorCountLayoutSupport::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkDescriptorSetVariableDescriptorCountLayoutSupport::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkDescriptorSetVariableDescriptorCountLayoutSupport::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkDescriptorSetVariableDescriptorCountLayoutSupport::size();
    }
}
