<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkDeviceGroupSubmitInfo\VkDeviceGroupSubmitInfo as ExtVkDeviceGroupSubmitInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkDeviceGroupSubmitInfo">, 8 members.
 *
 * The typed shape of the array ExtVkDeviceGroupSubmitInfo::pack() takes and
 * ExtVkDeviceGroupSubmitInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkDeviceGroupSubmitInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::DEVICE_GROUP_SUBMIT_INFO,
        public int $pNext = 0,
        public int $waitSemaphoreCount = 0,
        public int $pWaitSemaphoreDeviceIndices = 0,
        public int $commandBufferCount = 0,
        public int $pCommandBufferDeviceMasks = 0,
        public int $signalSemaphoreCount = 0,
        public int $pSignalSemaphoreDeviceIndices = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['waitSemaphoreCount'] = $this->waitSemaphoreCount;
        $members['pWaitSemaphoreDeviceIndices'] = $this->pWaitSemaphoreDeviceIndices;
        $members['commandBufferCount'] = $this->commandBufferCount;
        $members['pCommandBufferDeviceMasks'] = $this->pCommandBufferDeviceMasks;
        $members['signalSemaphoreCount'] = $this->signalSemaphoreCount;
        $members['pSignalSemaphoreDeviceIndices'] = $this->pSignalSemaphoreDeviceIndices;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            waitSemaphoreCount: (int) ($members['waitSemaphoreCount'] ?? 0),
            pWaitSemaphoreDeviceIndices: (int) ($members['pWaitSemaphoreDeviceIndices'] ?? 0),
            commandBufferCount: (int) ($members['commandBufferCount'] ?? 0),
            pCommandBufferDeviceMasks: (int) ($members['pCommandBufferDeviceMasks'] ?? 0),
            signalSemaphoreCount: (int) ($members['signalSemaphoreCount'] ?? 0),
            pSignalSemaphoreDeviceIndices: (int) ($members['pSignalSemaphoreDeviceIndices'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkDeviceGroupSubmitInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkDeviceGroupSubmitInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkDeviceGroupSubmitInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkDeviceGroupSubmitInfo::size();
    }
}
