<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkDeviceQueueInfo2\VkDeviceQueueInfo2 as ExtVkDeviceQueueInfo2;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkDeviceQueueInfo2">, 5 members.
 *
 * The typed shape of the array ExtVkDeviceQueueInfo2::pack() takes and
 * ExtVkDeviceQueueInfo2::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkDeviceQueueInfo2
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::DEVICE_QUEUE_INFO_2,
        public int $pNext = 0,
        public int $flags = 0,
        public int $queueFamilyIndex = 0,
        public int $queueIndex = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        $members['queueFamilyIndex'] = $this->queueFamilyIndex;
        $members['queueIndex'] = $this->queueIndex;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            queueFamilyIndex: (int) ($members['queueFamilyIndex'] ?? 0),
            queueIndex: (int) ($members['queueIndex'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkDeviceQueueInfo2::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkDeviceQueueInfo2::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkDeviceQueueInfo2::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkDeviceQueueInfo2::size();
    }
}
