<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkImageLayout;
use Vulkan\Struct\VkDescriptorImageInfo\VkDescriptorImageInfo as ExtVkDescriptorImageInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkDescriptorImageInfo">, 3 members.
 *
 * The typed shape of the array ExtVkDescriptorImageInfo::pack() takes and
 * ExtVkDescriptorImageInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkDescriptorImageInfo
{
    public function __construct(
        public int $sampler = 0,
        public int $imageView = 0,
        public VkImageLayout|int $imageLayout = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sampler'] = $this->sampler;
        $members['imageView'] = $this->imageView;
        $members['imageLayout'] = $this->imageLayout instanceof \BackedEnum ? $this->imageLayout->value : $this->imageLayout;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sampler: (int) ($members['sampler'] ?? 0),
            imageView: (int) ($members['imageView'] ?? 0),
            imageLayout: (int) ($members['imageLayout'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkDescriptorImageInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkDescriptorImageInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkDescriptorImageInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkDescriptorImageInfo::size();
    }
}
