<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkDeviceGroupRenderPassBeginInfo\VkDeviceGroupRenderPassBeginInfo as ExtVkDeviceGroupRenderPassBeginInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkDeviceGroupRenderPassBeginInfo">, 5 members.
 *
 * The typed shape of the array ExtVkDeviceGroupRenderPassBeginInfo::pack() takes and
 * ExtVkDeviceGroupRenderPassBeginInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkDeviceGroupRenderPassBeginInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::DEVICE_GROUP_RENDER_PASS_BEGIN_INFO,
        public int $pNext = 0,
        public int $deviceMask = 0,
        public int $deviceRenderAreaCount = 0,
        public int $pDeviceRenderAreas = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['deviceMask'] = $this->deviceMask;
        $members['deviceRenderAreaCount'] = $this->deviceRenderAreaCount;
        $members['pDeviceRenderAreas'] = $this->pDeviceRenderAreas;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            deviceMask: (int) ($members['deviceMask'] ?? 0),
            deviceRenderAreaCount: (int) ($members['deviceRenderAreaCount'] ?? 0),
            pDeviceRenderAreas: (int) ($members['pDeviceRenderAreas'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkDeviceGroupRenderPassBeginInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkDeviceGroupRenderPassBeginInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkDeviceGroupRenderPassBeginInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkDeviceGroupRenderPassBeginInfo::size();
    }
}
