<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkDebugUtilsLabelEXT\VkDebugUtilsLabelEXT as ExtVkDebugUtilsLabelEXT;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkDebugUtilsLabelEXT">, 4 members.
 *
 * The typed shape of the array ExtVkDebugUtilsLabelEXT::pack() takes and
 * ExtVkDebugUtilsLabelEXT::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkDebugUtilsLabelEXT
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::DEBUG_UTILS_LABEL_EXT,
        public int $pNext = 0,
        public int $pLabelName = 0,
        public array $color = [],
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['pLabelName'] = $this->pLabelName;
        $members['color'] = $this->color;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            pLabelName: (int) ($members['pLabelName'] ?? 0),
            color: (array) ($members['color'] ?? []),
        );
    }

    public function pack(): int
    {
        return ExtVkDebugUtilsLabelEXT::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkDebugUtilsLabelEXT::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkDebugUtilsLabelEXT::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkDebugUtilsLabelEXT::size();
    }
}
