<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkDeviceQueueCreateInfo\VkDeviceQueueCreateInfo as ExtVkDeviceQueueCreateInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkDeviceQueueCreateInfo">, 6 members.
 *
 * The typed shape of the array ExtVkDeviceQueueCreateInfo::pack() takes and
 * ExtVkDeviceQueueCreateInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkDeviceQueueCreateInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::DEVICE_QUEUE_CREATE_INFO,
        public int $pNext = 0,
        public int $flags = 0,
        public int $queueFamilyIndex = 0,
        public int $queueCount = 0,
        public int $pQueuePriorities = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        $members['queueFamilyIndex'] = $this->queueFamilyIndex;
        $members['queueCount'] = $this->queueCount;
        $members['pQueuePriorities'] = $this->pQueuePriorities;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            queueFamilyIndex: (int) ($members['queueFamilyIndex'] ?? 0),
            queueCount: (int) ($members['queueCount'] ?? 0),
            pQueuePriorities: (int) ($members['pQueuePriorities'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkDeviceQueueCreateInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkDeviceQueueCreateInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkDeviceQueueCreateInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkDeviceQueueCreateInfo::size();
    }
}
