<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkDrawIndirectCommand\VkDrawIndirectCommand as ExtVkDrawIndirectCommand;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkDrawIndirectCommand">, 4 members.
 *
 * The typed shape of the array ExtVkDrawIndirectCommand::pack() takes and
 * ExtVkDrawIndirectCommand::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkDrawIndirectCommand
{
    public function __construct(
        public int $vertexCount = 0,
        public int $instanceCount = 0,
        public int $firstVertex = 0,
        public int $firstInstance = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['vertexCount'] = $this->vertexCount;
        $members['instanceCount'] = $this->instanceCount;
        $members['firstVertex'] = $this->firstVertex;
        $members['firstInstance'] = $this->firstInstance;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            vertexCount: (int) ($members['vertexCount'] ?? 0),
            instanceCount: (int) ($members['instanceCount'] ?? 0),
            firstVertex: (int) ($members['firstVertex'] ?? 0),
            firstInstance: (int) ($members['firstInstance'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkDrawIndirectCommand::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkDrawIndirectCommand::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkDrawIndirectCommand::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkDrawIndirectCommand::size();
    }
}
