<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkExportMemoryAllocateInfo\VkExportMemoryAllocateInfo as ExtVkExportMemoryAllocateInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkExportMemoryAllocateInfo">, 3 members.
 *
 * The typed shape of the array ExtVkExportMemoryAllocateInfo::pack() takes and
 * ExtVkExportMemoryAllocateInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkExportMemoryAllocateInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::EXPORT_MEMORY_ALLOCATE_INFO,
        public int $pNext = 0,
        public int $handleTypes = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['handleTypes'] = $this->handleTypes;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            handleTypes: (int) ($members['handleTypes'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkExportMemoryAllocateInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkExportMemoryAllocateInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkExportMemoryAllocateInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkExportMemoryAllocateInfo::size();
    }
}
