<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkExtent3D\VkExtent3D as ExtVkExtent3D;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkExtent3D">, 3 members.
 *
 * The typed shape of the array ExtVkExtent3D::pack() takes and
 * ExtVkExtent3D::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkExtent3D
{
    public function __construct(
        public int $width = 0,
        public int $height = 0,
        public int $depth = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['width'] = $this->width;
        $members['height'] = $this->height;
        $members['depth'] = $this->depth;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            width: (int) ($members['width'] ?? 0),
            height: (int) ($members['height'] ?? 0),
            depth: (int) ($members['depth'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkExtent3D::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkExtent3D::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkExtent3D::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkExtent3D::size();
    }
}
