<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkExternalSemaphoreProperties\VkExternalSemaphoreProperties as ExtVkExternalSemaphoreProperties;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkExternalSemaphoreProperties">, 5 members.
 *
 * The typed shape of the array ExtVkExternalSemaphoreProperties::pack() takes and
 * ExtVkExternalSemaphoreProperties::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkExternalSemaphoreProperties
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::EXTERNAL_SEMAPHORE_PROPERTIES,
        public int $pNext = 0,
        public int $exportFromImportedHandleTypes = 0,
        public int $compatibleHandleTypes = 0,
        public int $externalSemaphoreFeatures = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['exportFromImportedHandleTypes'] = $this->exportFromImportedHandleTypes;
        $members['compatibleHandleTypes'] = $this->compatibleHandleTypes;
        $members['externalSemaphoreFeatures'] = $this->externalSemaphoreFeatures;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            exportFromImportedHandleTypes: (int) ($members['exportFromImportedHandleTypes'] ?? 0),
            compatibleHandleTypes: (int) ($members['compatibleHandleTypes'] ?? 0),
            externalSemaphoreFeatures: (int) ($members['externalSemaphoreFeatures'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkExternalSemaphoreProperties::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkExternalSemaphoreProperties::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkExternalSemaphoreProperties::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkExternalSemaphoreProperties::size();
    }
}
