<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkExternalImageFormatProperties\VkExternalImageFormatProperties as ExtVkExternalImageFormatProperties;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkExternalImageFormatProperties">, 3 members.
 *
 * The typed shape of the array ExtVkExternalImageFormatProperties::pack() takes and
 * ExtVkExternalImageFormatProperties::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkExternalImageFormatProperties
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::EXTERNAL_IMAGE_FORMAT_PROPERTIES,
        public int $pNext = 0,
        public ?VkExternalMemoryProperties $externalMemoryProperties = null,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        if (! is_null($this->externalMemoryProperties)) {
            $members['externalMemoryProperties'] = $this->externalMemoryProperties->toArray();
        }

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            externalMemoryProperties: is_array($members['externalMemoryProperties'] ?? null) ? VkExternalMemoryProperties::fromArray($members['externalMemoryProperties']) : null,
        );
    }

    public function pack(): int
    {
        return ExtVkExternalImageFormatProperties::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkExternalImageFormatProperties::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkExternalImageFormatProperties::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkExternalImageFormatProperties::size();
    }
}
