<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkFramebufferAttachmentImageInfo\VkFramebufferAttachmentImageInfo as ExtVkFramebufferAttachmentImageInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkFramebufferAttachmentImageInfo">, 9 members.
 *
 * The typed shape of the array ExtVkFramebufferAttachmentImageInfo::pack() takes and
 * ExtVkFramebufferAttachmentImageInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkFramebufferAttachmentImageInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::FRAMEBUFFER_ATTACHMENT_IMAGE_INFO,
        public int $pNext = 0,
        public int $flags = 0,
        public int $usage = 0,
        public int $width = 0,
        public int $height = 0,
        public int $layerCount = 0,
        public int $viewFormatCount = 0,
        public int $pViewFormats = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        $members['usage'] = $this->usage;
        $members['width'] = $this->width;
        $members['height'] = $this->height;
        $members['layerCount'] = $this->layerCount;
        $members['viewFormatCount'] = $this->viewFormatCount;
        $members['pViewFormats'] = $this->pViewFormats;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            usage: (int) ($members['usage'] ?? 0),
            width: (int) ($members['width'] ?? 0),
            height: (int) ($members['height'] ?? 0),
            layerCount: (int) ($members['layerCount'] ?? 0),
            viewFormatCount: (int) ($members['viewFormatCount'] ?? 0),
            pViewFormats: (int) ($members['pViewFormats'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkFramebufferAttachmentImageInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkFramebufferAttachmentImageInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkFramebufferAttachmentImageInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkFramebufferAttachmentImageInfo::size();
    }
}
