<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkHostImageCopyDevicePerformanceQuery\VkHostImageCopyDevicePerformanceQuery as ExtVkHostImageCopyDevicePerformanceQuery;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkHostImageCopyDevicePerformanceQuery">, 4 members.
 *
 * The typed shape of the array ExtVkHostImageCopyDevicePerformanceQuery::pack() takes and
 * ExtVkHostImageCopyDevicePerformanceQuery::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkHostImageCopyDevicePerformanceQuery
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::HOST_IMAGE_COPY_DEVICE_PERFORMANCE_QUERY,
        public int $pNext = 0,
        public bool $optimalDeviceAccess = false,
        public bool $identicalMemoryLayout = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['optimalDeviceAccess'] = $this->optimalDeviceAccess;
        $members['identicalMemoryLayout'] = $this->identicalMemoryLayout;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            optimalDeviceAccess: (bool) ($members['optimalDeviceAccess'] ?? false),
            identicalMemoryLayout: (bool) ($members['identicalMemoryLayout'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkHostImageCopyDevicePerformanceQuery::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkHostImageCopyDevicePerformanceQuery::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkHostImageCopyDevicePerformanceQuery::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkHostImageCopyDevicePerformanceQuery::size();
    }
}
