<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkImportMetalSharedEventInfoEXT\VkImportMetalSharedEventInfoEXT as ExtVkImportMetalSharedEventInfoEXT;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkImportMetalSharedEventInfoEXT">, 3 members.
 *
 * The typed shape of the array ExtVkImportMetalSharedEventInfoEXT::pack() takes and
 * ExtVkImportMetalSharedEventInfoEXT::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkImportMetalSharedEventInfoEXT
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::IMPORT_METAL_SHARED_EVENT_INFO_EXT,
        public int $pNext = 0,
        public int $mtlSharedEvent = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['mtlSharedEvent'] = $this->mtlSharedEvent;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            mtlSharedEvent: (int) ($members['mtlSharedEvent'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkImportMetalSharedEventInfoEXT::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkImportMetalSharedEventInfoEXT::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkImportMetalSharedEventInfoEXT::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkImportMetalSharedEventInfoEXT::size();
    }
}
