<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkImageBlit\VkImageBlit as ExtVkImageBlit;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkImageBlit">, 4 members.
 *
 * The typed shape of the array ExtVkImageBlit::pack() takes and
 * ExtVkImageBlit::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkImageBlit
{
    public function __construct(
        public ?VkImageSubresourceLayers $srcSubresource = null,
        public array $srcOffsets = [],
        public ?VkImageSubresourceLayers $dstSubresource = null,
        public array $dstOffsets = [],
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        if (! is_null($this->srcSubresource)) {
            $members['srcSubresource'] = $this->srcSubresource->toArray();
        }
        $members['srcOffsets'] = array_map(
            static fn (mixed $item): mixed => $item instanceof VkOffset3D ? $item->toArray() : $item,
            $this->srcOffsets,
        );
        if (! is_null($this->dstSubresource)) {
            $members['dstSubresource'] = $this->dstSubresource->toArray();
        }
        $members['dstOffsets'] = array_map(
            static fn (mixed $item): mixed => $item instanceof VkOffset3D ? $item->toArray() : $item,
            $this->dstOffsets,
        );

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            srcSubresource: is_array($members['srcSubresource'] ?? null) ? VkImageSubresourceLayers::fromArray($members['srcSubresource']) : null,
            srcOffsets: array_map(
                static fn (array $item): VkOffset3D => VkOffset3D::fromArray($item),
                (array) ($members['srcOffsets'] ?? []),
            ),
            dstSubresource: is_array($members['dstSubresource'] ?? null) ? VkImageSubresourceLayers::fromArray($members['dstSubresource']) : null,
            dstOffsets: array_map(
                static fn (array $item): VkOffset3D => VkOffset3D::fromArray($item),
                (array) ($members['dstOffsets'] ?? []),
            ),
        );
    }

    public function pack(): int
    {
        return ExtVkImageBlit::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkImageBlit::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkImageBlit::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkImageBlit::size();
    }
}
