<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkImageFormatListCreateInfo\VkImageFormatListCreateInfo as ExtVkImageFormatListCreateInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkImageFormatListCreateInfo">, 4 members.
 *
 * The typed shape of the array ExtVkImageFormatListCreateInfo::pack() takes and
 * ExtVkImageFormatListCreateInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkImageFormatListCreateInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::IMAGE_FORMAT_LIST_CREATE_INFO,
        public int $pNext = 0,
        public int $viewFormatCount = 0,
        public int $pViewFormats = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['viewFormatCount'] = $this->viewFormatCount;
        $members['pViewFormats'] = $this->pViewFormats;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            viewFormatCount: (int) ($members['viewFormatCount'] ?? 0),
            pViewFormats: (int) ($members['pViewFormats'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkImageFormatListCreateInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkImageFormatListCreateInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkImageFormatListCreateInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkImageFormatListCreateInfo::size();
    }
}
