<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkImageFormatProperties\VkImageFormatProperties as ExtVkImageFormatProperties;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkImageFormatProperties">, 5 members.
 *
 * The typed shape of the array ExtVkImageFormatProperties::pack() takes and
 * ExtVkImageFormatProperties::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkImageFormatProperties
{
    public function __construct(
        public ?VkExtent3D $maxExtent = null,
        public int $maxMipLevels = 0,
        public int $maxArrayLayers = 0,
        public int $sampleCounts = 0,
        public int $maxResourceSize = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        if (! is_null($this->maxExtent)) {
            $members['maxExtent'] = $this->maxExtent->toArray();
        }
        $members['maxMipLevels'] = $this->maxMipLevels;
        $members['maxArrayLayers'] = $this->maxArrayLayers;
        $members['sampleCounts'] = $this->sampleCounts;
        $members['maxResourceSize'] = $this->maxResourceSize;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            maxExtent: is_array($members['maxExtent'] ?? null) ? VkExtent3D::fromArray($members['maxExtent']) : null,
            maxMipLevels: (int) ($members['maxMipLevels'] ?? 0),
            maxArrayLayers: (int) ($members['maxArrayLayers'] ?? 0),
            sampleCounts: (int) ($members['sampleCounts'] ?? 0),
            maxResourceSize: (int) ($members['maxResourceSize'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkImageFormatProperties::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkImageFormatProperties::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkImageFormatProperties::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkImageFormatProperties::size();
    }
}
