<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkImageCopy\VkImageCopy as ExtVkImageCopy;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkImageCopy">, 5 members.
 *
 * The typed shape of the array ExtVkImageCopy::pack() takes and
 * ExtVkImageCopy::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkImageCopy
{
    public function __construct(
        public ?VkImageSubresourceLayers $srcSubresource = null,
        public ?VkOffset3D $srcOffset = null,
        public ?VkImageSubresourceLayers $dstSubresource = null,
        public ?VkOffset3D $dstOffset = null,
        public ?VkExtent3D $extent = null,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        if (! is_null($this->srcSubresource)) {
            $members['srcSubresource'] = $this->srcSubresource->toArray();
        }
        if (! is_null($this->srcOffset)) {
            $members['srcOffset'] = $this->srcOffset->toArray();
        }
        if (! is_null($this->dstSubresource)) {
            $members['dstSubresource'] = $this->dstSubresource->toArray();
        }
        if (! is_null($this->dstOffset)) {
            $members['dstOffset'] = $this->dstOffset->toArray();
        }
        if (! is_null($this->extent)) {
            $members['extent'] = $this->extent->toArray();
        }

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            srcSubresource: is_array($members['srcSubresource'] ?? null) ? VkImageSubresourceLayers::fromArray($members['srcSubresource']) : null,
            srcOffset: is_array($members['srcOffset'] ?? null) ? VkOffset3D::fromArray($members['srcOffset']) : null,
            dstSubresource: is_array($members['dstSubresource'] ?? null) ? VkImageSubresourceLayers::fromArray($members['dstSubresource']) : null,
            dstOffset: is_array($members['dstOffset'] ?? null) ? VkOffset3D::fromArray($members['dstOffset']) : null,
            extent: is_array($members['extent'] ?? null) ? VkExtent3D::fromArray($members['extent']) : null,
        );
    }

    public function pack(): int
    {
        return ExtVkImageCopy::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkImageCopy::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkImageCopy::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkImageCopy::size();
    }
}
