<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkImageBlit2\VkImageBlit2 as ExtVkImageBlit2;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkImageBlit2">, 6 members.
 *
 * The typed shape of the array ExtVkImageBlit2::pack() takes and
 * ExtVkImageBlit2::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkImageBlit2
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::IMAGE_BLIT_2,
        public int $pNext = 0,
        public ?VkImageSubresourceLayers $srcSubresource = null,
        public array $srcOffsets = [],
        public ?VkImageSubresourceLayers $dstSubresource = null,
        public array $dstOffsets = [],
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        if (! is_null($this->srcSubresource)) {
            $members['srcSubresource'] = $this->srcSubresource->toArray();
        }
        $members['srcOffsets'] = array_map(
            static fn (mixed $item): mixed => $item instanceof VkOffset3D ? $item->toArray() : $item,
            $this->srcOffsets,
        );
        if (! is_null($this->dstSubresource)) {
            $members['dstSubresource'] = $this->dstSubresource->toArray();
        }
        $members['dstOffsets'] = array_map(
            static fn (mixed $item): mixed => $item instanceof VkOffset3D ? $item->toArray() : $item,
            $this->dstOffsets,
        );

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            srcSubresource: is_array($members['srcSubresource'] ?? null) ? VkImageSubresourceLayers::fromArray($members['srcSubresource']) : null,
            srcOffsets: array_map(
                static fn (array $item): VkOffset3D => VkOffset3D::fromArray($item),
                (array) ($members['srcOffsets'] ?? []),
            ),
            dstSubresource: is_array($members['dstSubresource'] ?? null) ? VkImageSubresourceLayers::fromArray($members['dstSubresource']) : null,
            dstOffsets: array_map(
                static fn (array $item): VkOffset3D => VkOffset3D::fromArray($item),
                (array) ($members['dstOffsets'] ?? []),
            ),
        );
    }

    public function pack(): int
    {
        return ExtVkImageBlit2::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkImageBlit2::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkImageBlit2::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkImageBlit2::size();
    }
}
