<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkImageFormatProperties2\VkImageFormatProperties2 as ExtVkImageFormatProperties2;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkImageFormatProperties2">, 3 members.
 *
 * The typed shape of the array ExtVkImageFormatProperties2::pack() takes and
 * ExtVkImageFormatProperties2::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkImageFormatProperties2
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::IMAGE_FORMAT_PROPERTIES_2,
        public int $pNext = 0,
        public ?VkImageFormatProperties $imageFormatProperties = null,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        if (! is_null($this->imageFormatProperties)) {
            $members['imageFormatProperties'] = $this->imageFormatProperties->toArray();
        }

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            imageFormatProperties: is_array($members['imageFormatProperties'] ?? null) ? VkImageFormatProperties::fromArray($members['imageFormatProperties']) : null,
        );
    }

    public function pack(): int
    {
        return ExtVkImageFormatProperties2::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkImageFormatProperties2::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkImageFormatProperties2::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkImageFormatProperties2::size();
    }
}
