<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkImageLayout;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkImageMemoryBarrier2\VkImageMemoryBarrier2 as ExtVkImageMemoryBarrier2;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkImageMemoryBarrier2">, 12 members.
 *
 * The typed shape of the array ExtVkImageMemoryBarrier2::pack() takes and
 * ExtVkImageMemoryBarrier2::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkImageMemoryBarrier2
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::IMAGE_MEMORY_BARRIER_2,
        public int $pNext = 0,
        public int $srcStageMask = 0,
        public int $srcAccessMask = 0,
        public int $dstStageMask = 0,
        public int $dstAccessMask = 0,
        public VkImageLayout|int $oldLayout = 0,
        public VkImageLayout|int $newLayout = 0,
        public int $srcQueueFamilyIndex = 0,
        public int $dstQueueFamilyIndex = 0,
        public int $image = 0,
        public ?VkImageSubresourceRange $subresourceRange = null,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['srcStageMask'] = $this->srcStageMask;
        $members['srcAccessMask'] = $this->srcAccessMask;
        $members['dstStageMask'] = $this->dstStageMask;
        $members['dstAccessMask'] = $this->dstAccessMask;
        $members['oldLayout'] = $this->oldLayout instanceof \BackedEnum ? $this->oldLayout->value : $this->oldLayout;
        $members['newLayout'] = $this->newLayout instanceof \BackedEnum ? $this->newLayout->value : $this->newLayout;
        $members['srcQueueFamilyIndex'] = $this->srcQueueFamilyIndex;
        $members['dstQueueFamilyIndex'] = $this->dstQueueFamilyIndex;
        $members['image'] = $this->image;
        if (! is_null($this->subresourceRange)) {
            $members['subresourceRange'] = $this->subresourceRange->toArray();
        }

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            srcStageMask: (int) ($members['srcStageMask'] ?? 0),
            srcAccessMask: (int) ($members['srcAccessMask'] ?? 0),
            dstStageMask: (int) ($members['dstStageMask'] ?? 0),
            dstAccessMask: (int) ($members['dstAccessMask'] ?? 0),
            oldLayout: (int) ($members['oldLayout'] ?? 0),
            newLayout: (int) ($members['newLayout'] ?? 0),
            srcQueueFamilyIndex: (int) ($members['srcQueueFamilyIndex'] ?? 0),
            dstQueueFamilyIndex: (int) ($members['dstQueueFamilyIndex'] ?? 0),
            image: (int) ($members['image'] ?? 0),
            subresourceRange: is_array($members['subresourceRange'] ?? null) ? VkImageSubresourceRange::fromArray($members['subresourceRange']) : null,
        );
    }

    public function pack(): int
    {
        return ExtVkImageMemoryBarrier2::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkImageMemoryBarrier2::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkImageMemoryBarrier2::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkImageMemoryBarrier2::size();
    }
}
