<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkImageViewUsageCreateInfo\VkImageViewUsageCreateInfo as ExtVkImageViewUsageCreateInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkImageViewUsageCreateInfo">, 3 members.
 *
 * The typed shape of the array ExtVkImageViewUsageCreateInfo::pack() takes and
 * ExtVkImageViewUsageCreateInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkImageViewUsageCreateInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::IMAGE_VIEW_USAGE_CREATE_INFO,
        public int $pNext = 0,
        public int $usage = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['usage'] = $this->usage;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            usage: (int) ($members['usage'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkImageViewUsageCreateInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkImageViewUsageCreateInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkImageViewUsageCreateInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkImageViewUsageCreateInfo::size();
    }
}
