<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkFormat;
use Jovian\Bindings\Vulkan\Enums\VkImageLayout;
use Jovian\Bindings\Vulkan\Enums\VkImageTiling;
use Jovian\Bindings\Vulkan\Enums\VkImageType;
use Jovian\Bindings\Vulkan\Enums\VkSampleCountFlagBits;
use Jovian\Bindings\Vulkan\Enums\VkSharingMode;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkImageCreateInfo\VkImageCreateInfo as ExtVkImageCreateInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkImageCreateInfo">, 15 members.
 *
 * The typed shape of the array ExtVkImageCreateInfo::pack() takes and
 * ExtVkImageCreateInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkImageCreateInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::IMAGE_CREATE_INFO,
        public int $pNext = 0,
        public int $flags = 0,
        public VkImageType|int $imageType = 0,
        public VkFormat|int $format = 0,
        public ?VkExtent3D $extent = null,
        public int $mipLevels = 0,
        public int $arrayLayers = 0,
        public VkSampleCountFlagBits|int $samples = 0,
        public VkImageTiling|int $tiling = 0,
        public int $usage = 0,
        public VkSharingMode|int $sharingMode = 0,
        public int $queueFamilyIndexCount = 0,
        public int $pQueueFamilyIndices = 0,
        public VkImageLayout|int $initialLayout = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        $members['imageType'] = $this->imageType instanceof \BackedEnum ? $this->imageType->value : $this->imageType;
        $members['format'] = $this->format instanceof \BackedEnum ? $this->format->value : $this->format;
        if (! is_null($this->extent)) {
            $members['extent'] = $this->extent->toArray();
        }
        $members['mipLevels'] = $this->mipLevels;
        $members['arrayLayers'] = $this->arrayLayers;
        $members['samples'] = $this->samples instanceof \BackedEnum ? $this->samples->value : $this->samples;
        $members['tiling'] = $this->tiling instanceof \BackedEnum ? $this->tiling->value : $this->tiling;
        $members['usage'] = $this->usage;
        $members['sharingMode'] = $this->sharingMode instanceof \BackedEnum ? $this->sharingMode->value : $this->sharingMode;
        $members['queueFamilyIndexCount'] = $this->queueFamilyIndexCount;
        $members['pQueueFamilyIndices'] = $this->pQueueFamilyIndices;
        $members['initialLayout'] = $this->initialLayout instanceof \BackedEnum ? $this->initialLayout->value : $this->initialLayout;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            imageType: (int) ($members['imageType'] ?? 0),
            format: (int) ($members['format'] ?? 0),
            extent: is_array($members['extent'] ?? null) ? VkExtent3D::fromArray($members['extent']) : null,
            mipLevels: (int) ($members['mipLevels'] ?? 0),
            arrayLayers: (int) ($members['arrayLayers'] ?? 0),
            samples: (int) ($members['samples'] ?? 0),
            tiling: (int) ($members['tiling'] ?? 0),
            usage: (int) ($members['usage'] ?? 0),
            sharingMode: (int) ($members['sharingMode'] ?? 0),
            queueFamilyIndexCount: (int) ($members['queueFamilyIndexCount'] ?? 0),
            pQueueFamilyIndices: (int) ($members['pQueueFamilyIndices'] ?? 0),
            initialLayout: (int) ($members['initialLayout'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkImageCreateInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkImageCreateInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkImageCreateInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkImageCreateInfo::size();
    }
}
