<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkFormat;
use Jovian\Bindings\Vulkan\Enums\VkImageViewType;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkImageViewCreateInfo\VkImageViewCreateInfo as ExtVkImageViewCreateInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkImageViewCreateInfo">, 8 members.
 *
 * The typed shape of the array ExtVkImageViewCreateInfo::pack() takes and
 * ExtVkImageViewCreateInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkImageViewCreateInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::IMAGE_VIEW_CREATE_INFO,
        public int $pNext = 0,
        public int $flags = 0,
        public int $image = 0,
        public VkImageViewType|int $viewType = 0,
        public VkFormat|int $format = 0,
        public ?VkComponentMapping $components = null,
        public ?VkImageSubresourceRange $subresourceRange = null,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        $members['image'] = $this->image;
        $members['viewType'] = $this->viewType instanceof \BackedEnum ? $this->viewType->value : $this->viewType;
        $members['format'] = $this->format instanceof \BackedEnum ? $this->format->value : $this->format;
        if (! is_null($this->components)) {
            $members['components'] = $this->components->toArray();
        }
        if (! is_null($this->subresourceRange)) {
            $members['subresourceRange'] = $this->subresourceRange->toArray();
        }

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            image: (int) ($members['image'] ?? 0),
            viewType: (int) ($members['viewType'] ?? 0),
            format: (int) ($members['format'] ?? 0),
            components: is_array($members['components'] ?? null) ? VkComponentMapping::fromArray($members['components']) : null,
            subresourceRange: is_array($members['subresourceRange'] ?? null) ? VkImageSubresourceRange::fromArray($members['subresourceRange']) : null,
        );
    }

    public function pack(): int
    {
        return ExtVkImageViewCreateInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkImageViewCreateInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkImageViewCreateInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkImageViewCreateInfo::size();
    }
}
