<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkLayerProperties\VkLayerProperties as ExtVkLayerProperties;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkLayerProperties">, 4 members.
 *
 * The typed shape of the array ExtVkLayerProperties::pack() takes and
 * ExtVkLayerProperties::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkLayerProperties
{
    public function __construct(
        public string $layerName = '',
        public int $specVersion = 0,
        public int $implementationVersion = 0,
        public string $description = '',
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['layerName'] = $this->layerName;
        $members['specVersion'] = $this->specVersion;
        $members['implementationVersion'] = $this->implementationVersion;
        $members['description'] = $this->description;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            layerName: (string) ($members['layerName'] ?? ''),
            specVersion: (int) ($members['specVersion'] ?? 0),
            implementationVersion: (int) ($members['implementationVersion'] ?? 0),
            description: (string) ($members['description'] ?? ''),
        );
    }

    public function pack(): int
    {
        return ExtVkLayerProperties::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkLayerProperties::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkLayerProperties::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkLayerProperties::size();
    }
}
