<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkLayerSettingsCreateInfoEXT\VkLayerSettingsCreateInfoEXT as ExtVkLayerSettingsCreateInfoEXT;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkLayerSettingsCreateInfoEXT">, 4 members.
 *
 * The typed shape of the array ExtVkLayerSettingsCreateInfoEXT::pack() takes and
 * ExtVkLayerSettingsCreateInfoEXT::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkLayerSettingsCreateInfoEXT
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::LAYER_SETTINGS_CREATE_INFO_EXT,
        public int $pNext = 0,
        public int $settingCount = 0,
        public int $pSettings = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['settingCount'] = $this->settingCount;
        $members['pSettings'] = $this->pSettings;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            settingCount: (int) ($members['settingCount'] ?? 0),
            pSettings: (int) ($members['pSettings'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkLayerSettingsCreateInfoEXT::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkLayerSettingsCreateInfoEXT::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkLayerSettingsCreateInfoEXT::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkLayerSettingsCreateInfoEXT::size();
    }
}
