<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkMemoryDedicatedAllocateInfo\VkMemoryDedicatedAllocateInfo as ExtVkMemoryDedicatedAllocateInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkMemoryDedicatedAllocateInfo">, 4 members.
 *
 * The typed shape of the array ExtVkMemoryDedicatedAllocateInfo::pack() takes and
 * ExtVkMemoryDedicatedAllocateInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkMemoryDedicatedAllocateInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::MEMORY_DEDICATED_ALLOCATE_INFO,
        public int $pNext = 0,
        public int $image = 0,
        public int $buffer = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['image'] = $this->image;
        $members['buffer'] = $this->buffer;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            image: (int) ($members['image'] ?? 0),
            buffer: (int) ($members['buffer'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkMemoryDedicatedAllocateInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkMemoryDedicatedAllocateInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkMemoryDedicatedAllocateInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkMemoryDedicatedAllocateInfo::size();
    }
}
