<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkMemoryUnmapInfo\VkMemoryUnmapInfo as ExtVkMemoryUnmapInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkMemoryUnmapInfo">, 4 members.
 *
 * The typed shape of the array ExtVkMemoryUnmapInfo::pack() takes and
 * ExtVkMemoryUnmapInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkMemoryUnmapInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::MEMORY_UNMAP_INFO,
        public int $pNext = 0,
        public int $flags = 0,
        public int $memory = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        $members['memory'] = $this->memory;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            memory: (int) ($members['memory'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkMemoryUnmapInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkMemoryUnmapInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkMemoryUnmapInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkMemoryUnmapInfo::size();
    }
}
