<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkMemoryType\VkMemoryType as ExtVkMemoryType;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkMemoryType">, 2 members.
 *
 * The typed shape of the array ExtVkMemoryType::pack() takes and
 * ExtVkMemoryType::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkMemoryType
{
    public function __construct(
        public int $propertyFlags = 0,
        public int $heapIndex = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['propertyFlags'] = $this->propertyFlags;
        $members['heapIndex'] = $this->heapIndex;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            propertyFlags: (int) ($members['propertyFlags'] ?? 0),
            heapIndex: (int) ($members['heapIndex'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkMemoryType::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkMemoryType::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkMemoryType::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkMemoryType::size();
    }
}
