<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkPipelineRobustnessBufferBehavior;
use Jovian\Bindings\Vulkan\Enums\VkPipelineRobustnessImageBehavior;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceVulkan14Properties\VkPhysicalDeviceVulkan14Properties as ExtVkPhysicalDeviceVulkan14Properties;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceVulkan14Properties">, 27 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceVulkan14Properties::pack() takes and
 * ExtVkPhysicalDeviceVulkan14Properties::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceVulkan14Properties
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_VULKAN_1_4_PROPERTIES,
        public int $pNext = 0,
        public int $lineSubPixelPrecisionBits = 0,
        public int $maxVertexAttribDivisor = 0,
        public bool $supportsNonZeroFirstInstance = false,
        public int $maxPushDescriptors = 0,
        public bool $dynamicRenderingLocalReadDepthStencilAttachments = false,
        public bool $dynamicRenderingLocalReadMultisampledAttachments = false,
        public bool $earlyFragmentMultisampleCoverageAfterSampleCounting = false,
        public bool $earlyFragmentSampleMaskTestBeforeSampleCounting = false,
        public bool $depthStencilSwizzleOneSupport = false,
        public bool $polygonModePointSize = false,
        public bool $nonStrictSinglePixelWideLinesUseParallelogram = false,
        public bool $nonStrictWideLinesUseParallelogram = false,
        public bool $blockTexelViewCompatibleMultipleLayers = false,
        public int $maxCombinedImageSamplerDescriptorCount = 0,
        public bool $fragmentShadingRateClampCombinerInputs = false,
        public VkPipelineRobustnessBufferBehavior|int $defaultRobustnessStorageBuffers = 0,
        public VkPipelineRobustnessBufferBehavior|int $defaultRobustnessUniformBuffers = 0,
        public VkPipelineRobustnessBufferBehavior|int $defaultRobustnessVertexInputs = 0,
        public VkPipelineRobustnessImageBehavior|int $defaultRobustnessImages = 0,
        public int $copySrcLayoutCount = 0,
        public int $pCopySrcLayouts = 0,
        public int $copyDstLayoutCount = 0,
        public int $pCopyDstLayouts = 0,
        public array $optimalTilingLayoutUUID = [],
        public bool $identicalMemoryTypeRequirements = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['lineSubPixelPrecisionBits'] = $this->lineSubPixelPrecisionBits;
        $members['maxVertexAttribDivisor'] = $this->maxVertexAttribDivisor;
        $members['supportsNonZeroFirstInstance'] = $this->supportsNonZeroFirstInstance;
        $members['maxPushDescriptors'] = $this->maxPushDescriptors;
        $members['dynamicRenderingLocalReadDepthStencilAttachments'] = $this->dynamicRenderingLocalReadDepthStencilAttachments;
        $members['dynamicRenderingLocalReadMultisampledAttachments'] = $this->dynamicRenderingLocalReadMultisampledAttachments;
        $members['earlyFragmentMultisampleCoverageAfterSampleCounting'] = $this->earlyFragmentMultisampleCoverageAfterSampleCounting;
        $members['earlyFragmentSampleMaskTestBeforeSampleCounting'] = $this->earlyFragmentSampleMaskTestBeforeSampleCounting;
        $members['depthStencilSwizzleOneSupport'] = $this->depthStencilSwizzleOneSupport;
        $members['polygonModePointSize'] = $this->polygonModePointSize;
        $members['nonStrictSinglePixelWideLinesUseParallelogram'] = $this->nonStrictSinglePixelWideLinesUseParallelogram;
        $members['nonStrictWideLinesUseParallelogram'] = $this->nonStrictWideLinesUseParallelogram;
        $members['blockTexelViewCompatibleMultipleLayers'] = $this->blockTexelViewCompatibleMultipleLayers;
        $members['maxCombinedImageSamplerDescriptorCount'] = $this->maxCombinedImageSamplerDescriptorCount;
        $members['fragmentShadingRateClampCombinerInputs'] = $this->fragmentShadingRateClampCombinerInputs;
        $members['defaultRobustnessStorageBuffers'] = $this->defaultRobustnessStorageBuffers instanceof \BackedEnum ? $this->defaultRobustnessStorageBuffers->value : $this->defaultRobustnessStorageBuffers;
        $members['defaultRobustnessUniformBuffers'] = $this->defaultRobustnessUniformBuffers instanceof \BackedEnum ? $this->defaultRobustnessUniformBuffers->value : $this->defaultRobustnessUniformBuffers;
        $members['defaultRobustnessVertexInputs'] = $this->defaultRobustnessVertexInputs instanceof \BackedEnum ? $this->defaultRobustnessVertexInputs->value : $this->defaultRobustnessVertexInputs;
        $members['defaultRobustnessImages'] = $this->defaultRobustnessImages instanceof \BackedEnum ? $this->defaultRobustnessImages->value : $this->defaultRobustnessImages;
        $members['copySrcLayoutCount'] = $this->copySrcLayoutCount;
        $members['pCopySrcLayouts'] = $this->pCopySrcLayouts;
        $members['copyDstLayoutCount'] = $this->copyDstLayoutCount;
        $members['pCopyDstLayouts'] = $this->pCopyDstLayouts;
        $members['optimalTilingLayoutUUID'] = $this->optimalTilingLayoutUUID;
        $members['identicalMemoryTypeRequirements'] = $this->identicalMemoryTypeRequirements;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            lineSubPixelPrecisionBits: (int) ($members['lineSubPixelPrecisionBits'] ?? 0),
            maxVertexAttribDivisor: (int) ($members['maxVertexAttribDivisor'] ?? 0),
            supportsNonZeroFirstInstance: (bool) ($members['supportsNonZeroFirstInstance'] ?? false),
            maxPushDescriptors: (int) ($members['maxPushDescriptors'] ?? 0),
            dynamicRenderingLocalReadDepthStencilAttachments: (bool) ($members['dynamicRenderingLocalReadDepthStencilAttachments'] ?? false),
            dynamicRenderingLocalReadMultisampledAttachments: (bool) ($members['dynamicRenderingLocalReadMultisampledAttachments'] ?? false),
            earlyFragmentMultisampleCoverageAfterSampleCounting: (bool) ($members['earlyFragmentMultisampleCoverageAfterSampleCounting'] ?? false),
            earlyFragmentSampleMaskTestBeforeSampleCounting: (bool) ($members['earlyFragmentSampleMaskTestBeforeSampleCounting'] ?? false),
            depthStencilSwizzleOneSupport: (bool) ($members['depthStencilSwizzleOneSupport'] ?? false),
            polygonModePointSize: (bool) ($members['polygonModePointSize'] ?? false),
            nonStrictSinglePixelWideLinesUseParallelogram: (bool) ($members['nonStrictSinglePixelWideLinesUseParallelogram'] ?? false),
            nonStrictWideLinesUseParallelogram: (bool) ($members['nonStrictWideLinesUseParallelogram'] ?? false),
            blockTexelViewCompatibleMultipleLayers: (bool) ($members['blockTexelViewCompatibleMultipleLayers'] ?? false),
            maxCombinedImageSamplerDescriptorCount: (int) ($members['maxCombinedImageSamplerDescriptorCount'] ?? 0),
            fragmentShadingRateClampCombinerInputs: (bool) ($members['fragmentShadingRateClampCombinerInputs'] ?? false),
            defaultRobustnessStorageBuffers: (int) ($members['defaultRobustnessStorageBuffers'] ?? 0),
            defaultRobustnessUniformBuffers: (int) ($members['defaultRobustnessUniformBuffers'] ?? 0),
            defaultRobustnessVertexInputs: (int) ($members['defaultRobustnessVertexInputs'] ?? 0),
            defaultRobustnessImages: (int) ($members['defaultRobustnessImages'] ?? 0),
            copySrcLayoutCount: (int) ($members['copySrcLayoutCount'] ?? 0),
            pCopySrcLayouts: (int) ($members['pCopySrcLayouts'] ?? 0),
            copyDstLayoutCount: (int) ($members['copyDstLayoutCount'] ?? 0),
            pCopyDstLayouts: (int) ($members['pCopyDstLayouts'] ?? 0),
            optimalTilingLayoutUUID: (array) ($members['optimalTilingLayoutUUID'] ?? []),
            identicalMemoryTypeRequirements: (bool) ($members['identicalMemoryTypeRequirements'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceVulkan14Properties::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceVulkan14Properties::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceVulkan14Properties::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceVulkan14Properties::size();
    }
}
