<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceMultiviewFeatures\VkPhysicalDeviceMultiviewFeatures as ExtVkPhysicalDeviceMultiviewFeatures;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceMultiviewFeatures">, 5 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceMultiviewFeatures::pack() takes and
 * ExtVkPhysicalDeviceMultiviewFeatures::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceMultiviewFeatures
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_MULTIVIEW_FEATURES,
        public int $pNext = 0,
        public bool $multiview = false,
        public bool $multiviewGeometryShader = false,
        public bool $multiviewTessellationShader = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['multiview'] = $this->multiview;
        $members['multiviewGeometryShader'] = $this->multiviewGeometryShader;
        $members['multiviewTessellationShader'] = $this->multiviewTessellationShader;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            multiview: (bool) ($members['multiview'] ?? false),
            multiviewGeometryShader: (bool) ($members['multiviewGeometryShader'] ?? false),
            multiviewTessellationShader: (bool) ($members['multiviewTessellationShader'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceMultiviewFeatures::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceMultiviewFeatures::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceMultiviewFeatures::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceMultiviewFeatures::size();
    }
}
