<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceIDProperties\VkPhysicalDeviceIDProperties as ExtVkPhysicalDeviceIDProperties;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceIDProperties">, 7 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceIDProperties::pack() takes and
 * ExtVkPhysicalDeviceIDProperties::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceIDProperties
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_ID_PROPERTIES,
        public int $pNext = 0,
        public array $deviceUUID = [],
        public array $driverUUID = [],
        public array $deviceLUID = [],
        public int $deviceNodeMask = 0,
        public bool $deviceLUIDValid = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['deviceUUID'] = $this->deviceUUID;
        $members['driverUUID'] = $this->driverUUID;
        $members['deviceLUID'] = $this->deviceLUID;
        $members['deviceNodeMask'] = $this->deviceNodeMask;
        $members['deviceLUIDValid'] = $this->deviceLUIDValid;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            deviceUUID: (array) ($members['deviceUUID'] ?? []),
            driverUUID: (array) ($members['driverUUID'] ?? []),
            deviceLUID: (array) ($members['deviceLUID'] ?? []),
            deviceNodeMask: (int) ($members['deviceNodeMask'] ?? 0),
            deviceLUIDValid: (bool) ($members['deviceLUIDValid'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceIDProperties::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceIDProperties::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceIDProperties::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceIDProperties::size();
    }
}
