<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceSamplerYcbcrConversionFeatures\VkPhysicalDeviceSamplerYcbcrConversionFeatures as ExtVkPhysicalDeviceSamplerYcbcrConversionFeatures;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceSamplerYcbcrConversionFeatures">, 3 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceSamplerYcbcrConversionFeatures::pack() takes and
 * ExtVkPhysicalDeviceSamplerYcbcrConversionFeatures::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceSamplerYcbcrConversionFeatures
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES,
        public int $pNext = 0,
        public bool $samplerYcbcrConversion = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['samplerYcbcrConversion'] = $this->samplerYcbcrConversion;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            samplerYcbcrConversion: (bool) ($members['samplerYcbcrConversion'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceSamplerYcbcrConversionFeatures::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceSamplerYcbcrConversionFeatures::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceSamplerYcbcrConversionFeatures::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceSamplerYcbcrConversionFeatures::size();
    }
}
