<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceMaintenance4Properties\VkPhysicalDeviceMaintenance4Properties as ExtVkPhysicalDeviceMaintenance4Properties;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceMaintenance4Properties">, 3 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceMaintenance4Properties::pack() takes and
 * ExtVkPhysicalDeviceMaintenance4Properties::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceMaintenance4Properties
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_MAINTENANCE_4_PROPERTIES,
        public int $pNext = 0,
        public int $maxBufferSize = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['maxBufferSize'] = $this->maxBufferSize;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            maxBufferSize: (int) ($members['maxBufferSize'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceMaintenance4Properties::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceMaintenance4Properties::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceMaintenance4Properties::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceMaintenance4Properties::size();
    }
}
