<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceHostImageCopyProperties\VkPhysicalDeviceHostImageCopyProperties as ExtVkPhysicalDeviceHostImageCopyProperties;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceHostImageCopyProperties">, 8 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceHostImageCopyProperties::pack() takes and
 * ExtVkPhysicalDeviceHostImageCopyProperties::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceHostImageCopyProperties
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_HOST_IMAGE_COPY_PROPERTIES,
        public int $pNext = 0,
        public int $copySrcLayoutCount = 0,
        public int $pCopySrcLayouts = 0,
        public int $copyDstLayoutCount = 0,
        public int $pCopyDstLayouts = 0,
        public array $optimalTilingLayoutUUID = [],
        public bool $identicalMemoryTypeRequirements = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['copySrcLayoutCount'] = $this->copySrcLayoutCount;
        $members['pCopySrcLayouts'] = $this->pCopySrcLayouts;
        $members['copyDstLayoutCount'] = $this->copyDstLayoutCount;
        $members['pCopyDstLayouts'] = $this->pCopyDstLayouts;
        $members['optimalTilingLayoutUUID'] = $this->optimalTilingLayoutUUID;
        $members['identicalMemoryTypeRequirements'] = $this->identicalMemoryTypeRequirements;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            copySrcLayoutCount: (int) ($members['copySrcLayoutCount'] ?? 0),
            pCopySrcLayouts: (int) ($members['pCopySrcLayouts'] ?? 0),
            copyDstLayoutCount: (int) ($members['copyDstLayoutCount'] ?? 0),
            pCopyDstLayouts: (int) ($members['pCopyDstLayouts'] ?? 0),
            optimalTilingLayoutUUID: (array) ($members['optimalTilingLayoutUUID'] ?? []),
            identicalMemoryTypeRequirements: (bool) ($members['identicalMemoryTypeRequirements'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceHostImageCopyProperties::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceHostImageCopyProperties::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceHostImageCopyProperties::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceHostImageCopyProperties::size();
    }
}
