<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceGlobalPriorityQueryFeatures\VkPhysicalDeviceGlobalPriorityQueryFeatures as ExtVkPhysicalDeviceGlobalPriorityQueryFeatures;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceGlobalPriorityQueryFeatures">, 3 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceGlobalPriorityQueryFeatures::pack() takes and
 * ExtVkPhysicalDeviceGlobalPriorityQueryFeatures::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceGlobalPriorityQueryFeatures
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_GLOBAL_PRIORITY_QUERY_FEATURES,
        public int $pNext = 0,
        public bool $globalPriorityQuery = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['globalPriorityQuery'] = $this->globalPriorityQuery;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            globalPriorityQuery: (bool) ($members['globalPriorityQuery'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceGlobalPriorityQueryFeatures::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceGlobalPriorityQueryFeatures::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceGlobalPriorityQueryFeatures::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceGlobalPriorityQueryFeatures::size();
    }
}
