<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceShaderFloat16Int8Features\VkPhysicalDeviceShaderFloat16Int8Features as ExtVkPhysicalDeviceShaderFloat16Int8Features;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceShaderFloat16Int8Features">, 4 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceShaderFloat16Int8Features::pack() takes and
 * ExtVkPhysicalDeviceShaderFloat16Int8Features::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceShaderFloat16Int8Features
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_SHADER_FLOAT16_INT8_FEATURES,
        public int $pNext = 0,
        public bool $shaderFloat16 = false,
        public bool $shaderInt8 = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['shaderFloat16'] = $this->shaderFloat16;
        $members['shaderInt8'] = $this->shaderInt8;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            shaderFloat16: (bool) ($members['shaderFloat16'] ?? false),
            shaderInt8: (bool) ($members['shaderInt8'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceShaderFloat16Int8Features::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceShaderFloat16Int8Features::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceShaderFloat16Int8Features::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceShaderFloat16Int8Features::size();
    }
}
