<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceShaderAtomicInt64Features\VkPhysicalDeviceShaderAtomicInt64Features as ExtVkPhysicalDeviceShaderAtomicInt64Features;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceShaderAtomicInt64Features">, 4 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceShaderAtomicInt64Features::pack() takes and
 * ExtVkPhysicalDeviceShaderAtomicInt64Features::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceShaderAtomicInt64Features
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_SHADER_ATOMIC_INT64_FEATURES,
        public int $pNext = 0,
        public bool $shaderBufferInt64Atomics = false,
        public bool $shaderSharedInt64Atomics = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['shaderBufferInt64Atomics'] = $this->shaderBufferInt64Atomics;
        $members['shaderSharedInt64Atomics'] = $this->shaderSharedInt64Atomics;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            shaderBufferInt64Atomics: (bool) ($members['shaderBufferInt64Atomics'] ?? false),
            shaderSharedInt64Atomics: (bool) ($members['shaderSharedInt64Atomics'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceShaderAtomicInt64Features::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceShaderAtomicInt64Features::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceShaderAtomicInt64Features::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceShaderAtomicInt64Features::size();
    }
}
