<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceFeatures2\VkPhysicalDeviceFeatures2 as ExtVkPhysicalDeviceFeatures2;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceFeatures2">, 3 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceFeatures2::pack() takes and
 * ExtVkPhysicalDeviceFeatures2::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceFeatures2
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_FEATURES_2,
        public int $pNext = 0,
        public ?VkPhysicalDeviceFeatures $features = null,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        if (! is_null($this->features)) {
            $members['features'] = $this->features->toArray();
        }

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            features: is_array($members['features'] ?? null) ? VkPhysicalDeviceFeatures::fromArray($members['features']) : null,
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceFeatures2::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceFeatures2::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceFeatures2::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceFeatures2::size();
    }
}
