<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDevicePushDescriptorProperties\VkPhysicalDevicePushDescriptorProperties as ExtVkPhysicalDevicePushDescriptorProperties;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDevicePushDescriptorProperties">, 3 members.
 *
 * The typed shape of the array ExtVkPhysicalDevicePushDescriptorProperties::pack() takes and
 * ExtVkPhysicalDevicePushDescriptorProperties::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDevicePushDescriptorProperties
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_PUSH_DESCRIPTOR_PROPERTIES,
        public int $pNext = 0,
        public int $maxPushDescriptors = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['maxPushDescriptors'] = $this->maxPushDescriptors;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            maxPushDescriptors: (int) ($members['maxPushDescriptors'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDevicePushDescriptorProperties::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDevicePushDescriptorProperties::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDevicePushDescriptorProperties::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDevicePushDescriptorProperties::size();
    }
}
