<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkExternalSemaphoreHandleTypeFlagBits;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceExternalSemaphoreInfo\VkPhysicalDeviceExternalSemaphoreInfo as ExtVkPhysicalDeviceExternalSemaphoreInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceExternalSemaphoreInfo">, 3 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceExternalSemaphoreInfo::pack() takes and
 * ExtVkPhysicalDeviceExternalSemaphoreInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceExternalSemaphoreInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_EXTERNAL_SEMAPHORE_INFO,
        public int $pNext = 0,
        public VkExternalSemaphoreHandleTypeFlagBits|int $handleType = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['handleType'] = $this->handleType instanceof \BackedEnum ? $this->handleType->value : $this->handleType;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            handleType: (int) ($members['handleType'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceExternalSemaphoreInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceExternalSemaphoreInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceExternalSemaphoreInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceExternalSemaphoreInfo::size();
    }
}
