<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceBufferDeviceAddressFeatures\VkPhysicalDeviceBufferDeviceAddressFeatures as ExtVkPhysicalDeviceBufferDeviceAddressFeatures;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceBufferDeviceAddressFeatures">, 5 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceBufferDeviceAddressFeatures::pack() takes and
 * ExtVkPhysicalDeviceBufferDeviceAddressFeatures::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceBufferDeviceAddressFeatures
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES,
        public int $pNext = 0,
        public bool $bufferDeviceAddress = false,
        public bool $bufferDeviceAddressCaptureReplay = false,
        public bool $bufferDeviceAddressMultiDevice = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['bufferDeviceAddress'] = $this->bufferDeviceAddress;
        $members['bufferDeviceAddressCaptureReplay'] = $this->bufferDeviceAddressCaptureReplay;
        $members['bufferDeviceAddressMultiDevice'] = $this->bufferDeviceAddressMultiDevice;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            bufferDeviceAddress: (bool) ($members['bufferDeviceAddress'] ?? false),
            bufferDeviceAddressCaptureReplay: (bool) ($members['bufferDeviceAddressCaptureReplay'] ?? false),
            bufferDeviceAddressMultiDevice: (bool) ($members['bufferDeviceAddressMultiDevice'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceBufferDeviceAddressFeatures::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceBufferDeviceAddressFeatures::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceBufferDeviceAddressFeatures::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceBufferDeviceAddressFeatures::size();
    }
}
