<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceDescriptorIndexingProperties\VkPhysicalDeviceDescriptorIndexingProperties as ExtVkPhysicalDeviceDescriptorIndexingProperties;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceDescriptorIndexingProperties">, 25 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceDescriptorIndexingProperties::pack() takes and
 * ExtVkPhysicalDeviceDescriptorIndexingProperties::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceDescriptorIndexingProperties
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_PROPERTIES,
        public int $pNext = 0,
        public int $maxUpdateAfterBindDescriptorsInAllPools = 0,
        public bool $shaderUniformBufferArrayNonUniformIndexingNative = false,
        public bool $shaderSampledImageArrayNonUniformIndexingNative = false,
        public bool $shaderStorageBufferArrayNonUniformIndexingNative = false,
        public bool $shaderStorageImageArrayNonUniformIndexingNative = false,
        public bool $shaderInputAttachmentArrayNonUniformIndexingNative = false,
        public bool $robustBufferAccessUpdateAfterBind = false,
        public bool $quadDivergentImplicitLod = false,
        public int $maxPerStageDescriptorUpdateAfterBindSamplers = 0,
        public int $maxPerStageDescriptorUpdateAfterBindUniformBuffers = 0,
        public int $maxPerStageDescriptorUpdateAfterBindStorageBuffers = 0,
        public int $maxPerStageDescriptorUpdateAfterBindSampledImages = 0,
        public int $maxPerStageDescriptorUpdateAfterBindStorageImages = 0,
        public int $maxPerStageDescriptorUpdateAfterBindInputAttachments = 0,
        public int $maxPerStageUpdateAfterBindResources = 0,
        public int $maxDescriptorSetUpdateAfterBindSamplers = 0,
        public int $maxDescriptorSetUpdateAfterBindUniformBuffers = 0,
        public int $maxDescriptorSetUpdateAfterBindUniformBuffersDynamic = 0,
        public int $maxDescriptorSetUpdateAfterBindStorageBuffers = 0,
        public int $maxDescriptorSetUpdateAfterBindStorageBuffersDynamic = 0,
        public int $maxDescriptorSetUpdateAfterBindSampledImages = 0,
        public int $maxDescriptorSetUpdateAfterBindStorageImages = 0,
        public int $maxDescriptorSetUpdateAfterBindInputAttachments = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['maxUpdateAfterBindDescriptorsInAllPools'] = $this->maxUpdateAfterBindDescriptorsInAllPools;
        $members['shaderUniformBufferArrayNonUniformIndexingNative'] = $this->shaderUniformBufferArrayNonUniformIndexingNative;
        $members['shaderSampledImageArrayNonUniformIndexingNative'] = $this->shaderSampledImageArrayNonUniformIndexingNative;
        $members['shaderStorageBufferArrayNonUniformIndexingNative'] = $this->shaderStorageBufferArrayNonUniformIndexingNative;
        $members['shaderStorageImageArrayNonUniformIndexingNative'] = $this->shaderStorageImageArrayNonUniformIndexingNative;
        $members['shaderInputAttachmentArrayNonUniformIndexingNative'] = $this->shaderInputAttachmentArrayNonUniformIndexingNative;
        $members['robustBufferAccessUpdateAfterBind'] = $this->robustBufferAccessUpdateAfterBind;
        $members['quadDivergentImplicitLod'] = $this->quadDivergentImplicitLod;
        $members['maxPerStageDescriptorUpdateAfterBindSamplers'] = $this->maxPerStageDescriptorUpdateAfterBindSamplers;
        $members['maxPerStageDescriptorUpdateAfterBindUniformBuffers'] = $this->maxPerStageDescriptorUpdateAfterBindUniformBuffers;
        $members['maxPerStageDescriptorUpdateAfterBindStorageBuffers'] = $this->maxPerStageDescriptorUpdateAfterBindStorageBuffers;
        $members['maxPerStageDescriptorUpdateAfterBindSampledImages'] = $this->maxPerStageDescriptorUpdateAfterBindSampledImages;
        $members['maxPerStageDescriptorUpdateAfterBindStorageImages'] = $this->maxPerStageDescriptorUpdateAfterBindStorageImages;
        $members['maxPerStageDescriptorUpdateAfterBindInputAttachments'] = $this->maxPerStageDescriptorUpdateAfterBindInputAttachments;
        $members['maxPerStageUpdateAfterBindResources'] = $this->maxPerStageUpdateAfterBindResources;
        $members['maxDescriptorSetUpdateAfterBindSamplers'] = $this->maxDescriptorSetUpdateAfterBindSamplers;
        $members['maxDescriptorSetUpdateAfterBindUniformBuffers'] = $this->maxDescriptorSetUpdateAfterBindUniformBuffers;
        $members['maxDescriptorSetUpdateAfterBindUniformBuffersDynamic'] = $this->maxDescriptorSetUpdateAfterBindUniformBuffersDynamic;
        $members['maxDescriptorSetUpdateAfterBindStorageBuffers'] = $this->maxDescriptorSetUpdateAfterBindStorageBuffers;
        $members['maxDescriptorSetUpdateAfterBindStorageBuffersDynamic'] = $this->maxDescriptorSetUpdateAfterBindStorageBuffersDynamic;
        $members['maxDescriptorSetUpdateAfterBindSampledImages'] = $this->maxDescriptorSetUpdateAfterBindSampledImages;
        $members['maxDescriptorSetUpdateAfterBindStorageImages'] = $this->maxDescriptorSetUpdateAfterBindStorageImages;
        $members['maxDescriptorSetUpdateAfterBindInputAttachments'] = $this->maxDescriptorSetUpdateAfterBindInputAttachments;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            maxUpdateAfterBindDescriptorsInAllPools: (int) ($members['maxUpdateAfterBindDescriptorsInAllPools'] ?? 0),
            shaderUniformBufferArrayNonUniformIndexingNative: (bool) ($members['shaderUniformBufferArrayNonUniformIndexingNative'] ?? false),
            shaderSampledImageArrayNonUniformIndexingNative: (bool) ($members['shaderSampledImageArrayNonUniformIndexingNative'] ?? false),
            shaderStorageBufferArrayNonUniformIndexingNative: (bool) ($members['shaderStorageBufferArrayNonUniformIndexingNative'] ?? false),
            shaderStorageImageArrayNonUniformIndexingNative: (bool) ($members['shaderStorageImageArrayNonUniformIndexingNative'] ?? false),
            shaderInputAttachmentArrayNonUniformIndexingNative: (bool) ($members['shaderInputAttachmentArrayNonUniformIndexingNative'] ?? false),
            robustBufferAccessUpdateAfterBind: (bool) ($members['robustBufferAccessUpdateAfterBind'] ?? false),
            quadDivergentImplicitLod: (bool) ($members['quadDivergentImplicitLod'] ?? false),
            maxPerStageDescriptorUpdateAfterBindSamplers: (int) ($members['maxPerStageDescriptorUpdateAfterBindSamplers'] ?? 0),
            maxPerStageDescriptorUpdateAfterBindUniformBuffers: (int) ($members['maxPerStageDescriptorUpdateAfterBindUniformBuffers'] ?? 0),
            maxPerStageDescriptorUpdateAfterBindStorageBuffers: (int) ($members['maxPerStageDescriptorUpdateAfterBindStorageBuffers'] ?? 0),
            maxPerStageDescriptorUpdateAfterBindSampledImages: (int) ($members['maxPerStageDescriptorUpdateAfterBindSampledImages'] ?? 0),
            maxPerStageDescriptorUpdateAfterBindStorageImages: (int) ($members['maxPerStageDescriptorUpdateAfterBindStorageImages'] ?? 0),
            maxPerStageDescriptorUpdateAfterBindInputAttachments: (int) ($members['maxPerStageDescriptorUpdateAfterBindInputAttachments'] ?? 0),
            maxPerStageUpdateAfterBindResources: (int) ($members['maxPerStageUpdateAfterBindResources'] ?? 0),
            maxDescriptorSetUpdateAfterBindSamplers: (int) ($members['maxDescriptorSetUpdateAfterBindSamplers'] ?? 0),
            maxDescriptorSetUpdateAfterBindUniformBuffers: (int) ($members['maxDescriptorSetUpdateAfterBindUniformBuffers'] ?? 0),
            maxDescriptorSetUpdateAfterBindUniformBuffersDynamic: (int) ($members['maxDescriptorSetUpdateAfterBindUniformBuffersDynamic'] ?? 0),
            maxDescriptorSetUpdateAfterBindStorageBuffers: (int) ($members['maxDescriptorSetUpdateAfterBindStorageBuffers'] ?? 0),
            maxDescriptorSetUpdateAfterBindStorageBuffersDynamic: (int) ($members['maxDescriptorSetUpdateAfterBindStorageBuffersDynamic'] ?? 0),
            maxDescriptorSetUpdateAfterBindSampledImages: (int) ($members['maxDescriptorSetUpdateAfterBindSampledImages'] ?? 0),
            maxDescriptorSetUpdateAfterBindStorageImages: (int) ($members['maxDescriptorSetUpdateAfterBindStorageImages'] ?? 0),
            maxDescriptorSetUpdateAfterBindInputAttachments: (int) ($members['maxDescriptorSetUpdateAfterBindInputAttachments'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceDescriptorIndexingProperties::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceDescriptorIndexingProperties::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceDescriptorIndexingProperties::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceDescriptorIndexingProperties::size();
    }
}
