<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceVulkan14Features\VkPhysicalDeviceVulkan14Features as ExtVkPhysicalDeviceVulkan14Features;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceVulkan14Features">, 23 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceVulkan14Features::pack() takes and
 * ExtVkPhysicalDeviceVulkan14Features::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceVulkan14Features
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_VULKAN_1_4_FEATURES,
        public int $pNext = 0,
        public bool $globalPriorityQuery = false,
        public bool $shaderSubgroupRotate = false,
        public bool $shaderSubgroupRotateClustered = false,
        public bool $shaderFloatControls2 = false,
        public bool $shaderExpectAssume = false,
        public bool $rectangularLines = false,
        public bool $bresenhamLines = false,
        public bool $smoothLines = false,
        public bool $stippledRectangularLines = false,
        public bool $stippledBresenhamLines = false,
        public bool $stippledSmoothLines = false,
        public bool $vertexAttributeInstanceRateDivisor = false,
        public bool $vertexAttributeInstanceRateZeroDivisor = false,
        public bool $indexTypeUint8 = false,
        public bool $dynamicRenderingLocalRead = false,
        public bool $maintenance5 = false,
        public bool $maintenance6 = false,
        public bool $pipelineProtectedAccess = false,
        public bool $pipelineRobustness = false,
        public bool $hostImageCopy = false,
        public bool $pushDescriptor = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['globalPriorityQuery'] = $this->globalPriorityQuery;
        $members['shaderSubgroupRotate'] = $this->shaderSubgroupRotate;
        $members['shaderSubgroupRotateClustered'] = $this->shaderSubgroupRotateClustered;
        $members['shaderFloatControls2'] = $this->shaderFloatControls2;
        $members['shaderExpectAssume'] = $this->shaderExpectAssume;
        $members['rectangularLines'] = $this->rectangularLines;
        $members['bresenhamLines'] = $this->bresenhamLines;
        $members['smoothLines'] = $this->smoothLines;
        $members['stippledRectangularLines'] = $this->stippledRectangularLines;
        $members['stippledBresenhamLines'] = $this->stippledBresenhamLines;
        $members['stippledSmoothLines'] = $this->stippledSmoothLines;
        $members['vertexAttributeInstanceRateDivisor'] = $this->vertexAttributeInstanceRateDivisor;
        $members['vertexAttributeInstanceRateZeroDivisor'] = $this->vertexAttributeInstanceRateZeroDivisor;
        $members['indexTypeUint8'] = $this->indexTypeUint8;
        $members['dynamicRenderingLocalRead'] = $this->dynamicRenderingLocalRead;
        $members['maintenance5'] = $this->maintenance5;
        $members['maintenance6'] = $this->maintenance6;
        $members['pipelineProtectedAccess'] = $this->pipelineProtectedAccess;
        $members['pipelineRobustness'] = $this->pipelineRobustness;
        $members['hostImageCopy'] = $this->hostImageCopy;
        $members['pushDescriptor'] = $this->pushDescriptor;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            globalPriorityQuery: (bool) ($members['globalPriorityQuery'] ?? false),
            shaderSubgroupRotate: (bool) ($members['shaderSubgroupRotate'] ?? false),
            shaderSubgroupRotateClustered: (bool) ($members['shaderSubgroupRotateClustered'] ?? false),
            shaderFloatControls2: (bool) ($members['shaderFloatControls2'] ?? false),
            shaderExpectAssume: (bool) ($members['shaderExpectAssume'] ?? false),
            rectangularLines: (bool) ($members['rectangularLines'] ?? false),
            bresenhamLines: (bool) ($members['bresenhamLines'] ?? false),
            smoothLines: (bool) ($members['smoothLines'] ?? false),
            stippledRectangularLines: (bool) ($members['stippledRectangularLines'] ?? false),
            stippledBresenhamLines: (bool) ($members['stippledBresenhamLines'] ?? false),
            stippledSmoothLines: (bool) ($members['stippledSmoothLines'] ?? false),
            vertexAttributeInstanceRateDivisor: (bool) ($members['vertexAttributeInstanceRateDivisor'] ?? false),
            vertexAttributeInstanceRateZeroDivisor: (bool) ($members['vertexAttributeInstanceRateZeroDivisor'] ?? false),
            indexTypeUint8: (bool) ($members['indexTypeUint8'] ?? false),
            dynamicRenderingLocalRead: (bool) ($members['dynamicRenderingLocalRead'] ?? false),
            maintenance5: (bool) ($members['maintenance5'] ?? false),
            maintenance6: (bool) ($members['maintenance6'] ?? false),
            pipelineProtectedAccess: (bool) ($members['pipelineProtectedAccess'] ?? false),
            pipelineRobustness: (bool) ($members['pipelineRobustness'] ?? false),
            hostImageCopy: (bool) ($members['hostImageCopy'] ?? false),
            pushDescriptor: (bool) ($members['pushDescriptor'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceVulkan14Features::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceVulkan14Features::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceVulkan14Features::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceVulkan14Features::size();
    }
}
