<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkDriverId;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceDriverProperties\VkPhysicalDeviceDriverProperties as ExtVkPhysicalDeviceDriverProperties;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceDriverProperties">, 6 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceDriverProperties::pack() takes and
 * ExtVkPhysicalDeviceDriverProperties::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceDriverProperties
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_DRIVER_PROPERTIES,
        public int $pNext = 0,
        public VkDriverId|int $driverID = 0,
        public string $driverName = '',
        public string $driverInfo = '',
        public ?VkConformanceVersion $conformanceVersion = null,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['driverID'] = $this->driverID instanceof \BackedEnum ? $this->driverID->value : $this->driverID;
        $members['driverName'] = $this->driverName;
        $members['driverInfo'] = $this->driverInfo;
        if (! is_null($this->conformanceVersion)) {
            $members['conformanceVersion'] = $this->conformanceVersion->toArray();
        }

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            driverID: (int) ($members['driverID'] ?? 0),
            driverName: (string) ($members['driverName'] ?? ''),
            driverInfo: (string) ($members['driverInfo'] ?? ''),
            conformanceVersion: is_array($members['conformanceVersion'] ?? null) ? VkConformanceVersion::fromArray($members['conformanceVersion']) : null,
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceDriverProperties::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceDriverProperties::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceDriverProperties::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceDriverProperties::size();
    }
}
