<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceLineRasterizationFeatures\VkPhysicalDeviceLineRasterizationFeatures as ExtVkPhysicalDeviceLineRasterizationFeatures;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceLineRasterizationFeatures">, 8 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceLineRasterizationFeatures::pack() takes and
 * ExtVkPhysicalDeviceLineRasterizationFeatures::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceLineRasterizationFeatures
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_LINE_RASTERIZATION_FEATURES,
        public int $pNext = 0,
        public bool $rectangularLines = false,
        public bool $bresenhamLines = false,
        public bool $smoothLines = false,
        public bool $stippledRectangularLines = false,
        public bool $stippledBresenhamLines = false,
        public bool $stippledSmoothLines = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['rectangularLines'] = $this->rectangularLines;
        $members['bresenhamLines'] = $this->bresenhamLines;
        $members['smoothLines'] = $this->smoothLines;
        $members['stippledRectangularLines'] = $this->stippledRectangularLines;
        $members['stippledBresenhamLines'] = $this->stippledBresenhamLines;
        $members['stippledSmoothLines'] = $this->stippledSmoothLines;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            rectangularLines: (bool) ($members['rectangularLines'] ?? false),
            bresenhamLines: (bool) ($members['bresenhamLines'] ?? false),
            smoothLines: (bool) ($members['smoothLines'] ?? false),
            stippledRectangularLines: (bool) ($members['stippledRectangularLines'] ?? false),
            stippledBresenhamLines: (bool) ($members['stippledBresenhamLines'] ?? false),
            stippledSmoothLines: (bool) ($members['stippledSmoothLines'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceLineRasterizationFeatures::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceLineRasterizationFeatures::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceLineRasterizationFeatures::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceLineRasterizationFeatures::size();
    }
}
