<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceShaderIntegerDotProductProperties\VkPhysicalDeviceShaderIntegerDotProductProperties as ExtVkPhysicalDeviceShaderIntegerDotProductProperties;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceShaderIntegerDotProductProperties">, 32 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceShaderIntegerDotProductProperties::pack() takes and
 * ExtVkPhysicalDeviceShaderIntegerDotProductProperties::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceShaderIntegerDotProductProperties
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_SHADER_INTEGER_DOT_PRODUCT_PROPERTIES,
        public int $pNext = 0,
        public bool $integerDotProduct8BitUnsignedAccelerated = false,
        public bool $integerDotProduct8BitSignedAccelerated = false,
        public bool $integerDotProduct8BitMixedSignednessAccelerated = false,
        public bool $integerDotProduct4x8BitPackedUnsignedAccelerated = false,
        public bool $integerDotProduct4x8BitPackedSignedAccelerated = false,
        public bool $integerDotProduct4x8BitPackedMixedSignednessAccelerated = false,
        public bool $integerDotProduct16BitUnsignedAccelerated = false,
        public bool $integerDotProduct16BitSignedAccelerated = false,
        public bool $integerDotProduct16BitMixedSignednessAccelerated = false,
        public bool $integerDotProduct32BitUnsignedAccelerated = false,
        public bool $integerDotProduct32BitSignedAccelerated = false,
        public bool $integerDotProduct32BitMixedSignednessAccelerated = false,
        public bool $integerDotProduct64BitUnsignedAccelerated = false,
        public bool $integerDotProduct64BitSignedAccelerated = false,
        public bool $integerDotProduct64BitMixedSignednessAccelerated = false,
        public bool $integerDotProductAccumulatingSaturating8BitUnsignedAccelerated = false,
        public bool $integerDotProductAccumulatingSaturating8BitSignedAccelerated = false,
        public bool $integerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated = false,
        public bool $integerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated = false,
        public bool $integerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated = false,
        public bool $integerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated = false,
        public bool $integerDotProductAccumulatingSaturating16BitUnsignedAccelerated = false,
        public bool $integerDotProductAccumulatingSaturating16BitSignedAccelerated = false,
        public bool $integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated = false,
        public bool $integerDotProductAccumulatingSaturating32BitUnsignedAccelerated = false,
        public bool $integerDotProductAccumulatingSaturating32BitSignedAccelerated = false,
        public bool $integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated = false,
        public bool $integerDotProductAccumulatingSaturating64BitUnsignedAccelerated = false,
        public bool $integerDotProductAccumulatingSaturating64BitSignedAccelerated = false,
        public bool $integerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['integerDotProduct8BitUnsignedAccelerated'] = $this->integerDotProduct8BitUnsignedAccelerated;
        $members['integerDotProduct8BitSignedAccelerated'] = $this->integerDotProduct8BitSignedAccelerated;
        $members['integerDotProduct8BitMixedSignednessAccelerated'] = $this->integerDotProduct8BitMixedSignednessAccelerated;
        $members['integerDotProduct4x8BitPackedUnsignedAccelerated'] = $this->integerDotProduct4x8BitPackedUnsignedAccelerated;
        $members['integerDotProduct4x8BitPackedSignedAccelerated'] = $this->integerDotProduct4x8BitPackedSignedAccelerated;
        $members['integerDotProduct4x8BitPackedMixedSignednessAccelerated'] = $this->integerDotProduct4x8BitPackedMixedSignednessAccelerated;
        $members['integerDotProduct16BitUnsignedAccelerated'] = $this->integerDotProduct16BitUnsignedAccelerated;
        $members['integerDotProduct16BitSignedAccelerated'] = $this->integerDotProduct16BitSignedAccelerated;
        $members['integerDotProduct16BitMixedSignednessAccelerated'] = $this->integerDotProduct16BitMixedSignednessAccelerated;
        $members['integerDotProduct32BitUnsignedAccelerated'] = $this->integerDotProduct32BitUnsignedAccelerated;
        $members['integerDotProduct32BitSignedAccelerated'] = $this->integerDotProduct32BitSignedAccelerated;
        $members['integerDotProduct32BitMixedSignednessAccelerated'] = $this->integerDotProduct32BitMixedSignednessAccelerated;
        $members['integerDotProduct64BitUnsignedAccelerated'] = $this->integerDotProduct64BitUnsignedAccelerated;
        $members['integerDotProduct64BitSignedAccelerated'] = $this->integerDotProduct64BitSignedAccelerated;
        $members['integerDotProduct64BitMixedSignednessAccelerated'] = $this->integerDotProduct64BitMixedSignednessAccelerated;
        $members['integerDotProductAccumulatingSaturating8BitUnsignedAccelerated'] = $this->integerDotProductAccumulatingSaturating8BitUnsignedAccelerated;
        $members['integerDotProductAccumulatingSaturating8BitSignedAccelerated'] = $this->integerDotProductAccumulatingSaturating8BitSignedAccelerated;
        $members['integerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated'] = $this->integerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated;
        $members['integerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated'] = $this->integerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated;
        $members['integerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated'] = $this->integerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated;
        $members['integerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated'] = $this->integerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated;
        $members['integerDotProductAccumulatingSaturating16BitUnsignedAccelerated'] = $this->integerDotProductAccumulatingSaturating16BitUnsignedAccelerated;
        $members['integerDotProductAccumulatingSaturating16BitSignedAccelerated'] = $this->integerDotProductAccumulatingSaturating16BitSignedAccelerated;
        $members['integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated'] = $this->integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated;
        $members['integerDotProductAccumulatingSaturating32BitUnsignedAccelerated'] = $this->integerDotProductAccumulatingSaturating32BitUnsignedAccelerated;
        $members['integerDotProductAccumulatingSaturating32BitSignedAccelerated'] = $this->integerDotProductAccumulatingSaturating32BitSignedAccelerated;
        $members['integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated'] = $this->integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated;
        $members['integerDotProductAccumulatingSaturating64BitUnsignedAccelerated'] = $this->integerDotProductAccumulatingSaturating64BitUnsignedAccelerated;
        $members['integerDotProductAccumulatingSaturating64BitSignedAccelerated'] = $this->integerDotProductAccumulatingSaturating64BitSignedAccelerated;
        $members['integerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated'] = $this->integerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            integerDotProduct8BitUnsignedAccelerated: (bool) ($members['integerDotProduct8BitUnsignedAccelerated'] ?? false),
            integerDotProduct8BitSignedAccelerated: (bool) ($members['integerDotProduct8BitSignedAccelerated'] ?? false),
            integerDotProduct8BitMixedSignednessAccelerated: (bool) ($members['integerDotProduct8BitMixedSignednessAccelerated'] ?? false),
            integerDotProduct4x8BitPackedUnsignedAccelerated: (bool) ($members['integerDotProduct4x8BitPackedUnsignedAccelerated'] ?? false),
            integerDotProduct4x8BitPackedSignedAccelerated: (bool) ($members['integerDotProduct4x8BitPackedSignedAccelerated'] ?? false),
            integerDotProduct4x8BitPackedMixedSignednessAccelerated: (bool) ($members['integerDotProduct4x8BitPackedMixedSignednessAccelerated'] ?? false),
            integerDotProduct16BitUnsignedAccelerated: (bool) ($members['integerDotProduct16BitUnsignedAccelerated'] ?? false),
            integerDotProduct16BitSignedAccelerated: (bool) ($members['integerDotProduct16BitSignedAccelerated'] ?? false),
            integerDotProduct16BitMixedSignednessAccelerated: (bool) ($members['integerDotProduct16BitMixedSignednessAccelerated'] ?? false),
            integerDotProduct32BitUnsignedAccelerated: (bool) ($members['integerDotProduct32BitUnsignedAccelerated'] ?? false),
            integerDotProduct32BitSignedAccelerated: (bool) ($members['integerDotProduct32BitSignedAccelerated'] ?? false),
            integerDotProduct32BitMixedSignednessAccelerated: (bool) ($members['integerDotProduct32BitMixedSignednessAccelerated'] ?? false),
            integerDotProduct64BitUnsignedAccelerated: (bool) ($members['integerDotProduct64BitUnsignedAccelerated'] ?? false),
            integerDotProduct64BitSignedAccelerated: (bool) ($members['integerDotProduct64BitSignedAccelerated'] ?? false),
            integerDotProduct64BitMixedSignednessAccelerated: (bool) ($members['integerDotProduct64BitMixedSignednessAccelerated'] ?? false),
            integerDotProductAccumulatingSaturating8BitUnsignedAccelerated: (bool) ($members['integerDotProductAccumulatingSaturating8BitUnsignedAccelerated'] ?? false),
            integerDotProductAccumulatingSaturating8BitSignedAccelerated: (bool) ($members['integerDotProductAccumulatingSaturating8BitSignedAccelerated'] ?? false),
            integerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated: (bool) ($members['integerDotProductAccumulatingSaturating8BitMixedSignednessAccelerated'] ?? false),
            integerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated: (bool) ($members['integerDotProductAccumulatingSaturating4x8BitPackedUnsignedAccelerated'] ?? false),
            integerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated: (bool) ($members['integerDotProductAccumulatingSaturating4x8BitPackedSignedAccelerated'] ?? false),
            integerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated: (bool) ($members['integerDotProductAccumulatingSaturating4x8BitPackedMixedSignednessAccelerated'] ?? false),
            integerDotProductAccumulatingSaturating16BitUnsignedAccelerated: (bool) ($members['integerDotProductAccumulatingSaturating16BitUnsignedAccelerated'] ?? false),
            integerDotProductAccumulatingSaturating16BitSignedAccelerated: (bool) ($members['integerDotProductAccumulatingSaturating16BitSignedAccelerated'] ?? false),
            integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated: (bool) ($members['integerDotProductAccumulatingSaturating16BitMixedSignednessAccelerated'] ?? false),
            integerDotProductAccumulatingSaturating32BitUnsignedAccelerated: (bool) ($members['integerDotProductAccumulatingSaturating32BitUnsignedAccelerated'] ?? false),
            integerDotProductAccumulatingSaturating32BitSignedAccelerated: (bool) ($members['integerDotProductAccumulatingSaturating32BitSignedAccelerated'] ?? false),
            integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated: (bool) ($members['integerDotProductAccumulatingSaturating32BitMixedSignednessAccelerated'] ?? false),
            integerDotProductAccumulatingSaturating64BitUnsignedAccelerated: (bool) ($members['integerDotProductAccumulatingSaturating64BitUnsignedAccelerated'] ?? false),
            integerDotProductAccumulatingSaturating64BitSignedAccelerated: (bool) ($members['integerDotProductAccumulatingSaturating64BitSignedAccelerated'] ?? false),
            integerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated: (bool) ($members['integerDotProductAccumulatingSaturating64BitMixedSignednessAccelerated'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceShaderIntegerDotProductProperties::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceShaderIntegerDotProductProperties::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceShaderIntegerDotProductProperties::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceShaderIntegerDotProductProperties::size();
    }
}
