<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceVulkan13Features\VkPhysicalDeviceVulkan13Features as ExtVkPhysicalDeviceVulkan13Features;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceVulkan13Features">, 17 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceVulkan13Features::pack() takes and
 * ExtVkPhysicalDeviceVulkan13Features::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceVulkan13Features
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_VULKAN_1_3_FEATURES,
        public int $pNext = 0,
        public bool $robustImageAccess = false,
        public bool $inlineUniformBlock = false,
        public bool $descriptorBindingInlineUniformBlockUpdateAfterBind = false,
        public bool $pipelineCreationCacheControl = false,
        public bool $privateData = false,
        public bool $shaderDemoteToHelperInvocation = false,
        public bool $shaderTerminateInvocation = false,
        public bool $subgroupSizeControl = false,
        public bool $computeFullSubgroups = false,
        public bool $synchronization2 = false,
        public bool $textureCompressionASTC_HDR = false,
        public bool $shaderZeroInitializeWorkgroupMemory = false,
        public bool $dynamicRendering = false,
        public bool $shaderIntegerDotProduct = false,
        public bool $maintenance4 = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['robustImageAccess'] = $this->robustImageAccess;
        $members['inlineUniformBlock'] = $this->inlineUniformBlock;
        $members['descriptorBindingInlineUniformBlockUpdateAfterBind'] = $this->descriptorBindingInlineUniformBlockUpdateAfterBind;
        $members['pipelineCreationCacheControl'] = $this->pipelineCreationCacheControl;
        $members['privateData'] = $this->privateData;
        $members['shaderDemoteToHelperInvocation'] = $this->shaderDemoteToHelperInvocation;
        $members['shaderTerminateInvocation'] = $this->shaderTerminateInvocation;
        $members['subgroupSizeControl'] = $this->subgroupSizeControl;
        $members['computeFullSubgroups'] = $this->computeFullSubgroups;
        $members['synchronization2'] = $this->synchronization2;
        $members['textureCompressionASTC_HDR'] = $this->textureCompressionASTC_HDR;
        $members['shaderZeroInitializeWorkgroupMemory'] = $this->shaderZeroInitializeWorkgroupMemory;
        $members['dynamicRendering'] = $this->dynamicRendering;
        $members['shaderIntegerDotProduct'] = $this->shaderIntegerDotProduct;
        $members['maintenance4'] = $this->maintenance4;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            robustImageAccess: (bool) ($members['robustImageAccess'] ?? false),
            inlineUniformBlock: (bool) ($members['inlineUniformBlock'] ?? false),
            descriptorBindingInlineUniformBlockUpdateAfterBind: (bool) ($members['descriptorBindingInlineUniformBlockUpdateAfterBind'] ?? false),
            pipelineCreationCacheControl: (bool) ($members['pipelineCreationCacheControl'] ?? false),
            privateData: (bool) ($members['privateData'] ?? false),
            shaderDemoteToHelperInvocation: (bool) ($members['shaderDemoteToHelperInvocation'] ?? false),
            shaderTerminateInvocation: (bool) ($members['shaderTerminateInvocation'] ?? false),
            subgroupSizeControl: (bool) ($members['subgroupSizeControl'] ?? false),
            computeFullSubgroups: (bool) ($members['computeFullSubgroups'] ?? false),
            synchronization2: (bool) ($members['synchronization2'] ?? false),
            textureCompressionASTC_HDR: (bool) ($members['textureCompressionASTC_HDR'] ?? false),
            shaderZeroInitializeWorkgroupMemory: (bool) ($members['shaderZeroInitializeWorkgroupMemory'] ?? false),
            dynamicRendering: (bool) ($members['dynamicRendering'] ?? false),
            shaderIntegerDotProduct: (bool) ($members['shaderIntegerDotProduct'] ?? false),
            maintenance4: (bool) ($members['maintenance4'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceVulkan13Features::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceVulkan13Features::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceVulkan13Features::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceVulkan13Features::size();
    }
}
