<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceGroupProperties\VkPhysicalDeviceGroupProperties as ExtVkPhysicalDeviceGroupProperties;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceGroupProperties">, 5 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceGroupProperties::pack() takes and
 * ExtVkPhysicalDeviceGroupProperties::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceGroupProperties
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_GROUP_PROPERTIES,
        public int $pNext = 0,
        public int $physicalDeviceCount = 0,
        public array $physicalDevices = [],
        public bool $subsetAllocation = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['physicalDeviceCount'] = $this->physicalDeviceCount;
        $members['physicalDevices'] = $this->physicalDevices;
        $members['subsetAllocation'] = $this->subsetAllocation;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            physicalDeviceCount: (int) ($members['physicalDeviceCount'] ?? 0),
            physicalDevices: (array) ($members['physicalDevices'] ?? []),
            subsetAllocation: (bool) ($members['subsetAllocation'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceGroupProperties::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceGroupProperties::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceGroupProperties::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceGroupProperties::size();
    }
}
