<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkPhysicalDeviceMemoryProperties\VkPhysicalDeviceMemoryProperties as ExtVkPhysicalDeviceMemoryProperties;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceMemoryProperties">, 4 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceMemoryProperties::pack() takes and
 * ExtVkPhysicalDeviceMemoryProperties::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceMemoryProperties
{
    public function __construct(
        public int $memoryTypeCount = 0,
        public array $memoryTypes = [],
        public int $memoryHeapCount = 0,
        public array $memoryHeaps = [],
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['memoryTypeCount'] = $this->memoryTypeCount;
        $members['memoryTypes'] = array_map(
            static fn (mixed $item): mixed => $item instanceof VkMemoryType ? $item->toArray() : $item,
            $this->memoryTypes,
        );
        $members['memoryHeapCount'] = $this->memoryHeapCount;
        $members['memoryHeaps'] = array_map(
            static fn (mixed $item): mixed => $item instanceof VkMemoryHeap ? $item->toArray() : $item,
            $this->memoryHeaps,
        );

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            memoryTypeCount: (int) ($members['memoryTypeCount'] ?? 0),
            memoryTypes: array_map(
                static fn (array $item): VkMemoryType => VkMemoryType::fromArray($item),
                (array) ($members['memoryTypes'] ?? []),
            ),
            memoryHeapCount: (int) ($members['memoryHeapCount'] ?? 0),
            memoryHeaps: array_map(
                static fn (array $item): VkMemoryHeap => VkMemoryHeap::fromArray($item),
                (array) ($members['memoryHeaps'] ?? []),
            ),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceMemoryProperties::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceMemoryProperties::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceMemoryProperties::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceMemoryProperties::size();
    }
}
