<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceMaintenance6Features\VkPhysicalDeviceMaintenance6Features as ExtVkPhysicalDeviceMaintenance6Features;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceMaintenance6Features">, 3 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceMaintenance6Features::pack() takes and
 * ExtVkPhysicalDeviceMaintenance6Features::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceMaintenance6Features
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_MAINTENANCE_6_FEATURES,
        public int $pNext = 0,
        public bool $maintenance6 = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['maintenance6'] = $this->maintenance6;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            maintenance6: (bool) ($members['maintenance6'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceMaintenance6Features::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceMaintenance6Features::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceMaintenance6Features::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceMaintenance6Features::size();
    }
}
