<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceTextureCompressionASTCHDRFeatures\VkPhysicalDeviceTextureCompressionASTCHDRFeatures as ExtVkPhysicalDeviceTextureCompressionASTCHDRFeatures;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceTextureCompressionASTCHDRFeatures">, 3 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceTextureCompressionASTCHDRFeatures::pack() takes and
 * ExtVkPhysicalDeviceTextureCompressionASTCHDRFeatures::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceTextureCompressionASTCHDRFeatures
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_TEXTURE_COMPRESSION_ASTC_HDR_FEATURES,
        public int $pNext = 0,
        public bool $textureCompressionASTC_HDR = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['textureCompressionASTC_HDR'] = $this->textureCompressionASTC_HDR;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            textureCompressionASTC_HDR: (bool) ($members['textureCompressionASTC_HDR'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceTextureCompressionASTCHDRFeatures::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceTextureCompressionASTCHDRFeatures::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceTextureCompressionASTCHDRFeatures::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceTextureCompressionASTCHDRFeatures::size();
    }
}
