<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDevicePipelineCreationCacheControlFeatures\VkPhysicalDevicePipelineCreationCacheControlFeatures as ExtVkPhysicalDevicePipelineCreationCacheControlFeatures;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDevicePipelineCreationCacheControlFeatures">, 3 members.
 *
 * The typed shape of the array ExtVkPhysicalDevicePipelineCreationCacheControlFeatures::pack() takes and
 * ExtVkPhysicalDevicePipelineCreationCacheControlFeatures::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDevicePipelineCreationCacheControlFeatures
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_PIPELINE_CREATION_CACHE_CONTROL_FEATURES,
        public int $pNext = 0,
        public bool $pipelineCreationCacheControl = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['pipelineCreationCacheControl'] = $this->pipelineCreationCacheControl;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            pipelineCreationCacheControl: (bool) ($members['pipelineCreationCacheControl'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDevicePipelineCreationCacheControlFeatures::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDevicePipelineCreationCacheControlFeatures::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDevicePipelineCreationCacheControlFeatures::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDevicePipelineCreationCacheControlFeatures::size();
    }
}
