<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDevice16BitStorageFeatures\VkPhysicalDevice16BitStorageFeatures as ExtVkPhysicalDevice16BitStorageFeatures;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDevice16BitStorageFeatures">, 6 members.
 *
 * The typed shape of the array ExtVkPhysicalDevice16BitStorageFeatures::pack() takes and
 * ExtVkPhysicalDevice16BitStorageFeatures::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDevice16BitStorageFeatures
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES,
        public int $pNext = 0,
        public bool $storageBuffer16BitAccess = false,
        public bool $uniformAndStorageBuffer16BitAccess = false,
        public bool $storagePushConstant16 = false,
        public bool $storageInputOutput16 = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['storageBuffer16BitAccess'] = $this->storageBuffer16BitAccess;
        $members['uniformAndStorageBuffer16BitAccess'] = $this->uniformAndStorageBuffer16BitAccess;
        $members['storagePushConstant16'] = $this->storagePushConstant16;
        $members['storageInputOutput16'] = $this->storageInputOutput16;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            storageBuffer16BitAccess: (bool) ($members['storageBuffer16BitAccess'] ?? false),
            uniformAndStorageBuffer16BitAccess: (bool) ($members['uniformAndStorageBuffer16BitAccess'] ?? false),
            storagePushConstant16: (bool) ($members['storagePushConstant16'] ?? false),
            storageInputOutput16: (bool) ($members['storageInputOutput16'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDevice16BitStorageFeatures::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDevice16BitStorageFeatures::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDevice16BitStorageFeatures::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDevice16BitStorageFeatures::size();
    }
}
