<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPhysicalDeviceVulkan12Features\VkPhysicalDeviceVulkan12Features as ExtVkPhysicalDeviceVulkan12Features;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPhysicalDeviceVulkan12Features">, 49 members.
 *
 * The typed shape of the array ExtVkPhysicalDeviceVulkan12Features::pack() takes and
 * ExtVkPhysicalDeviceVulkan12Features::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPhysicalDeviceVulkan12Features
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PHYSICAL_DEVICE_VULKAN_1_2_FEATURES,
        public int $pNext = 0,
        public bool $samplerMirrorClampToEdge = false,
        public bool $drawIndirectCount = false,
        public bool $storageBuffer8BitAccess = false,
        public bool $uniformAndStorageBuffer8BitAccess = false,
        public bool $storagePushConstant8 = false,
        public bool $shaderBufferInt64Atomics = false,
        public bool $shaderSharedInt64Atomics = false,
        public bool $shaderFloat16 = false,
        public bool $shaderInt8 = false,
        public bool $descriptorIndexing = false,
        public bool $shaderInputAttachmentArrayDynamicIndexing = false,
        public bool $shaderUniformTexelBufferArrayDynamicIndexing = false,
        public bool $shaderStorageTexelBufferArrayDynamicIndexing = false,
        public bool $shaderUniformBufferArrayNonUniformIndexing = false,
        public bool $shaderSampledImageArrayNonUniformIndexing = false,
        public bool $shaderStorageBufferArrayNonUniformIndexing = false,
        public bool $shaderStorageImageArrayNonUniformIndexing = false,
        public bool $shaderInputAttachmentArrayNonUniformIndexing = false,
        public bool $shaderUniformTexelBufferArrayNonUniformIndexing = false,
        public bool $shaderStorageTexelBufferArrayNonUniformIndexing = false,
        public bool $descriptorBindingUniformBufferUpdateAfterBind = false,
        public bool $descriptorBindingSampledImageUpdateAfterBind = false,
        public bool $descriptorBindingStorageImageUpdateAfterBind = false,
        public bool $descriptorBindingStorageBufferUpdateAfterBind = false,
        public bool $descriptorBindingUniformTexelBufferUpdateAfterBind = false,
        public bool $descriptorBindingStorageTexelBufferUpdateAfterBind = false,
        public bool $descriptorBindingUpdateUnusedWhilePending = false,
        public bool $descriptorBindingPartiallyBound = false,
        public bool $descriptorBindingVariableDescriptorCount = false,
        public bool $runtimeDescriptorArray = false,
        public bool $samplerFilterMinmax = false,
        public bool $scalarBlockLayout = false,
        public bool $imagelessFramebuffer = false,
        public bool $uniformBufferStandardLayout = false,
        public bool $shaderSubgroupExtendedTypes = false,
        public bool $separateDepthStencilLayouts = false,
        public bool $hostQueryReset = false,
        public bool $timelineSemaphore = false,
        public bool $bufferDeviceAddress = false,
        public bool $bufferDeviceAddressCaptureReplay = false,
        public bool $bufferDeviceAddressMultiDevice = false,
        public bool $vulkanMemoryModel = false,
        public bool $vulkanMemoryModelDeviceScope = false,
        public bool $vulkanMemoryModelAvailabilityVisibilityChains = false,
        public bool $shaderOutputViewportIndex = false,
        public bool $shaderOutputLayer = false,
        public bool $subgroupBroadcastDynamicId = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['samplerMirrorClampToEdge'] = $this->samplerMirrorClampToEdge;
        $members['drawIndirectCount'] = $this->drawIndirectCount;
        $members['storageBuffer8BitAccess'] = $this->storageBuffer8BitAccess;
        $members['uniformAndStorageBuffer8BitAccess'] = $this->uniformAndStorageBuffer8BitAccess;
        $members['storagePushConstant8'] = $this->storagePushConstant8;
        $members['shaderBufferInt64Atomics'] = $this->shaderBufferInt64Atomics;
        $members['shaderSharedInt64Atomics'] = $this->shaderSharedInt64Atomics;
        $members['shaderFloat16'] = $this->shaderFloat16;
        $members['shaderInt8'] = $this->shaderInt8;
        $members['descriptorIndexing'] = $this->descriptorIndexing;
        $members['shaderInputAttachmentArrayDynamicIndexing'] = $this->shaderInputAttachmentArrayDynamicIndexing;
        $members['shaderUniformTexelBufferArrayDynamicIndexing'] = $this->shaderUniformTexelBufferArrayDynamicIndexing;
        $members['shaderStorageTexelBufferArrayDynamicIndexing'] = $this->shaderStorageTexelBufferArrayDynamicIndexing;
        $members['shaderUniformBufferArrayNonUniformIndexing'] = $this->shaderUniformBufferArrayNonUniformIndexing;
        $members['shaderSampledImageArrayNonUniformIndexing'] = $this->shaderSampledImageArrayNonUniformIndexing;
        $members['shaderStorageBufferArrayNonUniformIndexing'] = $this->shaderStorageBufferArrayNonUniformIndexing;
        $members['shaderStorageImageArrayNonUniformIndexing'] = $this->shaderStorageImageArrayNonUniformIndexing;
        $members['shaderInputAttachmentArrayNonUniformIndexing'] = $this->shaderInputAttachmentArrayNonUniformIndexing;
        $members['shaderUniformTexelBufferArrayNonUniformIndexing'] = $this->shaderUniformTexelBufferArrayNonUniformIndexing;
        $members['shaderStorageTexelBufferArrayNonUniformIndexing'] = $this->shaderStorageTexelBufferArrayNonUniformIndexing;
        $members['descriptorBindingUniformBufferUpdateAfterBind'] = $this->descriptorBindingUniformBufferUpdateAfterBind;
        $members['descriptorBindingSampledImageUpdateAfterBind'] = $this->descriptorBindingSampledImageUpdateAfterBind;
        $members['descriptorBindingStorageImageUpdateAfterBind'] = $this->descriptorBindingStorageImageUpdateAfterBind;
        $members['descriptorBindingStorageBufferUpdateAfterBind'] = $this->descriptorBindingStorageBufferUpdateAfterBind;
        $members['descriptorBindingUniformTexelBufferUpdateAfterBind'] = $this->descriptorBindingUniformTexelBufferUpdateAfterBind;
        $members['descriptorBindingStorageTexelBufferUpdateAfterBind'] = $this->descriptorBindingStorageTexelBufferUpdateAfterBind;
        $members['descriptorBindingUpdateUnusedWhilePending'] = $this->descriptorBindingUpdateUnusedWhilePending;
        $members['descriptorBindingPartiallyBound'] = $this->descriptorBindingPartiallyBound;
        $members['descriptorBindingVariableDescriptorCount'] = $this->descriptorBindingVariableDescriptorCount;
        $members['runtimeDescriptorArray'] = $this->runtimeDescriptorArray;
        $members['samplerFilterMinmax'] = $this->samplerFilterMinmax;
        $members['scalarBlockLayout'] = $this->scalarBlockLayout;
        $members['imagelessFramebuffer'] = $this->imagelessFramebuffer;
        $members['uniformBufferStandardLayout'] = $this->uniformBufferStandardLayout;
        $members['shaderSubgroupExtendedTypes'] = $this->shaderSubgroupExtendedTypes;
        $members['separateDepthStencilLayouts'] = $this->separateDepthStencilLayouts;
        $members['hostQueryReset'] = $this->hostQueryReset;
        $members['timelineSemaphore'] = $this->timelineSemaphore;
        $members['bufferDeviceAddress'] = $this->bufferDeviceAddress;
        $members['bufferDeviceAddressCaptureReplay'] = $this->bufferDeviceAddressCaptureReplay;
        $members['bufferDeviceAddressMultiDevice'] = $this->bufferDeviceAddressMultiDevice;
        $members['vulkanMemoryModel'] = $this->vulkanMemoryModel;
        $members['vulkanMemoryModelDeviceScope'] = $this->vulkanMemoryModelDeviceScope;
        $members['vulkanMemoryModelAvailabilityVisibilityChains'] = $this->vulkanMemoryModelAvailabilityVisibilityChains;
        $members['shaderOutputViewportIndex'] = $this->shaderOutputViewportIndex;
        $members['shaderOutputLayer'] = $this->shaderOutputLayer;
        $members['subgroupBroadcastDynamicId'] = $this->subgroupBroadcastDynamicId;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            samplerMirrorClampToEdge: (bool) ($members['samplerMirrorClampToEdge'] ?? false),
            drawIndirectCount: (bool) ($members['drawIndirectCount'] ?? false),
            storageBuffer8BitAccess: (bool) ($members['storageBuffer8BitAccess'] ?? false),
            uniformAndStorageBuffer8BitAccess: (bool) ($members['uniformAndStorageBuffer8BitAccess'] ?? false),
            storagePushConstant8: (bool) ($members['storagePushConstant8'] ?? false),
            shaderBufferInt64Atomics: (bool) ($members['shaderBufferInt64Atomics'] ?? false),
            shaderSharedInt64Atomics: (bool) ($members['shaderSharedInt64Atomics'] ?? false),
            shaderFloat16: (bool) ($members['shaderFloat16'] ?? false),
            shaderInt8: (bool) ($members['shaderInt8'] ?? false),
            descriptorIndexing: (bool) ($members['descriptorIndexing'] ?? false),
            shaderInputAttachmentArrayDynamicIndexing: (bool) ($members['shaderInputAttachmentArrayDynamicIndexing'] ?? false),
            shaderUniformTexelBufferArrayDynamicIndexing: (bool) ($members['shaderUniformTexelBufferArrayDynamicIndexing'] ?? false),
            shaderStorageTexelBufferArrayDynamicIndexing: (bool) ($members['shaderStorageTexelBufferArrayDynamicIndexing'] ?? false),
            shaderUniformBufferArrayNonUniformIndexing: (bool) ($members['shaderUniformBufferArrayNonUniformIndexing'] ?? false),
            shaderSampledImageArrayNonUniformIndexing: (bool) ($members['shaderSampledImageArrayNonUniformIndexing'] ?? false),
            shaderStorageBufferArrayNonUniformIndexing: (bool) ($members['shaderStorageBufferArrayNonUniformIndexing'] ?? false),
            shaderStorageImageArrayNonUniformIndexing: (bool) ($members['shaderStorageImageArrayNonUniformIndexing'] ?? false),
            shaderInputAttachmentArrayNonUniformIndexing: (bool) ($members['shaderInputAttachmentArrayNonUniformIndexing'] ?? false),
            shaderUniformTexelBufferArrayNonUniformIndexing: (bool) ($members['shaderUniformTexelBufferArrayNonUniformIndexing'] ?? false),
            shaderStorageTexelBufferArrayNonUniformIndexing: (bool) ($members['shaderStorageTexelBufferArrayNonUniformIndexing'] ?? false),
            descriptorBindingUniformBufferUpdateAfterBind: (bool) ($members['descriptorBindingUniformBufferUpdateAfterBind'] ?? false),
            descriptorBindingSampledImageUpdateAfterBind: (bool) ($members['descriptorBindingSampledImageUpdateAfterBind'] ?? false),
            descriptorBindingStorageImageUpdateAfterBind: (bool) ($members['descriptorBindingStorageImageUpdateAfterBind'] ?? false),
            descriptorBindingStorageBufferUpdateAfterBind: (bool) ($members['descriptorBindingStorageBufferUpdateAfterBind'] ?? false),
            descriptorBindingUniformTexelBufferUpdateAfterBind: (bool) ($members['descriptorBindingUniformTexelBufferUpdateAfterBind'] ?? false),
            descriptorBindingStorageTexelBufferUpdateAfterBind: (bool) ($members['descriptorBindingStorageTexelBufferUpdateAfterBind'] ?? false),
            descriptorBindingUpdateUnusedWhilePending: (bool) ($members['descriptorBindingUpdateUnusedWhilePending'] ?? false),
            descriptorBindingPartiallyBound: (bool) ($members['descriptorBindingPartiallyBound'] ?? false),
            descriptorBindingVariableDescriptorCount: (bool) ($members['descriptorBindingVariableDescriptorCount'] ?? false),
            runtimeDescriptorArray: (bool) ($members['runtimeDescriptorArray'] ?? false),
            samplerFilterMinmax: (bool) ($members['samplerFilterMinmax'] ?? false),
            scalarBlockLayout: (bool) ($members['scalarBlockLayout'] ?? false),
            imagelessFramebuffer: (bool) ($members['imagelessFramebuffer'] ?? false),
            uniformBufferStandardLayout: (bool) ($members['uniformBufferStandardLayout'] ?? false),
            shaderSubgroupExtendedTypes: (bool) ($members['shaderSubgroupExtendedTypes'] ?? false),
            separateDepthStencilLayouts: (bool) ($members['separateDepthStencilLayouts'] ?? false),
            hostQueryReset: (bool) ($members['hostQueryReset'] ?? false),
            timelineSemaphore: (bool) ($members['timelineSemaphore'] ?? false),
            bufferDeviceAddress: (bool) ($members['bufferDeviceAddress'] ?? false),
            bufferDeviceAddressCaptureReplay: (bool) ($members['bufferDeviceAddressCaptureReplay'] ?? false),
            bufferDeviceAddressMultiDevice: (bool) ($members['bufferDeviceAddressMultiDevice'] ?? false),
            vulkanMemoryModel: (bool) ($members['vulkanMemoryModel'] ?? false),
            vulkanMemoryModelDeviceScope: (bool) ($members['vulkanMemoryModelDeviceScope'] ?? false),
            vulkanMemoryModelAvailabilityVisibilityChains: (bool) ($members['vulkanMemoryModelAvailabilityVisibilityChains'] ?? false),
            shaderOutputViewportIndex: (bool) ($members['shaderOutputViewportIndex'] ?? false),
            shaderOutputLayer: (bool) ($members['shaderOutputLayer'] ?? false),
            subgroupBroadcastDynamicId: (bool) ($members['subgroupBroadcastDynamicId'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPhysicalDeviceVulkan12Features::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPhysicalDeviceVulkan12Features::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPhysicalDeviceVulkan12Features::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPhysicalDeviceVulkan12Features::size();
    }
}
