<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkSampleCountFlagBits;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPipelineMultisampleStateCreateInfo\VkPipelineMultisampleStateCreateInfo as ExtVkPipelineMultisampleStateCreateInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPipelineMultisampleStateCreateInfo">, 9 members.
 *
 * The typed shape of the array ExtVkPipelineMultisampleStateCreateInfo::pack() takes and
 * ExtVkPipelineMultisampleStateCreateInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPipelineMultisampleStateCreateInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,
        public int $pNext = 0,
        public int $flags = 0,
        public VkSampleCountFlagBits|int $rasterizationSamples = 0,
        public bool $sampleShadingEnable = false,
        public float $minSampleShading = 0.0,
        public int $pSampleMask = 0,
        public bool $alphaToCoverageEnable = false,
        public bool $alphaToOneEnable = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        $members['rasterizationSamples'] = $this->rasterizationSamples instanceof \BackedEnum ? $this->rasterizationSamples->value : $this->rasterizationSamples;
        $members['sampleShadingEnable'] = $this->sampleShadingEnable;
        $members['minSampleShading'] = $this->minSampleShading;
        $members['pSampleMask'] = $this->pSampleMask;
        $members['alphaToCoverageEnable'] = $this->alphaToCoverageEnable;
        $members['alphaToOneEnable'] = $this->alphaToOneEnable;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            rasterizationSamples: (int) ($members['rasterizationSamples'] ?? 0),
            sampleShadingEnable: (bool) ($members['sampleShadingEnable'] ?? false),
            minSampleShading: (float) ($members['minSampleShading'] ?? 0.0),
            pSampleMask: (int) ($members['pSampleMask'] ?? 0),
            alphaToCoverageEnable: (bool) ($members['alphaToCoverageEnable'] ?? false),
            alphaToOneEnable: (bool) ($members['alphaToOneEnable'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkPipelineMultisampleStateCreateInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPipelineMultisampleStateCreateInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPipelineMultisampleStateCreateInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPipelineMultisampleStateCreateInfo::size();
    }
}
