<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkPipelineVertexInputStateCreateInfo\VkPipelineVertexInputStateCreateInfo as ExtVkPipelineVertexInputStateCreateInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPipelineVertexInputStateCreateInfo">, 7 members.
 *
 * The typed shape of the array ExtVkPipelineVertexInputStateCreateInfo::pack() takes and
 * ExtVkPipelineVertexInputStateCreateInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPipelineVertexInputStateCreateInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
        public int $pNext = 0,
        public int $flags = 0,
        public int $vertexBindingDescriptionCount = 0,
        public int $pVertexBindingDescriptions = 0,
        public int $vertexAttributeDescriptionCount = 0,
        public int $pVertexAttributeDescriptions = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        $members['vertexBindingDescriptionCount'] = $this->vertexBindingDescriptionCount;
        $members['pVertexBindingDescriptions'] = $this->pVertexBindingDescriptions;
        $members['vertexAttributeDescriptionCount'] = $this->vertexAttributeDescriptionCount;
        $members['pVertexAttributeDescriptions'] = $this->pVertexAttributeDescriptions;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            vertexBindingDescriptionCount: (int) ($members['vertexBindingDescriptionCount'] ?? 0),
            pVertexBindingDescriptions: (int) ($members['pVertexBindingDescriptions'] ?? 0),
            vertexAttributeDescriptionCount: (int) ($members['vertexAttributeDescriptionCount'] ?? 0),
            pVertexAttributeDescriptions: (int) ($members['pVertexAttributeDescriptions'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkPipelineVertexInputStateCreateInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPipelineVertexInputStateCreateInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPipelineVertexInputStateCreateInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPipelineVertexInputStateCreateInfo::size();
    }
}
