<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkPushConstantRange\VkPushConstantRange as ExtVkPushConstantRange;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkPushConstantRange">, 3 members.
 *
 * The typed shape of the array ExtVkPushConstantRange::pack() takes and
 * ExtVkPushConstantRange::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkPushConstantRange
{
    public function __construct(
        public int $stageFlags = 0,
        public int $offset = 0,
        public int $size = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['stageFlags'] = $this->stageFlags;
        $members['offset'] = $this->offset;
        $members['size'] = $this->size;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            stageFlags: (int) ($members['stageFlags'] ?? 0),
            offset: (int) ($members['offset'] ?? 0),
            size: (int) ($members['size'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkPushConstantRange::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkPushConstantRange::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkPushConstantRange::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkPushConstantRange::size();
    }
}
