<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkRect2D\VkRect2D as ExtVkRect2D;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkRect2D">, 2 members.
 *
 * The typed shape of the array ExtVkRect2D::pack() takes and
 * ExtVkRect2D::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkRect2D
{
    public function __construct(
        public ?VkOffset2D $offset = null,
        public ?VkExtent2D $extent = null,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        if (! is_null($this->offset)) {
            $members['offset'] = $this->offset->toArray();
        }
        if (! is_null($this->extent)) {
            $members['extent'] = $this->extent->toArray();
        }

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            offset: is_array($members['offset'] ?? null) ? VkOffset2D::fromArray($members['offset']) : null,
            extent: is_array($members['extent'] ?? null) ? VkExtent2D::fromArray($members['extent']) : null,
        );
    }

    public function pack(): int
    {
        return ExtVkRect2D::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkRect2D::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkRect2D::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkRect2D::size();
    }
}
