<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkRenderingInfo\VkRenderingInfo as ExtVkRenderingInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkRenderingInfo">, 10 members.
 *
 * The typed shape of the array ExtVkRenderingInfo::pack() takes and
 * ExtVkRenderingInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkRenderingInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::RENDERING_INFO,
        public int $pNext = 0,
        public int $flags = 0,
        public ?VkRect2D $renderArea = null,
        public int $layerCount = 0,
        public int $viewMask = 0,
        public int $colorAttachmentCount = 0,
        public int $pColorAttachments = 0,
        public int $pDepthAttachment = 0,
        public int $pStencilAttachment = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        if (! is_null($this->renderArea)) {
            $members['renderArea'] = $this->renderArea->toArray();
        }
        $members['layerCount'] = $this->layerCount;
        $members['viewMask'] = $this->viewMask;
        $members['colorAttachmentCount'] = $this->colorAttachmentCount;
        $members['pColorAttachments'] = $this->pColorAttachments;
        $members['pDepthAttachment'] = $this->pDepthAttachment;
        $members['pStencilAttachment'] = $this->pStencilAttachment;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            renderArea: is_array($members['renderArea'] ?? null) ? VkRect2D::fromArray($members['renderArea']) : null,
            layerCount: (int) ($members['layerCount'] ?? 0),
            viewMask: (int) ($members['viewMask'] ?? 0),
            colorAttachmentCount: (int) ($members['colorAttachmentCount'] ?? 0),
            pColorAttachments: (int) ($members['pColorAttachments'] ?? 0),
            pDepthAttachment: (int) ($members['pDepthAttachment'] ?? 0),
            pStencilAttachment: (int) ($members['pStencilAttachment'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkRenderingInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkRenderingInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkRenderingInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkRenderingInfo::size();
    }
}
