<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkRenderingInputAttachmentIndexInfo\VkRenderingInputAttachmentIndexInfo as ExtVkRenderingInputAttachmentIndexInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkRenderingInputAttachmentIndexInfo">, 6 members.
 *
 * The typed shape of the array ExtVkRenderingInputAttachmentIndexInfo::pack() takes and
 * ExtVkRenderingInputAttachmentIndexInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkRenderingInputAttachmentIndexInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::RENDERING_INPUT_ATTACHMENT_INDEX_INFO,
        public int $pNext = 0,
        public int $colorAttachmentCount = 0,
        public int $pColorAttachmentInputIndices = 0,
        public int $pDepthInputAttachmentIndex = 0,
        public int $pStencilInputAttachmentIndex = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['colorAttachmentCount'] = $this->colorAttachmentCount;
        $members['pColorAttachmentInputIndices'] = $this->pColorAttachmentInputIndices;
        $members['pDepthInputAttachmentIndex'] = $this->pDepthInputAttachmentIndex;
        $members['pStencilInputAttachmentIndex'] = $this->pStencilInputAttachmentIndex;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            colorAttachmentCount: (int) ($members['colorAttachmentCount'] ?? 0),
            pColorAttachmentInputIndices: (int) ($members['pColorAttachmentInputIndices'] ?? 0),
            pDepthInputAttachmentIndex: (int) ($members['pDepthInputAttachmentIndex'] ?? 0),
            pStencilInputAttachmentIndex: (int) ($members['pStencilInputAttachmentIndex'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkRenderingInputAttachmentIndexInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkRenderingInputAttachmentIndexInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkRenderingInputAttachmentIndexInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkRenderingInputAttachmentIndexInfo::size();
    }
}
