<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkAttachmentLoadOp;
use Jovian\Bindings\Vulkan\Enums\VkAttachmentStoreOp;
use Jovian\Bindings\Vulkan\Enums\VkImageLayout;
use Jovian\Bindings\Vulkan\Enums\VkResolveModeFlagBits;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkRenderingAttachmentInfo\VkRenderingAttachmentInfo as ExtVkRenderingAttachmentInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkRenderingAttachmentInfo">, 10 members.
 *
 * The typed shape of the array ExtVkRenderingAttachmentInfo::pack() takes and
 * ExtVkRenderingAttachmentInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkRenderingAttachmentInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::RENDERING_ATTACHMENT_INFO,
        public int $pNext = 0,
        public int $imageView = 0,
        public VkImageLayout|int $imageLayout = 0,
        public VkResolveModeFlagBits|int $resolveMode = 0,
        public int $resolveImageView = 0,
        public VkImageLayout|int $resolveImageLayout = 0,
        public VkAttachmentLoadOp|int $loadOp = 0,
        public VkAttachmentStoreOp|int $storeOp = 0,
        public ?VkClearValue $clearValue = null,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['imageView'] = $this->imageView;
        $members['imageLayout'] = $this->imageLayout instanceof \BackedEnum ? $this->imageLayout->value : $this->imageLayout;
        $members['resolveMode'] = $this->resolveMode instanceof \BackedEnum ? $this->resolveMode->value : $this->resolveMode;
        $members['resolveImageView'] = $this->resolveImageView;
        $members['resolveImageLayout'] = $this->resolveImageLayout instanceof \BackedEnum ? $this->resolveImageLayout->value : $this->resolveImageLayout;
        $members['loadOp'] = $this->loadOp instanceof \BackedEnum ? $this->loadOp->value : $this->loadOp;
        $members['storeOp'] = $this->storeOp instanceof \BackedEnum ? $this->storeOp->value : $this->storeOp;
        if (! is_null($this->clearValue)) {
            $members['clearValue'] = $this->clearValue->toArray();
        }

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            imageView: (int) ($members['imageView'] ?? 0),
            imageLayout: (int) ($members['imageLayout'] ?? 0),
            resolveMode: (int) ($members['resolveMode'] ?? 0),
            resolveImageView: (int) ($members['resolveImageView'] ?? 0),
            resolveImageLayout: (int) ($members['resolveImageLayout'] ?? 0),
            loadOp: (int) ($members['loadOp'] ?? 0),
            storeOp: (int) ($members['storeOp'] ?? 0),
            clearValue: is_array($members['clearValue'] ?? null) ? VkClearValue::fromArray($members['clearValue']) : null,
        );
    }

    public function pack(): int
    {
        return ExtVkRenderingAttachmentInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkRenderingAttachmentInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkRenderingAttachmentInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkRenderingAttachmentInfo::size();
    }
}
