<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkChromaLocation;
use Jovian\Bindings\Vulkan\Enums\VkFilter;
use Jovian\Bindings\Vulkan\Enums\VkFormat;
use Jovian\Bindings\Vulkan\Enums\VkSamplerYcbcrModelConversion;
use Jovian\Bindings\Vulkan\Enums\VkSamplerYcbcrRange;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkSamplerYcbcrConversionCreateInfo\VkSamplerYcbcrConversionCreateInfo as ExtVkSamplerYcbcrConversionCreateInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkSamplerYcbcrConversionCreateInfo">, 10 members.
 *
 * The typed shape of the array ExtVkSamplerYcbcrConversionCreateInfo::pack() takes and
 * ExtVkSamplerYcbcrConversionCreateInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkSamplerYcbcrConversionCreateInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::SAMPLER_YCBCR_CONVERSION_CREATE_INFO,
        public int $pNext = 0,
        public VkFormat|int $format = 0,
        public VkSamplerYcbcrModelConversion|int $ycbcrModel = 0,
        public VkSamplerYcbcrRange|int $ycbcrRange = 0,
        public ?VkComponentMapping $components = null,
        public VkChromaLocation|int $xChromaOffset = 0,
        public VkChromaLocation|int $yChromaOffset = 0,
        public VkFilter|int $chromaFilter = 0,
        public bool $forceExplicitReconstruction = false,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['format'] = $this->format instanceof \BackedEnum ? $this->format->value : $this->format;
        $members['ycbcrModel'] = $this->ycbcrModel instanceof \BackedEnum ? $this->ycbcrModel->value : $this->ycbcrModel;
        $members['ycbcrRange'] = $this->ycbcrRange instanceof \BackedEnum ? $this->ycbcrRange->value : $this->ycbcrRange;
        if (! is_null($this->components)) {
            $members['components'] = $this->components->toArray();
        }
        $members['xChromaOffset'] = $this->xChromaOffset instanceof \BackedEnum ? $this->xChromaOffset->value : $this->xChromaOffset;
        $members['yChromaOffset'] = $this->yChromaOffset instanceof \BackedEnum ? $this->yChromaOffset->value : $this->yChromaOffset;
        $members['chromaFilter'] = $this->chromaFilter instanceof \BackedEnum ? $this->chromaFilter->value : $this->chromaFilter;
        $members['forceExplicitReconstruction'] = $this->forceExplicitReconstruction;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            format: (int) ($members['format'] ?? 0),
            ycbcrModel: (int) ($members['ycbcrModel'] ?? 0),
            ycbcrRange: (int) ($members['ycbcrRange'] ?? 0),
            components: is_array($members['components'] ?? null) ? VkComponentMapping::fromArray($members['components']) : null,
            xChromaOffset: (int) ($members['xChromaOffset'] ?? 0),
            yChromaOffset: (int) ($members['yChromaOffset'] ?? 0),
            chromaFilter: (int) ($members['chromaFilter'] ?? 0),
            forceExplicitReconstruction: (bool) ($members['forceExplicitReconstruction'] ?? false),
        );
    }

    public function pack(): int
    {
        return ExtVkSamplerYcbcrConversionCreateInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkSamplerYcbcrConversionCreateInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkSamplerYcbcrConversionCreateInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkSamplerYcbcrConversionCreateInfo::size();
    }
}
