<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkSemaphoreType;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkSemaphoreTypeCreateInfo\VkSemaphoreTypeCreateInfo as ExtVkSemaphoreTypeCreateInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkSemaphoreTypeCreateInfo">, 4 members.
 *
 * The typed shape of the array ExtVkSemaphoreTypeCreateInfo::pack() takes and
 * ExtVkSemaphoreTypeCreateInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkSemaphoreTypeCreateInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::SEMAPHORE_TYPE_CREATE_INFO,
        public int $pNext = 0,
        public VkSemaphoreType|int $semaphoreType = 0,
        public int $initialValue = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['semaphoreType'] = $this->semaphoreType instanceof \BackedEnum ? $this->semaphoreType->value : $this->semaphoreType;
        $members['initialValue'] = $this->initialValue;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            semaphoreType: (int) ($members['semaphoreType'] ?? 0),
            initialValue: (int) ($members['initialValue'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkSemaphoreTypeCreateInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkSemaphoreTypeCreateInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkSemaphoreTypeCreateInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkSemaphoreTypeCreateInfo::size();
    }
}
