<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkSemaphoreWaitInfo\VkSemaphoreWaitInfo as ExtVkSemaphoreWaitInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkSemaphoreWaitInfo">, 6 members.
 *
 * The typed shape of the array ExtVkSemaphoreWaitInfo::pack() takes and
 * ExtVkSemaphoreWaitInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkSemaphoreWaitInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::SEMAPHORE_WAIT_INFO,
        public int $pNext = 0,
        public int $flags = 0,
        public int $semaphoreCount = 0,
        public int $pSemaphores = 0,
        public int $pValues = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        $members['semaphoreCount'] = $this->semaphoreCount;
        $members['pSemaphores'] = $this->pSemaphores;
        $members['pValues'] = $this->pValues;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            semaphoreCount: (int) ($members['semaphoreCount'] ?? 0),
            pSemaphores: (int) ($members['pSemaphores'] ?? 0),
            pValues: (int) ($members['pValues'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkSemaphoreWaitInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkSemaphoreWaitInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkSemaphoreWaitInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkSemaphoreWaitInfo::size();
    }
}
