<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkSparseImageMemoryRequirements\VkSparseImageMemoryRequirements as ExtVkSparseImageMemoryRequirements;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkSparseImageMemoryRequirements">, 5 members.
 *
 * The typed shape of the array ExtVkSparseImageMemoryRequirements::pack() takes and
 * ExtVkSparseImageMemoryRequirements::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkSparseImageMemoryRequirements
{
    public function __construct(
        public ?VkSparseImageFormatProperties $formatProperties = null,
        public int $imageMipTailFirstLod = 0,
        public int $imageMipTailSize = 0,
        public int $imageMipTailOffset = 0,
        public int $imageMipTailStride = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        if (! is_null($this->formatProperties)) {
            $members['formatProperties'] = $this->formatProperties->toArray();
        }
        $members['imageMipTailFirstLod'] = $this->imageMipTailFirstLod;
        $members['imageMipTailSize'] = $this->imageMipTailSize;
        $members['imageMipTailOffset'] = $this->imageMipTailOffset;
        $members['imageMipTailStride'] = $this->imageMipTailStride;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            formatProperties: is_array($members['formatProperties'] ?? null) ? VkSparseImageFormatProperties::fromArray($members['formatProperties']) : null,
            imageMipTailFirstLod: (int) ($members['imageMipTailFirstLod'] ?? 0),
            imageMipTailSize: (int) ($members['imageMipTailSize'] ?? 0),
            imageMipTailOffset: (int) ($members['imageMipTailOffset'] ?? 0),
            imageMipTailStride: (int) ($members['imageMipTailStride'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkSparseImageMemoryRequirements::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkSparseImageMemoryRequirements::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkSparseImageMemoryRequirements::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkSparseImageMemoryRequirements::size();
    }
}
