<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkSparseImageMemoryBindInfo\VkSparseImageMemoryBindInfo as ExtVkSparseImageMemoryBindInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkSparseImageMemoryBindInfo">, 3 members.
 *
 * The typed shape of the array ExtVkSparseImageMemoryBindInfo::pack() takes and
 * ExtVkSparseImageMemoryBindInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkSparseImageMemoryBindInfo
{
    public function __construct(
        public int $image = 0,
        public int $bindCount = 0,
        public int $pBinds = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['image'] = $this->image;
        $members['bindCount'] = $this->bindCount;
        $members['pBinds'] = $this->pBinds;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            image: (int) ($members['image'] ?? 0),
            bindCount: (int) ($members['bindCount'] ?? 0),
            pBinds: (int) ($members['pBinds'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkSparseImageMemoryBindInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkSparseImageMemoryBindInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkSparseImageMemoryBindInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkSparseImageMemoryBindInfo::size();
    }
}
