<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkSpecializationInfo\VkSpecializationInfo as ExtVkSpecializationInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkSpecializationInfo">, 4 members.
 *
 * The typed shape of the array ExtVkSpecializationInfo::pack() takes and
 * ExtVkSpecializationInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkSpecializationInfo
{
    public function __construct(
        public int $mapEntryCount = 0,
        public int $pMapEntries = 0,
        public int $dataSize = 0,
        public int $pData = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['mapEntryCount'] = $this->mapEntryCount;
        $members['pMapEntries'] = $this->pMapEntries;
        $members['dataSize'] = $this->dataSize;
        $members['pData'] = $this->pData;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            mapEntryCount: (int) ($members['mapEntryCount'] ?? 0),
            pMapEntries: (int) ($members['pMapEntries'] ?? 0),
            dataSize: (int) ($members['dataSize'] ?? 0),
            pData: (int) ($members['pData'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkSpecializationInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkSpecializationInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkSpecializationInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkSpecializationInfo::size();
    }
}
