<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkSparseImageMemoryBind\VkSparseImageMemoryBind as ExtVkSparseImageMemoryBind;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkSparseImageMemoryBind">, 6 members.
 *
 * The typed shape of the array ExtVkSparseImageMemoryBind::pack() takes and
 * ExtVkSparseImageMemoryBind::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkSparseImageMemoryBind
{
    public function __construct(
        public ?VkImageSubresource $subresource = null,
        public ?VkOffset3D $offset = null,
        public ?VkExtent3D $extent = null,
        public int $memory = 0,
        public int $memoryOffset = 0,
        public int $flags = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        if (! is_null($this->subresource)) {
            $members['subresource'] = $this->subresource->toArray();
        }
        if (! is_null($this->offset)) {
            $members['offset'] = $this->offset->toArray();
        }
        if (! is_null($this->extent)) {
            $members['extent'] = $this->extent->toArray();
        }
        $members['memory'] = $this->memory;
        $members['memoryOffset'] = $this->memoryOffset;
        $members['flags'] = $this->flags;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            subresource: is_array($members['subresource'] ?? null) ? VkImageSubresource::fromArray($members['subresource']) : null,
            offset: is_array($members['offset'] ?? null) ? VkOffset3D::fromArray($members['offset']) : null,
            extent: is_array($members['extent'] ?? null) ? VkExtent3D::fromArray($members['extent']) : null,
            memory: (int) ($members['memory'] ?? 0),
            memoryOffset: (int) ($members['memoryOffset'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkSparseImageMemoryBind::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkSparseImageMemoryBind::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkSparseImageMemoryBind::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkSparseImageMemoryBind::size();
    }
}
