<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkSpecializationMapEntry\VkSpecializationMapEntry as ExtVkSpecializationMapEntry;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkSpecializationMapEntry">, 3 members.
 *
 * The typed shape of the array ExtVkSpecializationMapEntry::pack() takes and
 * ExtVkSpecializationMapEntry::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkSpecializationMapEntry
{
    public function __construct(
        public int $constantID = 0,
        public int $offset = 0,
        public int $size = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['constantID'] = $this->constantID;
        $members['offset'] = $this->offset;
        $members['size'] = $this->size;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            constantID: (int) ($members['constantID'] ?? 0),
            offset: (int) ($members['offset'] ?? 0),
            size: (int) ($members['size'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkSpecializationMapEntry::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkSpecializationMapEntry::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkSpecializationMapEntry::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkSpecializationMapEntry::size();
    }
}
