<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkSparseImageMemoryRequirements2\VkSparseImageMemoryRequirements2 as ExtVkSparseImageMemoryRequirements2;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkSparseImageMemoryRequirements2">, 3 members.
 *
 * The typed shape of the array ExtVkSparseImageMemoryRequirements2::pack() takes and
 * ExtVkSparseImageMemoryRequirements2::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkSparseImageMemoryRequirements2
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::SPARSE_IMAGE_MEMORY_REQUIREMENTS_2,
        public int $pNext = 0,
        public ?VkSparseImageMemoryRequirements $memoryRequirements = null,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        if (! is_null($this->memoryRequirements)) {
            $members['memoryRequirements'] = $this->memoryRequirements->toArray();
        }

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            memoryRequirements: is_array($members['memoryRequirements'] ?? null) ? VkSparseImageMemoryRequirements::fromArray($members['memoryRequirements']) : null,
        );
    }

    public function pack(): int
    {
        return ExtVkSparseImageMemoryRequirements2::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkSparseImageMemoryRequirements2::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkSparseImageMemoryRequirements2::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkSparseImageMemoryRequirements2::size();
    }
}
