<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkCompareOp;
use Jovian\Bindings\Vulkan\Enums\VkStencilOp;
use Vulkan\Struct\VkStencilOpState\VkStencilOpState as ExtVkStencilOpState;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkStencilOpState">, 7 members.
 *
 * The typed shape of the array ExtVkStencilOpState::pack() takes and
 * ExtVkStencilOpState::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkStencilOpState
{
    public function __construct(
        public VkStencilOp|int $failOp = 0,
        public VkStencilOp|int $passOp = 0,
        public VkStencilOp|int $depthFailOp = 0,
        public VkCompareOp|int $compareOp = 0,
        public int $compareMask = 0,
        public int $writeMask = 0,
        public int $reference = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['failOp'] = $this->failOp instanceof \BackedEnum ? $this->failOp->value : $this->failOp;
        $members['passOp'] = $this->passOp instanceof \BackedEnum ? $this->passOp->value : $this->passOp;
        $members['depthFailOp'] = $this->depthFailOp instanceof \BackedEnum ? $this->depthFailOp->value : $this->depthFailOp;
        $members['compareOp'] = $this->compareOp instanceof \BackedEnum ? $this->compareOp->value : $this->compareOp;
        $members['compareMask'] = $this->compareMask;
        $members['writeMask'] = $this->writeMask;
        $members['reference'] = $this->reference;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            failOp: (int) ($members['failOp'] ?? 0),
            passOp: (int) ($members['passOp'] ?? 0),
            depthFailOp: (int) ($members['depthFailOp'] ?? 0),
            compareOp: (int) ($members['compareOp'] ?? 0),
            compareMask: (int) ($members['compareMask'] ?? 0),
            writeMask: (int) ($members['writeMask'] ?? 0),
            reference: (int) ($members['reference'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkStencilOpState::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkStencilOpState::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkStencilOpState::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkStencilOpState::size();
    }
}
