<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Jovian\Bindings\Vulkan\Enums\VkSubpassContents;
use Vulkan\Struct\VkSubpassBeginInfo\VkSubpassBeginInfo as ExtVkSubpassBeginInfo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkSubpassBeginInfo">, 3 members.
 *
 * The typed shape of the array ExtVkSubpassBeginInfo::pack() takes and
 * ExtVkSubpassBeginInfo::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkSubpassBeginInfo
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::SUBPASS_BEGIN_INFO,
        public int $pNext = 0,
        public VkSubpassContents|int $contents = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['contents'] = $this->contents instanceof \BackedEnum ? $this->contents->value : $this->contents;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            contents: (int) ($members['contents'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkSubpassBeginInfo::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkSubpassBeginInfo::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkSubpassBeginInfo::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkSubpassBeginInfo::size();
    }
}
