<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkSubpassDependency\VkSubpassDependency as ExtVkSubpassDependency;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkSubpassDependency">, 7 members.
 *
 * The typed shape of the array ExtVkSubpassDependency::pack() takes and
 * ExtVkSubpassDependency::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkSubpassDependency
{
    public function __construct(
        public int $srcSubpass = 0,
        public int $dstSubpass = 0,
        public int $srcStageMask = 0,
        public int $dstStageMask = 0,
        public int $srcAccessMask = 0,
        public int $dstAccessMask = 0,
        public int $dependencyFlags = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['srcSubpass'] = $this->srcSubpass;
        $members['dstSubpass'] = $this->dstSubpass;
        $members['srcStageMask'] = $this->srcStageMask;
        $members['dstStageMask'] = $this->dstStageMask;
        $members['srcAccessMask'] = $this->srcAccessMask;
        $members['dstAccessMask'] = $this->dstAccessMask;
        $members['dependencyFlags'] = $this->dependencyFlags;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            srcSubpass: (int) ($members['srcSubpass'] ?? 0),
            dstSubpass: (int) ($members['dstSubpass'] ?? 0),
            srcStageMask: (int) ($members['srcStageMask'] ?? 0),
            dstStageMask: (int) ($members['dstStageMask'] ?? 0),
            srcAccessMask: (int) ($members['srcAccessMask'] ?? 0),
            dstAccessMask: (int) ($members['dstAccessMask'] ?? 0),
            dependencyFlags: (int) ($members['dependencyFlags'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkSubpassDependency::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkSubpassDependency::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkSubpassDependency::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkSubpassDependency::size();
    }
}
