<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkResolveModeFlagBits;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkSubpassDescriptionDepthStencilResolve\VkSubpassDescriptionDepthStencilResolve as ExtVkSubpassDescriptionDepthStencilResolve;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkSubpassDescriptionDepthStencilResolve">, 5 members.
 *
 * The typed shape of the array ExtVkSubpassDescriptionDepthStencilResolve::pack() takes and
 * ExtVkSubpassDescriptionDepthStencilResolve::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkSubpassDescriptionDepthStencilResolve
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::SUBPASS_DESCRIPTION_DEPTH_STENCIL_RESOLVE,
        public int $pNext = 0,
        public VkResolveModeFlagBits|int $depthResolveMode = 0,
        public VkResolveModeFlagBits|int $stencilResolveMode = 0,
        public int $pDepthStencilResolveAttachment = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['depthResolveMode'] = $this->depthResolveMode instanceof \BackedEnum ? $this->depthResolveMode->value : $this->depthResolveMode;
        $members['stencilResolveMode'] = $this->stencilResolveMode instanceof \BackedEnum ? $this->stencilResolveMode->value : $this->stencilResolveMode;
        $members['pDepthStencilResolveAttachment'] = $this->pDepthStencilResolveAttachment;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            depthResolveMode: (int) ($members['depthResolveMode'] ?? 0),
            stencilResolveMode: (int) ($members['stencilResolveMode'] ?? 0),
            pDepthStencilResolveAttachment: (int) ($members['pDepthStencilResolveAttachment'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkSubpassDescriptionDepthStencilResolve::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkSubpassDescriptionDepthStencilResolve::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkSubpassDescriptionDepthStencilResolve::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkSubpassDescriptionDepthStencilResolve::size();
    }
}
