<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkSubpassDependency2\VkSubpassDependency2 as ExtVkSubpassDependency2;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkSubpassDependency2">, 10 members.
 *
 * The typed shape of the array ExtVkSubpassDependency2::pack() takes and
 * ExtVkSubpassDependency2::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkSubpassDependency2
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::SUBPASS_DEPENDENCY_2,
        public int $pNext = 0,
        public int $srcSubpass = 0,
        public int $dstSubpass = 0,
        public int $srcStageMask = 0,
        public int $dstStageMask = 0,
        public int $srcAccessMask = 0,
        public int $dstAccessMask = 0,
        public int $dependencyFlags = 0,
        public int $viewOffset = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['srcSubpass'] = $this->srcSubpass;
        $members['dstSubpass'] = $this->dstSubpass;
        $members['srcStageMask'] = $this->srcStageMask;
        $members['dstStageMask'] = $this->dstStageMask;
        $members['srcAccessMask'] = $this->srcAccessMask;
        $members['dstAccessMask'] = $this->dstAccessMask;
        $members['dependencyFlags'] = $this->dependencyFlags;
        $members['viewOffset'] = $this->viewOffset;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            srcSubpass: (int) ($members['srcSubpass'] ?? 0),
            dstSubpass: (int) ($members['dstSubpass'] ?? 0),
            srcStageMask: (int) ($members['srcStageMask'] ?? 0),
            dstStageMask: (int) ($members['dstStageMask'] ?? 0),
            srcAccessMask: (int) ($members['srcAccessMask'] ?? 0),
            dstAccessMask: (int) ($members['dstAccessMask'] ?? 0),
            dependencyFlags: (int) ($members['dependencyFlags'] ?? 0),
            viewOffset: (int) ($members['viewOffset'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkSubpassDependency2::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkSubpassDependency2::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkSubpassDependency2::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkSubpassDependency2::size();
    }
}
