<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkColorSpaceKHR;
use Jovian\Bindings\Vulkan\Enums\VkCompositeAlphaFlagBitsKHR;
use Jovian\Bindings\Vulkan\Enums\VkFormat;
use Jovian\Bindings\Vulkan\Enums\VkPresentModeKHR;
use Jovian\Bindings\Vulkan\Enums\VkSharingMode;
use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Jovian\Bindings\Vulkan\Enums\VkSurfaceTransformFlagBitsKHR;
use Vulkan\Struct\VkSwapchainCreateInfoKHR\VkSwapchainCreateInfoKHR as ExtVkSwapchainCreateInfoKHR;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkSwapchainCreateInfoKHR">, 18 members.
 *
 * The typed shape of the array ExtVkSwapchainCreateInfoKHR::pack() takes and
 * ExtVkSwapchainCreateInfoKHR::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkSwapchainCreateInfoKHR
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::SWAPCHAIN_CREATE_INFO_KHR,
        public int $pNext = 0,
        public int $flags = 0,
        public int $surface = 0,
        public int $minImageCount = 0,
        public VkFormat|int $imageFormat = 0,
        public VkColorSpaceKHR|int $imageColorSpace = 0,
        public ?VkExtent2D $imageExtent = null,
        public int $imageArrayLayers = 0,
        public int $imageUsage = 0,
        public VkSharingMode|int $imageSharingMode = 0,
        public int $queueFamilyIndexCount = 0,
        public int $pQueueFamilyIndices = 0,
        public VkSurfaceTransformFlagBitsKHR|int $preTransform = 0,
        public VkCompositeAlphaFlagBitsKHR|int $compositeAlpha = 0,
        public VkPresentModeKHR|int $presentMode = 0,
        public bool $clipped = false,
        public int $oldSwapchain = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        $members['surface'] = $this->surface;
        $members['minImageCount'] = $this->minImageCount;
        $members['imageFormat'] = $this->imageFormat instanceof \BackedEnum ? $this->imageFormat->value : $this->imageFormat;
        $members['imageColorSpace'] = $this->imageColorSpace instanceof \BackedEnum ? $this->imageColorSpace->value : $this->imageColorSpace;
        if (! is_null($this->imageExtent)) {
            $members['imageExtent'] = $this->imageExtent->toArray();
        }
        $members['imageArrayLayers'] = $this->imageArrayLayers;
        $members['imageUsage'] = $this->imageUsage;
        $members['imageSharingMode'] = $this->imageSharingMode instanceof \BackedEnum ? $this->imageSharingMode->value : $this->imageSharingMode;
        $members['queueFamilyIndexCount'] = $this->queueFamilyIndexCount;
        $members['pQueueFamilyIndices'] = $this->pQueueFamilyIndices;
        $members['preTransform'] = $this->preTransform instanceof \BackedEnum ? $this->preTransform->value : $this->preTransform;
        $members['compositeAlpha'] = $this->compositeAlpha instanceof \BackedEnum ? $this->compositeAlpha->value : $this->compositeAlpha;
        $members['presentMode'] = $this->presentMode instanceof \BackedEnum ? $this->presentMode->value : $this->presentMode;
        $members['clipped'] = $this->clipped;
        $members['oldSwapchain'] = $this->oldSwapchain;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            surface: (int) ($members['surface'] ?? 0),
            minImageCount: (int) ($members['minImageCount'] ?? 0),
            imageFormat: (int) ($members['imageFormat'] ?? 0),
            imageColorSpace: (int) ($members['imageColorSpace'] ?? 0),
            imageExtent: is_array($members['imageExtent'] ?? null) ? VkExtent2D::fromArray($members['imageExtent']) : null,
            imageArrayLayers: (int) ($members['imageArrayLayers'] ?? 0),
            imageUsage: (int) ($members['imageUsage'] ?? 0),
            imageSharingMode: (int) ($members['imageSharingMode'] ?? 0),
            queueFamilyIndexCount: (int) ($members['queueFamilyIndexCount'] ?? 0),
            pQueueFamilyIndices: (int) ($members['pQueueFamilyIndices'] ?? 0),
            preTransform: (int) ($members['preTransform'] ?? 0),
            compositeAlpha: (int) ($members['compositeAlpha'] ?? 0),
            presentMode: (int) ($members['presentMode'] ?? 0),
            clipped: (bool) ($members['clipped'] ?? false),
            oldSwapchain: (int) ($members['oldSwapchain'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkSwapchainCreateInfoKHR::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkSwapchainCreateInfoKHR::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkSwapchainCreateInfoKHR::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkSwapchainCreateInfoKHR::size();
    }
}
