<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkVertexInputRate;
use Vulkan\Struct\VkVertexInputBindingDescription\VkVertexInputBindingDescription as ExtVkVertexInputBindingDescription;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkVertexInputBindingDescription">, 3 members.
 *
 * The typed shape of the array ExtVkVertexInputBindingDescription::pack() takes and
 * ExtVkVertexInputBindingDescription::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkVertexInputBindingDescription
{
    public function __construct(
        public int $binding = 0,
        public int $stride = 0,
        public VkVertexInputRate|int $inputRate = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['binding'] = $this->binding;
        $members['stride'] = $this->stride;
        $members['inputRate'] = $this->inputRate instanceof \BackedEnum ? $this->inputRate->value : $this->inputRate;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            binding: (int) ($members['binding'] ?? 0),
            stride: (int) ($members['stride'] ?? 0),
            inputRate: (int) ($members['inputRate'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkVertexInputBindingDescription::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkVertexInputBindingDescription::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkVertexInputBindingDescription::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkVertexInputBindingDescription::size();
    }
}
