<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkFormat;
use Vulkan\Struct\VkVertexInputAttributeDescription\VkVertexInputAttributeDescription as ExtVkVertexInputAttributeDescription;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkVertexInputAttributeDescription">, 4 members.
 *
 * The typed shape of the array ExtVkVertexInputAttributeDescription::pack() takes and
 * ExtVkVertexInputAttributeDescription::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkVertexInputAttributeDescription
{
    public function __construct(
        public int $location = 0,
        public int $binding = 0,
        public VkFormat|int $format = 0,
        public int $offset = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['location'] = $this->location;
        $members['binding'] = $this->binding;
        $members['format'] = $this->format instanceof \BackedEnum ? $this->format->value : $this->format;
        $members['offset'] = $this->offset;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            location: (int) ($members['location'] ?? 0),
            binding: (int) ($members['binding'] ?? 0),
            format: (int) ($members['format'] ?? 0),
            offset: (int) ($members['offset'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkVertexInputAttributeDescription::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkVertexInputAttributeDescription::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkVertexInputAttributeDescription::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkVertexInputAttributeDescription::size();
    }
}
