<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkVertexInputBindingDivisorDescription\VkVertexInputBindingDivisorDescription as ExtVkVertexInputBindingDivisorDescription;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkVertexInputBindingDivisorDescription">, 2 members.
 *
 * The typed shape of the array ExtVkVertexInputBindingDivisorDescription::pack() takes and
 * ExtVkVertexInputBindingDivisorDescription::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkVertexInputBindingDivisorDescription
{
    public function __construct(
        public int $binding = 0,
        public int $divisor = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['binding'] = $this->binding;
        $members['divisor'] = $this->divisor;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            binding: (int) ($members['binding'] ?? 0),
            divisor: (int) ($members['divisor'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkVertexInputBindingDivisorDescription::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkVertexInputBindingDivisorDescription::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkVertexInputBindingDivisorDescription::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkVertexInputBindingDivisorDescription::size();
    }
}
