<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Vulkan\Struct\VkViewport\VkViewport as ExtVkViewport;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkViewport">, 6 members.
 *
 * The typed shape of the array ExtVkViewport::pack() takes and
 * ExtVkViewport::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkViewport
{
    public function __construct(
        public float $x = 0.0,
        public float $y = 0.0,
        public float $width = 0.0,
        public float $height = 0.0,
        public float $minDepth = 0.0,
        public float $maxDepth = 0.0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['x'] = $this->x;
        $members['y'] = $this->y;
        $members['width'] = $this->width;
        $members['height'] = $this->height;
        $members['minDepth'] = $this->minDepth;
        $members['maxDepth'] = $this->maxDepth;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            x: (float) ($members['x'] ?? 0.0),
            y: (float) ($members['y'] ?? 0.0),
            width: (float) ($members['width'] ?? 0.0),
            height: (float) ($members['height'] ?? 0.0),
            minDepth: (float) ($members['minDepth'] ?? 0.0),
            maxDepth: (float) ($members['maxDepth'] ?? 0.0),
        );
    }

    public function pack(): int
    {
        return ExtVkViewport::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkViewport::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkViewport::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkViewport::size();
    }
}
