<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkWriteDescriptorSetInlineUniformBlock\VkWriteDescriptorSetInlineUniformBlock as ExtVkWriteDescriptorSetInlineUniformBlock;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkWriteDescriptorSetInlineUniformBlock">, 4 members.
 *
 * The typed shape of the array ExtVkWriteDescriptorSetInlineUniformBlock::pack() takes and
 * ExtVkWriteDescriptorSetInlineUniformBlock::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkWriteDescriptorSetInlineUniformBlock
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::WRITE_DESCRIPTOR_SET_INLINE_UNIFORM_BLOCK,
        public int $pNext = 0,
        public int $dataSize = 0,
        public int $pData = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['dataSize'] = $this->dataSize;
        $members['pData'] = $this->pData;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            dataSize: (int) ($members['dataSize'] ?? 0),
            pData: (int) ($members['pData'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkWriteDescriptorSetInlineUniformBlock::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkWriteDescriptorSetInlineUniformBlock::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkWriteDescriptorSetInlineUniformBlock::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkWriteDescriptorSetInlineUniformBlock::size();
    }
}
