<?php

declare(strict_types=1);

namespace Jovian\Bindings\Vulkan\Structs;

use Jovian\Bindings\Vulkan\Enums\VkStructureType;
use Vulkan\Struct\VkXcbSurfaceCreateInfoKHR\VkXcbSurfaceCreateInfoKHR as ExtVkXcbSurfaceCreateInfoKHR;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Source: vk.xml <type category="struct" name="VkXcbSurfaceCreateInfoKHR">, 5 members.
 *
 * The typed shape of the array ExtVkXcbSurfaceCreateInfoKHR::pack() takes and
 * ExtVkXcbSurfaceCreateInfoKHR::unpack() returns. toArray() is this object flattened,
 * fromArray() is its inverse, and each of the four binding methods is
 * exactly one extension call.
 */
final readonly class VkXcbSurfaceCreateInfoKHR
{
    public function __construct(
        public VkStructureType|int $sType = VkStructureType::XCB_SURFACE_CREATE_INFO_KHR,
        public int $pNext = 0,
        public int $flags = 0,
        public int $connection = 0,
        public int $window = 0,
    ) {}

    /**
     * @return array<string, mixed> the shape ext-vulkan's pack() takes
     */
    public function toArray(): array
    {
        $members = [];
        $members['sType'] = $this->sType instanceof \BackedEnum ? $this->sType->value : $this->sType;
        $members['pNext'] = $this->pNext;
        $members['flags'] = $this->flags;
        $members['connection'] = $this->connection;
        $members['window'] = $this->window;

        return $members;
    }

    /**
     * @param  array<string, mixed>  $members  the shape ext-vulkan's unpack() returns
     */
    public static function fromArray(array $members): self
    {
        return new self(
            sType: (int) ($members['sType'] ?? 0),
            pNext: (int) ($members['pNext'] ?? 0),
            flags: (int) ($members['flags'] ?? 0),
            connection: (int) ($members['connection'] ?? 0),
            window: (int) ($members['window'] ?? 0),
        );
    }

    public function pack(): int
    {
        return ExtVkXcbSurfaceCreateInfoKHR::pack($this->toArray());
    }

    public function packInto(int $ptr): void
    {
        ExtVkXcbSurfaceCreateInfoKHR::packInto($ptr, $this->toArray());
    }

    public static function unpack(int $ptr): self
    {
        return self::fromArray(ExtVkXcbSurfaceCreateInfoKHR::unpack($ptr));
    }

    public static function size(): int
    {
        return ExtVkXcbSurfaceCreateInfoKHR::size();
    }
}
